/**
 * amenbo Viewer's drop box.
 *
 * This Worker is deployed into the **user's own** Cloudflare account — the plugin stands it up
 * there and then hands over ownership. Nothing about it is hosted by anyone else, which is why
 * it is written to know as little as possible:
 *
 * - **It does not understand what it stores.** One opaque blob, encrypted on the PC and
 *   decrypted on the phone. Give it a schema and every schema change becomes a redeploy across
 *   every user's account, with no way to roll anyone forward centrally.
 * - **It never sees the key.** That reaches the phone by QR, off the network. An account
 *   someone takes over still yields nothing but ciphertext.
 * - **It is written to, and read from, and nothing else.** No accounts, no sessions, no
 *   listing. One long random token decides who may do either.
 *
 * ## Skeleton
 *
 * The shape is here; the handlers are not. What a snapshot looks like inside — where its
 * version number sits, which the `PUT` has to read to refuse a rollback and `GET /meta` has to
 * answer with — is the shared contract in `spec/`, and it is not written yet. So the routing,
 * the method handling and the token gate are real and tested, and the three handlers answer
 * 501 rather than guessing at a format three other parts have to live with.
 */

/**
 * The bindings, extending what `wrangler types` reads out of wrangler.jsonc — so the KV
 * namespace is declared in one place and a binding added to the config arrives here rather than
 * being spelled a second time.
 *
 * The Secret is the part wrangler cannot know: it is set on the deployed Worker and never
 * appears in the config, so it is declared by hand.
 */
export interface Env extends Cloudflare.Env {
	/**
	 * The token that decides who may read and who may write — a Secret, so it does not come
	 * back out of the dashboard once set. Generated by the plugin at setup; never chosen by a
	 * person, and never a password.
	 */
	AUTH_TOKEN: string;
}

/** The key the snapshot is written under. Always this one, always overwritten. */
export const SNAPSHOT_KEY = "snapshot";

/** What every handler answers with while the shared contract is unwritten. */
const WAITING_ON_SPEC =
	"not built yet — this endpoint waits on the shared contract in spec/ (the snapshot format and its version number)";

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		// A Worker with no token set lets nobody in — but that is a fault in the deployment,
		// not a caller who guessed wrong, and saying so is what makes it fixable. It cannot be
		// mistaken for a leak: there is no token to compare against, so nothing is let through.
		if (!env.AUTH_TOKEN) {
			return problem(503, "this Worker has no AUTH_TOKEN set — run `wrangler secret put AUTH_TOKEN`");
		}

		// The gate comes before the routing, so an unauthorised caller learns nothing about the
		// shape of what is behind it — not which paths exist, not which methods they take.
		if (!authorised(request, env.AUTH_TOKEN)) {
			return problem(401, "a bearer token is required", { "WWW-Authenticate": "Bearer" });
		}

		const { pathname } = new URL(request.url);
		const allowed = ROUTES[pathname];
		if (!allowed) {
			return problem(404, "no such endpoint");
		}
		if (!allowed.includes(request.method)) {
			return problem(405, `${request.method} is not allowed here`, { Allow: allowed.join(", ") });
		}
		return problem(501, WAITING_ON_SPEC);
	},
} satisfies ExportedHandler<Env>;

/**
 * The three endpoints, and the methods each one takes. HEAD rides along with GET because the
 * runtime answers it from the GET handler, and a phone checking for a new snapshot may well use
 * it.
 *
 * | | |
 * |---|---|
 * | `PUT /snapshot`  | takes the ciphertext and overwrites the one key. Refuses a version at or behind the stored one, so a replayed send cannot roll the phone back |
 * | `GET /snapshot`  | hands the ciphertext back |
 * | `GET /meta`      | the version and when it landed — what the phone asks before spending bytes on the snapshot itself |
 */
const ROUTES: Record<string, string[]> = {
	"/snapshot": ["PUT", "GET", "HEAD"],
	"/meta": ["GET", "HEAD"],
};

/**
 * Reads the bearer token off the request and compares it to the configured one without leaking
 * how far the comparison got.
 *
 * `timingSafeEqual` throws on a length mismatch rather than answering false, so the lengths are
 * checked first — and a differing length is not itself a secret worth hiding, since the token's
 * length is fixed by whoever generated it and identical for everyone.
 */
function authorised(request: Request, expected: string): boolean {
	const header = request.headers.get("Authorization") ?? "";
	const [scheme, ...rest] = header.split(" ");
	if (scheme.toLowerCase() !== "bearer") {
		return false;
	}
	const offered = new TextEncoder().encode(rest.join(" "));
	const wanted = new TextEncoder().encode(expected);
	if (offered.byteLength !== wanted.byteLength) {
		return false;
	}
	return crypto.subtle.timingSafeEqual(offered, wanted);
}

/**
 * One shape for every refusal, so a caller can read the reason without guessing at the body.
 * The status is the verdict; the sentence is for whoever has to fix it.
 */
function problem(status: number, detail: string, headers: Record<string, string> = {}): Response {
	return Response.json({ error: detail }, { status, headers });
}
