/**
 * amenbo Viewer's drop box.
 *
 * This Worker is deployed into the **user's own** Cloudflare account — the plugin stands it up
 * there and then hands over ownership. Nothing about it is hosted by anyone else, which is why
 * it is written to know as little as possible:
 *
 * - **It does not understand what it stores.** A key it was handed and bytes it cannot read,
 *   sealed on the PC and opened on the phone. Give it a schema and every schema change becomes
 *   a redeploy across every user's account, with no way to roll anyone forward centrally.
 * - **It never sees the key.** That reaches the phone by QR, off the network. An account
 *   someone takes over still yields nothing but ciphertext.
 * - **It is written to, and read from, and nothing else.** No accounts, no sessions, no
 *   listing.
 *
 * ## Two kinds of token
 *
 * The PC writes and the phones read, and they do not hold the same credential.
 *
 * | | where it lives | what it may do |
 * |---|---|---|
 * | the write token | a Secret on this Worker, one of them | every `PUT` and `DELETE` |
 * | a read token | one row per phone, **as a hash** | every `GET` |
 *
 * **The point is being able to cut off one phone.** One shared token would mean a single lost
 * phone re-pairs every other one, so the phones get one each — and since this Worker only ever
 * compares, it keeps the hashes rather than the tokens, and a copy of the table is not a set of
 * credentials.
 *
 * ## Skeleton
 *
 * The storage, the gate and the token endpoints are here. The record endpoints answer 501 rather
 * than pretending, so nothing can be built on top of them believing a record landed.
 */

/**
 * The bindings, extending what `wrangler types` reads out of wrangler.jsonc — so the database is
 * declared in one place and a binding added to the config arrives here rather than being spelled
 * a second time.
 *
 * The Secret is the part wrangler cannot know: it is set on the deployed Worker and never
 * appears in the config, so it is declared by hand.
 */
export interface Env extends Cloudflare.Env {
	/**
	 * The token that lets the PC write — a Secret, so it does not come back out of the
	 * dashboard once set. Generated by the plugin at setup; never chosen by a person, and never
	 * a password. There is one, and it is not the one the phones hold.
	 */
	WRITE_TOKEN: string;
}

/** What an endpoint that has no handler behind it yet answers with. */
const NOT_BUILT_YET = "not built yet — this endpoint has no handler behind it";

/** Which kind of token a request has to be carrying. */
type Kind = "write" | "read";

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		// A Worker with no write token set lets nobody write — but that is a fault in the
		// deployment, not a caller who guessed wrong, and saying so is what makes it fixable. It
		// cannot be mistaken for a leak: there is nothing to compare against, so nothing is let
		// through.
		if (!env.WRITE_TOKEN) {
			return problem(503, "this Worker has no WRITE_TOKEN set — run `wrangler secret put WRITE_TOKEN`");
		}

		// The gate comes before the routing, so a caller carrying nothing we know learns nothing
		// about the shape of what is behind it — not which paths exist, not which methods they
		// take.
		const carrying = await kindOffered(request, env);
		if (!carrying) {
			return problem(401, "a bearer token is required", { "WWW-Authenticate": "Bearer" });
		}

		const { pathname } = new URL(request.url);
		const labelled = pathname.match(LABELLED_TOKEN);
		const allowed = labelled ? TOKEN_METHODS : ROUTES[pathname];
		if (!allowed) {
			return problem(404, "no such endpoint");
		}
		const wanted = allowed[request.method];
		if (!wanted) {
			return problem(405, `${request.method} is not allowed here`, { Allow: Object.keys(allowed).join(", ") });
		}
		// Past this point the caller is known, so telling them their token is the wrong kind for
		// this door gives away nothing they could not already see.
		if (wanted !== carrying) {
			return problem(403, `this endpoint takes the ${wanted} token, and a ${carrying} token was offered`);
		}

		if (labelled) {
			return revoke(env, decodeURIComponent(labelled[1]));
		}
		if (pathname === "/tokens") {
			return issue(env, request);
		}
		return problem(501, NOT_BUILT_YET);
	},
} satisfies ExportedHandler<Env>;

/**
 * The endpoints, the methods each one takes, and which token each method wants. HEAD rides along
 * with GET because the runtime answers it from the GET handler, and a phone checking for
 * something new may well use it.
 *
 * | | |
 * |---|---|
 * | `PUT /snapshot`  | takes the ciphertext. Refuses a version at or behind the stored one, so a replayed send cannot roll the phone back |
 * | `GET /snapshot`  | hands the ciphertext back |
 * | `GET /meta`      | the version and when it landed — what the phone asks before spending bytes on the records themselves |
 * | `PUT /tokens`    | lets one more phone read |
 */
const ROUTES: Record<string, Record<string, Kind>> = {
	"/snapshot": { PUT: "write", GET: "read", HEAD: "read" },
	"/meta": { GET: "read", HEAD: "read" },
	"/tokens": { PUT: "write" },
};

/** `DELETE /tokens/<label>` — the one endpoint whose path names what it acts on. */
const LABELLED_TOKEN = /^\/tokens\/(.+)$/;
const TOKEN_METHODS: Record<string, Kind> = { DELETE: "write" };

/**
 * Works out which kind of token the request is carrying, or none.
 *
 * The write token is compared without leaking how far the comparison got. The read tokens are
 * looked up by their hash instead, and that lookup is not constant time — it does not need to
 * be, because what a timing difference could give away is a hash, and a hash is not what gets
 * anyone in.
 */
async function kindOffered(request: Request, env: Env): Promise<Kind | null> {
	const offered = bearer(request);
	if (offered === null) {
		return null;
	}
	if (sameSecret(offered, env.WRITE_TOKEN)) {
		return "write";
	}
	const known = await env.RECORDS.prepare("SELECT 1 FROM tokens WHERE hash = ?").bind(await sha256(offered)).first();
	return known ? "read" : null;
}

/** Reads the bearer token off the request, or null when there is not one. */
function bearer(request: Request): string | null {
	const header = request.headers.get("Authorization") ?? "";
	const [scheme, ...rest] = header.split(" ");
	if (scheme.toLowerCase() !== "bearer") {
		return null;
	}
	const offered = rest.join(" ");
	return offered === "" ? null : offered;
}

/**
 * Compares two secrets without leaking how far the comparison got.
 *
 * `timingSafeEqual` throws on a length mismatch rather than answering false, so the lengths are
 * checked first — and a differing length is not itself a secret worth hiding, since the token's
 * length is fixed by whoever generated it and identical for everyone.
 */
function sameSecret(offered: string, expected: string): boolean {
	const a = new TextEncoder().encode(offered);
	const b = new TextEncoder().encode(expected);
	if (a.byteLength !== b.byteLength) {
		return false;
	}
	return crypto.subtle.timingSafeEqual(a, b);
}

/** A token's hash as this Worker writes and compares it: SHA-256, lower-case hex. */
async function sha256(text: string): Promise<string> {
	const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
	return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/** A hash as it may be written down: SHA-256 is 32 bytes, so 64 hex characters and nothing else. */
const HASH = /^[0-9a-f]{64}$/i;

/**
 * `PUT /tokens` — lets one more phone read.
 *
 * **The token itself never arrives.** The PC generates it, shows it on a QR, and sends only its
 * hash, so the value exists on the PC and on the phone that photographed it and nowhere else.
 *
 * Issuing under a label that is already there replaces it, which is what re-pairing the same
 * phone means: the previous token stops working the moment the new one is issued, rather than
 * both being live until someone remembers to revoke.
 */
async function issue(env: Env, request: Request): Promise<Response> {
	let asked: unknown;
	try {
		asked = await request.json();
	} catch {
		return problem(400, "the body has to be a JSON object");
	}
	const { label, hash } = (asked ?? {}) as { label?: unknown; hash?: unknown };
	if (typeof label !== "string" || label.trim() === "") {
		return problem(400, "a token needs a label — it is what revoking one names");
	}
	if (typeof hash !== "string" || !HASH.test(hash)) {
		return problem(400, "the hash has to be a SHA-256 as 64 hex characters");
	}

	const issued_at = new Date().toISOString();
	await env.RECORDS.prepare(
		"INSERT INTO tokens (label, hash, issued_at) VALUES (?, ?, ?)" +
			" ON CONFLICT (label) DO UPDATE SET hash = excluded.hash, issued_at = excluded.issued_at",
	)
		.bind(label.trim(), hash.toLowerCase(), issued_at)
		.run();

	return Response.json({ label: label.trim(), issued_at });
}

/**
 * `DELETE /tokens/<label>` — cuts one phone off, and nothing else.
 *
 * A label that is not there is answered as not found rather than shrugged off. Revoking is what
 * someone does when a phone is lost, and a typo that answered "done" would leave them believing
 * they had cut off a phone that is still reading.
 */
async function revoke(env: Env, label: string): Promise<Response> {
	const gone = await env.RECORDS.prepare("DELETE FROM tokens WHERE label = ?").bind(label).run();
	if (!gone.meta.changes) {
		return problem(404, `no token is labelled ${JSON.stringify(label)}`);
	}
	return Response.json({ label });
}

/**
 * One shape for every refusal, so a caller can read the reason without guessing at the body.
 * The status is the verdict; the sentence is for whoever has to fix it.
 */
function problem(status: number, detail: string, headers: Record<string, string> = {}): Response {
	return Response.json({ error: detail }, { status, headers });
}
