/**
 * Amenbo Viewer's drop box.
 *
 * This Worker is deployed into the **user's own** Cloudflare account — the plugin stands it up
 * there and then hands over ownership. Nothing about it is hosted by anyone else, which is why
 * it is written to know as little as possible:
 *
 * - **It does not understand what it stores.** A key it was handed and bytes it cannot read,
 *   sealed on the PC and opened on the phone. Give it a schema and every schema change becomes
 *   a redeploy across every user's account, with no way to roll anyone forward centrally.
 * - **It never sees the key.** That reaches the phone by QR, off the network. An account
 *   someone takes over still yields nothing but ciphertext.
 * - **It is written to, and read from, and nothing else.** No accounts, no sessions, no
 *   listing.
 *
 * ## Two kinds of token
 *
 * The PC writes and the phones read, and they do not hold the same credential.
 *
 * | | where it lives | what it may do |
 * |---|---|---|
 * | the write token | a Secret on this Worker, one of them | every door |
 * | the read code | one row, **as a hash** | every `GET` |
 *
 * **What the split protects is the phone's half.** A code photographed off somebody's screen puts
 * nothing into the store, which is the whole of why there are two. The other direction was never
 * the point: the PC holds the encryption key and the backlog the records were sealed from, so a
 * write token that can also read learns nothing it did not hand over. It used to be refused there
 * anyway, and the comparison `repair` runs had to issue itself a read code to get past it — which,
 * with one code in the store, is the phone's.
 *
 * **There is one read code, not one per phone.** It used to be a row per phone, keyed by a name,
 * so that one could be cut off by naming it. But this Worker compares a hash and never learns
 * which phone offered it: one code photographed by three phones is one row here and all three
 * read. The name named something on the PC and nothing in the store.
 *
 * So the store holds a code, present or absent. Issuing replaces what was there and cuts whoever
 * held it. And since this Worker only ever compares, it keeps the hash rather than the code — a
 * copy of the table is not a credential.
 *
 * ## The order is the whole protocol
 *
 * Every record placed takes the next number in one ever-climbing order, and a phone remembers the
 * number it got to. Reading is "everything after this point", which is what makes a phone that
 * was away for a week cost the same as one that was away for a minute: what it is handed is what
 * moved, not what exists.
 *
 * The number is kept on the store row rather than counted off the records, because a reset
 * empties the records and the order has to survive it — see the migration that adds it.
 */

/**
 * The bindings, extending what `wrangler types` reads out of wrangler.jsonc — so the database is
 * declared in one place and a binding added to the config arrives here rather than being spelled
 * a second time.
 *
 * The Secret is the part wrangler cannot know: it is set on the deployed Worker and never
 * appears in the config, so it is declared by hand.
 */
export interface Env extends Cloudflare.Env {
	/**
	 * The token that lets the PC write — a Secret, so it does not come back out of the
	 * dashboard once set. Generated by the plugin at setup; never chosen by a person, and never
	 * a password. There is one, and it is not the one the phones hold.
	 */
	WRITE_TOKEN: string;
}

/**
 * The version of the shared contract this Worker speaks. It is not Amenbo's format version: this
 * one moves when the four parts change what they say to each other, and it travels on everything
 * this Worker sends so a phone can refuse a version it does not read rather than guess.
 */
const SPEC_V = 1;

/**
 * Which build of this Worker this is.
 *
 * **It is here because this is the one part that cannot be updated.** It runs in the user's own
 * Cloudflare account and changes only when they press setup, so a sender has to be able to find
 * out what it is talking to — and it has to find out with the token it holds, which is the write
 * one. So the number travels on the answer to a write.
 *
 * **`1` is every Worker deployed before this field existed.** A sender that reads no number at
 * all is talking to one of those, which is exactly what it needs to know.
 *
 * **It moves when a Worker already standing has to be replaced for something to work.** `3` is
 * the reading door opening to the write token, and the single pairing code that came with it
 * (migration `0006`): against a `2` the PC can write and cannot read back what it wrote, so
 * `repair` compares against nothing. The plugin carries this same number for the Worker it
 * deploys, and compares the two — which is how a settings screen can say the server is behind.
 */
const BUILD = 3;

/**
 * How many records one read hands back before saying there are more.
 *
 * A phone reads a page, writes it, and comes back for the next — so this bounds what has to be
 * held in memory at either end, on a first sync as much as on a small one.
 */
const PER_PAGE = 200;

/**
 * How many records one write may carry.
 *
 * The point is that too much is refused at the door with a sentence saying so, rather than
 * failing somewhere inside the database where the sender learns only that it did not work.
 *
 * A backlog outgrows this the moment it is placed whole, so the refusal is not the end of the
 * road: a sender that has more than this splits it into parts and says which one each is — see
 * `place`.
 */
const PER_WRITE = 500;

/**
 * How many keys one `?keys=1` read hands back before saying there are more.
 *
 * It is larger than a page of records because a key is a fraction of one: what comes back is a
 * string and a word, not an envelope, so the same answer size carries far more of them. Reading
 * the whole store's keys is what a sender does to find out what is here that the backlog no
 * longer has, and doing it a page of two hundred at a time would be a hundred and twenty requests
 * for something a dozen can carry.
 */
const PER_KEY_PAGE = 2000;

/** Which kind of token a request is carrying. */
type Kind = "write" | "read";

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		// A Worker with no write token set lets nobody write — but that is a fault in the
		// deployment, not a caller who guessed wrong, and saying so is what makes it fixable. It
		// cannot be mistaken for a leak: there is nothing to compare against, so nothing is let
		// through.
		if (!env.WRITE_TOKEN) {
			return problem(503, "this Worker has no WRITE_TOKEN set — run `wrangler secret put WRITE_TOKEN`");
		}

		// The gate comes before the routing, so a caller carrying nothing we know learns nothing
		// about the shape of what is behind it — not which paths exist, not which methods they
		// take.
		const carrying = await kindOffered(request, env);
		if (!carrying) {
			return problem(401, "a bearer token is required", { "WWW-Authenticate": "Bearer" });
		}

		const url = new URL(request.url);
		const { pathname } = url;
		const allowed = ROUTES[pathname];
		if (!allowed) {
			return problem(404, "no such endpoint");
		}
		const wanted = allowed[request.method];
		if (!wanted) {
			return problem(405, `${request.method} is not allowed here`, { Allow: Object.keys(allowed).join(", ") });
		}
		// Past this point the caller is known, so telling them their token is the wrong kind for
		// this door gives away nothing they could not already see.
		if (!wanted.includes(carrying)) {
			return problem(
				403,
				`this endpoint takes the ${wanted.join(" or the ")} token, and a ${carrying} token was offered`,
			);
		}

		// **Anything thrown is answered the same way, and the answer carries what was said.**
		// Telling one failure from another meant reading the sentence D1 threw, and the reading
		// was wrong in the direction that costs money: a database briefly unreachable came back
		// as "buy more storage". This Worker cannot be updated when that reading turns out to be
		// wrong, so it does not read — it hands the sentence on to the part that can be.
		try {
			switch (pathname) {
				case "/records":
					return request.method === "PUT" ? await place(env, request) : await read(env, url);
				case "/reset":
					return gone();
				case "/meta":
					return await meta(env);
				default:
					// The routes are the four above and `/tokens`, and anything else was turned
					// away as a missing endpoint before it got here.
					return await tokens(env, request);
			}
		} catch (thrown) {
			return unavailable(thrown);
		}
	},
} satisfies ExportedHandler<Env>;

/**
 * Who may read: the phone, and the PC that wrote it.
 *
 * **The read code is named first because it is the ordinary reader.** The write token is here so
 * that the PC can compare what is in the store with what it holds without issuing itself a read
 * code — which, now that the store keeps one, would be the phone's.
 */
const READING: Kind[] = ["read", "write"];

/**
 * The endpoints, the methods each one takes, and which tokens each method lets through. HEAD rides
 * along with GET because the runtime answers it from the GET handler, and a phone checking for
 * something new may well use it.
 *
 * | | |
 * |---|---|
 * | `PUT /records` | takes the records that moved, deletions among them, and answers with where the order now stands |
 * | `GET /records` | hands back everything after a point in the order, a page at a time — or, with `keys=1`, the keys alone |
 * | `GET /meta`    | the version, the order, when it last moved and which key sealed the records — the cheap question |
 * | `PUT /reset`   | **gone.** It is still routed so that what a caller gets is a sentence rather than a guess — see `gone` |
 * | `PUT /tokens`    | hands out the read code, replacing whatever was there |
 * | `DELETE /tokens` | takes it away, so nothing reads until one is issued again |
 * | `GET /tokens`    | whether there is one, and when it was issued — the write token's question, not a phone's |
 */
const ROUTES: Record<string, Record<string, Kind[]>> = {
	"/records": { PUT: ["write"], GET: READING, HEAD: READING },
	"/reset": { PUT: ["write"] },
	"/meta": { GET: READING, HEAD: READING },
	"/tokens": { PUT: ["write"], DELETE: ["write"], GET: ["write"], HEAD: ["write"] },
};

/**
 * `/tokens` — the three things that can be done to the one read code.
 *
 * The path names no code, so which of them this is comes off the method alone. Anything but these
 * three was turned away as a method the endpoint does not take, before it got here.
 */
function tokens(env: Env, request: Request): Promise<Response> {
	switch (request.method) {
		case "PUT":
			return issue(env, request);
		case "DELETE":
			return revoke(env);
		default:
			return pairing(env);
	}
}

/**
 * Works out which kind of token the request is carrying, or none.
 *
 * The write token is compared without leaking how far the comparison got. The read code is looked
 * up by its hash instead, and that lookup is not constant time — it does not need to be, because
 * what a timing difference could give away is a hash, and a hash is not what gets anyone in.
 */
async function kindOffered(request: Request, env: Env): Promise<Kind | null> {
	const offered = bearer(request);
	if (offered === null) {
		return null;
	}
	if (sameSecret(offered, env.WRITE_TOKEN)) {
		return "write";
	}
	const known = await env.RECORDS.prepare("SELECT 1 FROM tokens WHERE hash = ?").bind(await sha256(offered)).first();
	return known ? "read" : null;
}

/** Reads the bearer token off the request, or null when there is not one. */
function bearer(request: Request): string | null {
	const header = request.headers.get("Authorization") ?? "";
	const [scheme, ...rest] = header.split(" ");
	if (scheme.toLowerCase() !== "bearer") {
		return null;
	}
	const offered = rest.join(" ");
	return offered === "" ? null : offered;
}

/**
 * Compares two secrets without leaking how far the comparison got.
 *
 * `timingSafeEqual` throws on a length mismatch rather than answering false, so the lengths are
 * checked first — and a differing length is not itself a secret worth hiding, since the token's
 * length is fixed by whoever generated it and identical for everyone.
 */
function sameSecret(offered: string, expected: string): boolean {
	const a = new TextEncoder().encode(offered);
	const b = new TextEncoder().encode(expected);
	if (a.byteLength !== b.byteLength) {
		return false;
	}
	return crypto.subtle.timingSafeEqual(a, b);
}

/** A token's hash as this Worker writes and compares it: SHA-256, lower-case hex. */
async function sha256(text: string): Promise<string> {
	const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
	return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * Where the store as a whole stands: the version of the backlog its records came from, how far
 * the order has got, and when it last moved. One row, so this is a read of it and not a search.
 */
interface Standing {
	version: number | null;
	seq: number;
	updated_at: string | null;
	/**
	 * The point the placement now standing in the records began above. A cursor that has not
	 * passed it holds nothing from that placement — see `read`.
	 */
	placed_from: number;
	/**
	 * The fingerprint of the key the records here were sealed with, as the sender named it, or
	 * null for a store nobody has named one over. It is a hash and never a key — see the
	 * migration that adds it.
	 */
	key_fingerprint: string | null;
}

/** Reads that row. It is there from the first migration, so there is no "no store yet" to handle. */
async function standing(env: Env): Promise<Standing> {
	const row = await env.RECORDS.prepare(
		"SELECT version, seq, updated_at, placed_from, key_fingerprint FROM store WHERE id = 1",
	).first<Standing>();
	return row!;
}

/**
 * The answer `PUT /reset` gives now: it is gone, and it is not coming back.
 *
 * **It emptied the records before taking the first part of the whole store**, so between that and
 * the last part landing, what was here was a fraction of a backlog — which is why both reading
 * doors closed for the length of it. On a slow send that is hours of a phone reading nothing, and
 * a placement nobody finished left the doors shut for good: the flag came down with the last part
 * alone, and after an abandonment that part never arrives. A store like that is writable and
 * permanently unreadable, and nothing in it can put itself right.
 *
 * What replaced it places over what is there, key by key, and never closes anything.
 *
 * **410 and not 404.** A sender told there is no such endpoint reads a Worker it does not
 * recognise and says to press setup, which on an old plugin deploys the Worker that has this door
 * — round and round. A sender told the door is gone reads the sentence.
 *
 * **The door is not simply removed, either.** Removing it would answer 404, which is the reading
 * above; and leaving it routed but doing nothing would be worse than both, because a sender would
 * believe a store it asked to empty had been emptied.
 */
function gone(): Response {
	return problem(
		410,
		"this store is no longer emptied and filled again — records are placed over what is here," +
			" key by key, through `PUT /records`. Nothing has to be done to a store to make it take them",
	);
}

/**
 * The answer to anything thrown, whatever threw it.
 *
 * **This Worker does not read the sentence.** Telling a full database from an unreachable one
 * meant matching on the text D1 threw, because the binding throws a plain `Error` with no code
 * and no status; and a reading that is wrong sends someone to buy storage they do not need. The
 * Worker in the user's account is the one part that cannot be corrected when a reading like that
 * turns out to be wrong, so it hands the sentence to the sender, whose build can be.
 *
 * **`Retry-After` is longer than ten seconds on purpose.** The phone reads the number, not the
 * reason: ten or under means "the PC is still sending", and anything above means the store cannot
 * answer right now. A full database answered as the first would have every phone saying the PC is
 * busy, forever.
 */
function unavailable(thrown: unknown): Response {
	const said = thrown instanceof Error ? thrown.message : String(thrown);
	return problem(503, `this store could not answer: ${said}`, { "Retry-After": "60" });
}

/**
 * `GET /meta` — the cheap question, asked before the expensive one.
 *
 * A phone that is level with the store learns so for the price of one small answer, which is what
 * lets it ask often. `seq` is the point the records have reached, so a phone compares it with the
 * one it holds rather than fetching to find out.
 *
 * `placed_from` is the other number it compares against: a cursor that has not passed it holds
 * nothing from the placement standing here, so the answer is to throw that copy away rather than
 * read on from it. A phone that acts on it here is spared the refusal `read` would give it.
 *
 * `key_fingerprint` is the third, and it is the one that saves a sync rather than a page: a phone
 * whose own key hashes to something else cannot open a single row here, and learning that costs
 * one small answer instead of a whole fetch that decrypts to nothing. **Null is not a mismatch**
 * — it is a store nobody has named a key over, which is every store written by a sender older
 * than the field, so there is nothing to compare and the phone carries on.
 */
async function meta(env: Env): Promise<Response> {
	const now = await standing(env);
	return Response.json({
		spec_v: SPEC_V,
		version: now.version,
		seq: now.seq,
		updated_at: now.updated_at,
		placed_from: now.placed_from,
		key_fingerprint: now.key_fingerprint,
	});
}

/** A record as the table holds it, but for the place in the order the store hands it. */
interface Landing {
	k: string;
	op: "put" | "del";
	nonce: string | null;
	ciphertext: string | null;
}

/** One that has its place. */
interface Stored extends Landing {
	seq: number;
}

/**
 * `GET /records?since=<seq>` — everything after a point in the order, a page at a time.
 *
 * The page carries the point it reached, which is what the phone remembers and asks from next
 * time. `more` is how it knows to come straight back rather than wait for the next write: the
 * version only becomes the phone's once `more` is false, since until then it holds half a turn.
 *
 * **A cursor past the end is refused rather than answered.** The order never rewinds, so being
 * ahead of it means these are not the records that cursor was counted against — a store rebuilt
 * from nothing under a phone that was paired with the old one. Answering the tail would hand it
 * somebody else's rows under numbers it recognises.
 *
 * **A cursor that has not passed the current placement is refused too**, and for a reason that
 * looks nothing like it from the phone's side. Reading on from there would succeed and return
 * rows, which is what makes it dangerous: a record deleted before the placement is in neither
 * what is here nor what is coming, so the phone would keep it and call itself level. The remedy
 * is the same either way — throw the copy away and read again — so both refusals are the same
 * status, differing in what they say.
 *
 * **Being refused is not left to the phone to avoid.** `GET /meta` carries `placed_from` so a
 * phone can check before asking, but a phone that does not check must not be handed a quiet
 * wrong answer for it. `since=0` is the phone having thrown its copy away, and is served.
 *
 * ## `keys=1` — the same read, without the envelopes
 *
 * **What is here that the backlog no longer has cannot be worked out from this end.** This Worker
 * does not know what a key means, so the sender is the only one that can compare, and comparing
 * means reading every key. The whole answer is 27 MB of envelopes for a question that turns on
 * the strings alone.
 *
 * So `keys=1` hands back `k` and `op` and nothing else, a larger page at a time. **`op` travels
 * because a deletion is a row here**: a key whose last word was `del` is a headstone, not
 * something the store holds, and a sender that could not tell them apart would send a delete for
 * every one of them, every time.
 */
async function read(env: Env, url: URL): Promise<Response> {
	const asked = url.searchParams.get("since") ?? "0";
	if (!/^\d+$/.test(asked)) {
		return problem(400, "since has to be a whole number — the point in the order to read on from");
	}
	const since = Number(asked);
	const keysOnly = url.searchParams.get("keys") === "1";

	const now = await standing(env);
	if (since > now.seq) {
		return problem(
			409,
			`the order here has reached ${now.seq}, and you asked to read on from ${since}` +
				" — this store is not the one that cursor came from, so read again from the beginning",
		);
	}
	if (since > 0 && since <= now.placed_from) {
		return problem(
			409,
			`the whole of this store was placed again above ${now.placed_from}, and you asked to read on from ${since}` +
				" — everything you have from before that has been made again, so throw it away and read from the beginning",
		);
	}

	// One more than a page is asked for, so whether there is a next page is answered by the same
	// read rather than by a second one counting what is left. The envelope columns are left out
	// of the keys-only read as well as out of its answer: reading 27 MB out of the database to
	// throw it away here would buy nothing.
	const most = keysOnly ? PER_KEY_PAGE : PER_PAGE;
	const { results } = await env.RECORDS.prepare(
		keysOnly
			? "SELECT seq, k, op FROM records WHERE seq > ? ORDER BY seq LIMIT ?"
			: "SELECT seq, k, op, nonce, ciphertext FROM records WHERE seq > ? ORDER BY seq LIMIT ?",
	)
		.bind(since, most + 1)
		.all<Stored>();

	const more = results.length > most;
	const page = more ? results.slice(0, most) : results;
	return Response.json({
		spec_v: SPEC_V,
		version: now.version,
		seq: page.length ? page[page.length - 1].seq : since,
		more,
		records: page.map(keysOnly ? keyOnly : travelling),
	});
}

/** One record with its envelope left off: what it is filed under, and its last word. */
function keyOnly(row: Stored): Record<string, string> {
	return { k: row.k, op: row.op };
}

/**
 * One record on its way back to a phone, in the shape it was sent in: the key, what happened to
 * it, and the envelope for everything but a deletion. The order it belongs to is the page's, not
 * the record's, so it does not travel per row.
 */
function travelling(row: Stored): Record<string, string> {
	if (row.op === "del") {
		return { k: row.k, op: row.op };
	}
	return { k: row.k, op: row.op, n: row.nonce ?? "", c: row.ciphertext ?? "" };
}

/** One record as it arrives, before anything has been checked about it. */
interface Offered {
	k?: unknown;
	op?: unknown;
	n?: unknown;
	c?: unknown;
}

/**
 * `PUT /records` — the one way records land here.
 *
 * Each one takes its place beside what is already filed, or takes the place of the row under the
 * same key. **Nothing is emptied first**, so a whole store and a single edit are the same road:
 * the difference is how many records travel, not what happens to the ones already here.
 *
 * **It writes what it is handed, always.** It used to drop a turn whose version the store already
 * stood at, on the reasoning that the same number means the same records — and answer `200` to it,
 * because a repeat it recognised was a repeat it had already written. Both halves were wrong. The
 * backlog's version is too coarse a name for a turn: a send made while the backlog has not moved
 * carries the number the store is standing at without being a repeat of anything, and every one of
 * those was thrown away and reported as landed. **Three months of edits went missing behind that
 * `200`, and the one command for sending them again was killed by the same line.** Recognising a
 * repeat is the sender's job now — it is the end that knows what it sent.
 *
 * ## More than one request's worth
 *
 * One write takes `PER_WRITE` records, and a backlog outgrows that the first time it is sent
 * whole. So a body says which part of a turn it is: `{"part":2,"parts":5}`, both defaulting to 1,
 * and the same version travels on every part.
 *
 * **Only the last part settles the turn**: the version, the time and the key the records were
 * sealed with are written by that part alone, so a turn cut short leaves a store still naming
 * what it really holds, and the next turn is not mistaken for a repeat of it. What has landed of
 * an unfinished turn is a true prefix of what is coming, so a phone reading it is behind rather
 * than wrong — which is why nothing has to close while one is in flight.
 *
 * ## What the answer carries
 *
 * `seq` is where the order now stands, and the sender checks it: a store that wrote what it was
 * handed stands exactly the record count further on. `rows_written` is what the database actually
 * did, which is what lets a sender keep a budget against a daily limit in measured rows rather
 * than in guesses. `build` says which Worker this is, and it is on this answer rather than on a
 * read because the sender holds the write token and nothing else.
 */
async function place(env: Env, request: Request): Promise<Response> {
	let asked: unknown;
	try {
		asked = await request.json();
	} catch {
		return problem(400, "the body has to be a JSON object");
	}
	const { spec_v, version, part, parts, records, key_fingerprint } = (asked ?? {}) as {
		spec_v?: unknown;
		version?: unknown;
		part?: unknown;
		parts?: unknown;
		records?: unknown;
		key_fingerprint?: unknown;
	};

	if (spec_v !== SPEC_V) {
		return problem(400, `this Worker reads spec_v ${SPEC_V}, and was sent ${JSON.stringify(spec_v) ?? "nothing"}`);
	}
	if (typeof version !== "number" || !Number.isSafeInteger(version)) {
		return problem(400, "version has to be a whole number — the backlog's own version, so a repeat can be recognised");
	}
	// A body that says nothing about parts is one whole turn, which is what every send was before
	// there were parts at all.
	const of = parts === undefined ? 1 : parts;
	const at = part === undefined ? 1 : part;
	if (typeof of !== "number" || !Number.isSafeInteger(of) || of < 1) {
		return problem(400, "parts has to be a whole number of 1 or more — how many requests this turn is being sent in");
	}
	if (typeof at !== "number" || !Number.isSafeInteger(at) || at < 1 || at > of) {
		return problem(400, `part has to be a whole number from 1 to ${of} — which of this turn's requests this is`);
	}
	if (!Array.isArray(records)) {
		return problem(400, "records has to be a list, empty or otherwise");
	}
	if (records.length > PER_WRITE) {
		return problem(
			413,
			`one write takes ${PER_WRITE} records at most, and this one carried ${records.length} — send it in parts`,
		);
	}
	// **A body that names no key is a sender that does not say, and it is taken as such.** Every
	// send before this field existed is one of those, so refusing them would turn an upgrade of
	// this Worker into a store nobody could write to. What it must not do is stand for the last
	// sender's answer: the fingerprint says what is in the records *now*, so a turn that names
	// none leaves the store naming none.
	const offered = key_fingerprint ?? null;
	if (offered !== null && (typeof offered !== "string" || !HASH.test(offered))) {
		return problem(
			400,
			"key_fingerprint has to be a SHA-256 as 64 hex characters" +
				" — the hash of the key these records were sealed with, and never the key",
		);
	}
	const sealedWith = offered === null ? null : offered.toLowerCase();
	const carrying: Landing[] = [];
	for (const record of records as Offered[]) {
		const checked = checkedRecord(record ?? {});
		if (typeof checked === "string") {
			return problem(400, checked);
		}
		carrying.push(checked);
	}

	const last = at === of;

	// Every statement in one batch, so a write either lands whole or not at all: half a turn in
	// the table would be a phone reading records the version says nothing about.
	//
	// The numbers are not worked out here but in the statements themselves, counting up from
	// where the store row says the order stands. Two sends arriving together therefore cannot be
	// handed the same number — the second one reads the row the first one already moved.
	const upsert = env.RECORDS.prepare(
		"INSERT INTO records (k, seq, op, nonce, ciphertext)" +
			" VALUES (?, (SELECT seq FROM store WHERE id = 1) + ?, ?, ?, ?)" +
			" ON CONFLICT (k) DO UPDATE SET" +
			" seq = excluded.seq, op = excluded.op, nonce = excluded.nonce, ciphertext = excluded.ciphertext",
	);
	const statements = [
		...carrying.map((record, offset) => upsert.bind(record.k, offset + 1, record.op, record.nonce, record.ciphertext)),
		env.RECORDS.prepare("UPDATE store SET seq = seq + ? WHERE id = 1").bind(carrying.length),
		...(last
			? [
					env.RECORDS.prepare(
						"UPDATE store SET version = ?, updated_at = ?, key_fingerprint = ? WHERE id = 1",
					).bind(version, new Date().toISOString(), sealedWith),
				]
			: []),
		env.RECORDS.prepare("SELECT seq FROM store WHERE id = 1"),
	];
	const done = await env.RECORDS.batch<{ seq: number }>(statements);

	return Response.json({
		seq: done[done.length - 1].results[0].seq,
		rows_written: rowsWritten(done),
		build: BUILD,
	});
}

/**
 * What the database actually wrote for one turn, added up over the batch.
 *
 * **It is measured and not worked out.** A sender keeping a budget against a daily limit has to
 * count rows, and counting them from this end means knowing that an upsert onto a key already
 * here costs a different number from one onto a key that is not — which is a model of D1 living
 * in the sender, going stale the day the database changes. The number is here for the asking, so
 * it is handed over.
 *
 * A statement whose result says nothing about rows contributes nothing, which is what the reads
 * in the batch are.
 */
function rowsWritten(done: D1Result<unknown>[]): number {
	return done.reduce((all, one) => all + (one.meta?.rows_written ?? 0), 0);
}

/**
 * Checks one arriving record, and hands back either the row to write or the sentence saying what
 * is wrong with it.
 *
 * **What is checked is the shape and nothing else.** The key is a string this Worker files under
 * and the envelope is bytes it cannot open, so reading either of them for sense would be reading
 * what it was built not to.
 */
function checkedRecord(record: Offered): Landing | string {
	const { k, op, n, c } = record;
	if (typeof k !== "string" || k === "") {
		return "every record needs a key — the string it is filed under";
	}
	if (op !== "put" && op !== "del") {
		return `a record is either a put or a del, and ${JSON.stringify(k)} said ${JSON.stringify(op) ?? "nothing"}`;
	}
	if (op === "del") {
		// A deletion is a row with an empty envelope: that emptiness is the only thing telling
		// the two apart in the table, so whatever it arrived with is dropped rather than kept.
		return { k, op, nonce: null, ciphertext: null };
	}
	if (typeof n !== "string" || n === "" || typeof c !== "string" || c === "") {
		return `a put carries a nonce and a ciphertext, and ${JSON.stringify(k)} carried neither or half`;
	}
	return { k, op, nonce: n, ciphertext: c };
}

/** A hash as it may be written down: SHA-256 is 32 bytes, so 64 hex characters and nothing else. */
const HASH = /^[0-9a-f]{64}$/i;

/**
 * `PUT /tokens` — hands out the read code.
 *
 * **The code itself never arrives.** The PC generates it, shows it on a QR, and sends only its
 * hash, so the value exists on the PC and on the phone that photographed it and nowhere else.
 *
 * **Issuing replaces what was there.** There is one row, so the code that was here stops working
 * the moment a new one lands — which is what "issuing cuts the last one" means from a phone's
 * side. It is not a refusal to be worked around: the old shape refused a name that was taken and
 * made re-pairing two moves, and the name was the part that turned out not to exist.
 */
async function issue(env: Env, request: Request): Promise<Response> {
	let asked: unknown;
	try {
		asked = await request.json();
	} catch {
		return problem(400, "the body has to be a JSON object");
	}
	const { hash } = (asked ?? {}) as { hash?: unknown };
	if (typeof hash !== "string" || !HASH.test(hash)) {
		return problem(400, "the hash has to be a SHA-256 as 64 hex characters");
	}

	const issued_at = new Date().toISOString();
	await env.RECORDS.prepare(
		"INSERT INTO tokens (id, hash, issued_at) VALUES (1, ?, ?)" +
			" ON CONFLICT (id) DO UPDATE SET hash = excluded.hash, issued_at = excluded.issued_at",
	)
		.bind(hash.toLowerCase(), issued_at)
		.run();

	return Response.json({ issued_at });
}

/**
 * `DELETE /tokens` — takes the code away, so nothing reads until one is issued again.
 *
 * **A store that had none is not a mistake to report.** The old shape answered `404` to a label it
 * did not hold, because the label was typed and a typo answered "done" would leave someone
 * believing they had cut off a phone that is still reading. There is nothing to mistype now, and
 * asking a store with no code to have no code is asking for the state it is in. So the answer says
 * whether there was one to cut, and the status is the same either way.
 */
async function revoke(env: Env): Promise<Response> {
	const done = await env.RECORDS.prepare("DELETE FROM tokens WHERE id = 1").run();
	return Response.json({ cut: Boolean(done.meta.changes) });
}

/**
 * `GET /tokens` — whether there is a code, and when it was issued.
 *
 * **It takes the write token, not a read one.** The question belongs to the PC: the settings
 * screen draws whether a phone can read at all, and it drew that from a list the PC kept beside
 * its own state — a list of what the PC believed, which parts company with the store the first
 * time one is stood up again underneath it. Asking here makes the screen say what is true.
 *
 * **The hash does not travel.** What is kept is a hash and not a code, but handing it out would
 * put the read credential's only copy in reach of a token that has no use for it.
 */
async function pairing(env: Env): Promise<Response> {
	const row = await env.RECORDS.prepare("SELECT issued_at FROM tokens WHERE id = 1").first<{ issued_at: string }>();
	return Response.json({ paired: row !== null, issued_at: row?.issued_at ?? null });
}

/**
 * One shape for every refusal, so a caller can read the reason without guessing at the body.
 * The status is the verdict; the sentence is for whoever has to fix it.
 */
function problem(status: number, detail: string, headers: Record<string, string> = {}): Response {
	return Response.json({ error: detail }, { status, headers });
}
