package main

// Every language this build can speak the settings face in, keyed by Amenbo's language code and
// ordered by it. All nineteen Amenbo offers are here, and the code has to be
// spelled the way the store spells it — `pt-BR` and not `pt-br` — or the row is one nothing ever
// reads.
//
// **English is the row that must be complete**, and it is the one the code was written against:
// every other row is read against it phrase by phrase, so a sentence nobody has translated yet
// arrives in English rather than blank.
//
// What is *not* translated travels through these sentences untouched: an account id, a database
// name, an endpoint, the name a person gave their phone, and the addresses — the App Store page,
// Cloudflare's dashboard. So do the commands, `viewer setup` and `viewer revoke <name>`, which
// are typed exactly as they are printed.
var wordings = map[string]wording{
	"de": {
		phICloudFolder:            "der iCloud-Ordner",
		phCloudflareWorker:        "dein Cloudflare Worker",
		phOpenTheAppOnce:          "Amenbo Viewer (%s) auf dem Telefon öffnen",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "er steht, aber es ist kein Schlüssel hinterlegt — setup ausführen",
		phStandingBadKey:          "er steht, aber der Schlüssel in den Einstellungen ist unbrauchbar — setup erneut ausführen",
		phCarryingTo:              "Es wird zu %s getragen.",
		phCarryingNowhere:         "Trägt nirgendwohin.",
		phNothingIsTicked:         "Es wird nirgendwohin getragen: unter „Wohin getragen wird“ ist kein Ort angehakt.",
		phWaitingOn:               " Fehlt: %s.",
		phNoSuchPlaceHere:         " Dieser Rechner hat keinen solchen Ort wie %s — der gehört einem Mac.",
		phNowhere:                 "nirgendwohin",
		phAnd:                     " und ",
		phComma:                   ", ",
		phNothingToDrawOn:         "hier gibt es nichts, worauf ein Code gezeichnet werden könnte. Amenbo Viewer liegt unter %s",
		phCodeNotDrawn:            "der Code konnte nicht gezeichnet werden (%w) — Amenbo Viewer liegt unter %s",
		phPointTheCamera:          "richte die Kamera des Telefons auf den Code. Amenbo Viewer liegt auch unter %s",
		phImageNotOpened:          "das Bild ließ sich nicht öffnen (%v) — es wird stattdessen hier gezeichnet",
		phCodeLeftWithKey:         "der Code liegt unter %s und trägt den Schlüssel — lösche ihn, sobald das Telefon ihn gelesen hat (%v).",
		phCodeLeftBehind:          "der Code liegt unter %s, und es wurde nichts gestartet, um ihn wieder wegzuräumen (%v).",
		phCodeIsOnScreen:          "der Code ist auf dem Bildschirm, und das Bild verschwindet in %d Minuten — lies es bis dahin mit dem Telefon.",
		phNoScreenForTheTokenPage: "hier gibt es keinen Bildschirm, um sie zu öffnen. Die Token-Seite liegt unter %s",
		phTokenPageNotOpened:      "die Token-Seite ließ sich nicht öffnen (%w) — sie liegt unter %s",
		phTokenPageIsOpen:         "die Token-Seite ist offen, die nötigen Berechtigungen sind bereits angehakt. Drücke Continue to summary, dann Create Token, und füge das Angezeigte in das Feld hinter der setup-Schaltfläche ein.",
		phBuildingInAccount:       "wird im Konto %s aufgebaut",
		phDatabaseCreated:         "Datenbank %s angelegt",
		phDatabaseAlreadyThere:    "Datenbank %s war schon da",
		phWorkerDeployed:          "Worker %s ausgeliefert",
		phNoWorkersDevName:        "der Worker ist ausgeliefert, aber dieses Konto hat noch keinen workers.dev-Namen, unter dem er antworten kann. Wähle einen unter %s und führe setup erneut aus",
		phTheRouteIsUp:            "die Cloudflare-Route steht unter %s",
		phTheKeyWasKept:           "der Schlüssel, der schon in den Einstellungen stand, wurde behalten — die damit gekoppelten Telefone lesen weiter.",
		phANewKeyWasGenerated:     "ein neuer Schlüssel wurde erzeugt — koppele ein Telefon mit `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "der Worker und die Datenbank gehören dir. Wird dieses Plugin deinstalliert, bleiben sie, wo sie sind;\n  lösche sie im Cloudflare-Dashboard, wenn du sie loswerden willst.",
		phNoTokenWasPasted:        "es wurde kein Token eingefügt",
		phTokenReachesNoAccount:   "dieses Token erreicht kein Cloudflare-Konto — möglicherweise fehlt ihm die Berechtigung Account Settings (read)",
		phWorkerHasNoWriteToken:   "der Worker antwortet, hat aber kein Schreib-Token gesetzt — die Auslieferung ist nicht vollständig angekommen. Führe setup erneut aus",
		phEndpointNotAnsweringYet: "alles wurde angelegt, aber der Endpunkt antwortet noch nicht so, wie er sollte: %w",
		phPhoneMayReadFromNowOn:   "%q darf von jetzt an lesen. Unter diesem Namen wird es später abgeschnitten.",
		phPhoneAlreadyPaired:      "ein Telefon ist bereits als %q gekoppelt — schneide es mit `%s revoke %s` ab und koppele es erneut",
		phNoEncryptionKey:         "es ist kein Schlüssel hinterlegt — setup ausführen",
		phNoCloudflareRouteYet:    "es gibt noch keine Cloudflare-Route — stelle eine mit `%s setup` auf",
		phThePhoneWasNotNamed:     "das Telefon wurde nicht benannt, und der Name ist es, womit man es später abschneidet",
	},
	"en": {
		phICloudFolder:      "the iCloud folder",
		phCloudflareWorker:  "your Cloudflare Worker",
		phOpenTheAppOnce:    "open Amenbo Viewer (%s) on a phone once",
		phStandTheWorkerUp:  "run `%s setup`",
		phStandingWithNoKey: "it is standing, but no encryption key is configured — run setup",
		phStandingBadKey:    "it is standing, but the key in the settings cannot be used — run setup again",
		phCarryingTo:        "Carrying to %s.",
		phCarryingNowhere:   "Carrying nowhere.",
		phNothingIsTicked:   `Carrying nowhere: no place is ticked under "Where to carry".`,
		phWaitingOn:         " Waiting on %s.",
		phNoSuchPlaceHere:   " This machine has no such place as %s — that one is a mac's own.",
		phNowhere:           "nowhere",
		phAnd:               " and ",
		phComma:             ", ",

		phNothingToDrawOn: "there is nothing here to draw a code on. Amenbo Viewer is at %s",
		phCodeNotDrawn:    "the code could not be drawn (%w) — Amenbo Viewer is at %s",
		phPointTheCamera:  "point the phone's camera at the code. Amenbo Viewer is also at %s",

		phImageNotOpened:  "the image could not be opened (%v) — drawing it here instead",
		phCodeLeftWithKey: "the code is at %s, and it carries the key — delete it once the phone has read it (%v).",
		phCodeLeftBehind:  "the code is at %s, and nothing was started to take it away again (%v).",
		phCodeIsOnScreen:  "the code is on screen, and the image goes in %d minutes — read it with the phone before then.",

		phNoScreenForTheTokenPage: "there is no screen here to open it on. The token page is at %s",
		phTokenPageNotOpened:      "the token page could not be opened (%w) — it is at %s",
		phTokenPageIsOpen:         "the token page is open, with the permissions it needs already ticked. Press Continue to summary, then Create Token, and paste what it shows you into the box behind the setup button.",

		phBuildingInAccount:    "building in account %s",
		phDatabaseCreated:      "database %s created",
		phDatabaseAlreadyThere: "database %s was already there",
		phWorkerDeployed:       "Worker %s deployed",
		phNoWorkersDevName: "the Worker is deployed, but this account has no workers.dev name for it to answer on yet." +
			" Choose one at %s and run setup again",
		phTheRouteIsUp:        "the Cloudflare route is up at %s",
		phTheKeyWasKept:       "the encryption key already in the settings was kept, so the phones paired with it still read.",
		phANewKeyWasGenerated: "a new encryption key was generated — pair a phone with `amenbo plugin run %s qr`.",
		phTheWorkerIsYours: "the Worker and the database are yours. Uninstalling this plugin leaves them where they are;\n" +
			"  delete them in the Cloudflare dashboard when you want them gone.",
		phNoTokenWasPasted:        "no token was pasted",
		phTokenReachesNoAccount:   "this token reaches no Cloudflare account — it may be missing the Account Settings (read) permission",
		phWorkerHasNoWriteToken:   "the Worker is answering but has no write token set, which is a deploy that did not fully land — run setup again",
		phEndpointNotAnsweringYet: "everything was created, but the endpoint is not answering the way it should yet: %w",

		phPhoneMayReadFromNowOn: "%q may read from now on. Cut it off later by that name.",
		phPhoneAlreadyPaired:    "a phone is already paired as %q — cut it off with `%s revoke %s`, then pair it again",
		phNoEncryptionKey:       "no encryption key is configured — run setup",
		phNoCloudflareRouteYet:  "there is no Cloudflare route yet — run `%s setup` to stand one up",
		phThePhoneWasNotNamed:   "the phone was not named, and a name is what revoking one gives",
	},
	"es": {
		phICloudFolder:            "la carpeta de iCloud",
		phCloudflareWorker:        "tu propio Cloudflare Worker",
		phOpenTheAppOnce:          "abre Amenbo Viewer (%s) en el teléfono",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "está en pie, pero no hay clave de cifrado configurada — ejecuta setup",
		phStandingBadKey:          "está en pie, pero la clave de los ajustes no sirve — vuelve a ejecutar setup",
		phCarryingTo:              "Llegando a %s.",
		phCarryingNowhere:         "No llega a ninguna parte.",
		phNothingIsTicked:         "No llega a ninguna parte: no hay ningún sitio marcado en «A dónde llevarlo».",
		phWaitingOn:               " Falta: %s.",
		phNoSuchPlaceHere:         " Esta máquina no tiene un sitio como %s — eso es cosa de un Mac.",
		phNowhere:                 "ninguna parte",
		phAnd:                     " y ",
		phComma:                   ", ",
		phNothingToDrawOn:         "aquí no hay dónde dibujar un código. Amenbo Viewer está en %s",
		phCodeNotDrawn:            "no se pudo dibujar el código (%w) — Amenbo Viewer está en %s",
		phPointTheCamera:          "apunta la cámara del teléfono al código. Amenbo Viewer también está en %s",
		phImageNotOpened:          "no se pudo abrir la imagen (%v) — se dibuja aquí en su lugar",
		phCodeLeftWithKey:         "el código está en %s y lleva la clave — bórralo en cuanto el teléfono lo haya leído (%v).",
		phCodeLeftBehind:          "el código está en %s y no se puso nada en marcha para retirarlo (%v).",
		phCodeIsOnScreen:          "el código está en pantalla y la imagen desaparece en %d minutos — léela con el teléfono antes.",
		phNoScreenForTheTokenPage: "aquí no hay pantalla donde abrirla. La página del token está en %s",
		phTokenPageNotOpened:      "no se pudo abrir la página del token (%w) — está en %s",
		phTokenPageIsOpen:         "la página del token está abierta, con los permisos que hacen falta ya marcados. Pulsa Continue to summary, luego Create Token, y pega lo que te muestre en la casilla que hay tras el botón de setup.",
		phBuildingInAccount:       "construyendo en la cuenta %s",
		phDatabaseCreated:         "base de datos %s creada",
		phDatabaseAlreadyThere:    "la base de datos %s ya estaba",
		phWorkerDeployed:          "Worker %s desplegado",
		phNoWorkersDevName:        "el Worker está desplegado, pero esta cuenta aún no tiene un nombre workers.dev donde responder. Elige uno en %s y vuelve a ejecutar setup",
		phTheRouteIsUp:            "la ruta de Cloudflare está en pie en %s",
		phTheKeyWasKept:           "se conservó la clave de cifrado que ya estaba en los ajustes, así que los teléfonos emparejados con ella siguen leyendo.",
		phANewKeyWasGenerated:     "se generó una clave de cifrado nueva — empareja un teléfono con `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "el Worker y la base de datos son tuyos. Desinstalar este plugin los deja donde están;\n  bórralos en el panel de Cloudflare cuando quieras deshacerte de ellos.",
		phNoTokenWasPasted:        "no se pegó ningún token",
		phTokenReachesNoAccount:   "este token no llega a ninguna cuenta de Cloudflare — puede que le falte el permiso Account Settings (read)",
		phWorkerHasNoWriteToken:   "el Worker responde pero no tiene token de escritura, lo que es un despliegue que no llegó del todo — vuelve a ejecutar setup",
		phEndpointNotAnsweringYet: "se creó todo, pero el endpoint todavía no responde como debería: %w",
		phPhoneMayReadFromNowOn:   "%q puede leer desde ahora. Para cortarlo más adelante se usa ese nombre.",
		phPhoneAlreadyPaired:      "ya hay un teléfono emparejado como %q — córtalo con `%s revoke %s` y vuelve a emparejarlo",
		phNoEncryptionKey:         "no hay clave de cifrado configurada — ejecuta setup",
		phNoCloudflareRouteYet:    "todavía no hay ruta de Cloudflare — levanta una con `%s setup`",
		phThePhoneWasNotNamed:     "el teléfono no recibió nombre, y el nombre es lo que se usa para cortarlo",
	},
	"fr": {
		phICloudFolder:            "le dossier iCloud",
		phCloudflareWorker:        "votre Cloudflare Worker",
		phOpenTheAppOnce:          "ouvrez Amenbo Viewer (%s) sur le téléphone",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "il est en place, mais aucune clé de chiffrement n'est réglée — lancez setup",
		phStandingBadKey:          "il est en place, mais la clé des réglages est inutilisable — relancez setup",
		phCarryingTo:              "Achemine vers %s.",
		phCarryingNowhere:         "N'achemine nulle part.",
		phNothingIsTicked:         "N'achemine nulle part : aucun endroit n'est coché sous « Où acheminer ».",
		phWaitingOn:               " Manque : %s.",
		phNoSuchPlaceHere:         " Cette machine n'a pas d'endroit comme %s — c'est celui d'un Mac.",
		phNowhere:                 "nulle part",
		phAnd:                     " et ",
		phComma:                   ", ",
		phNothingToDrawOn:         "il n'y a rien ici pour dessiner un code. Amenbo Viewer est à %s",
		phCodeNotDrawn:            "le code n'a pas pu être dessiné (%w) — Amenbo Viewer est à %s",
		phPointTheCamera:          "pointez la caméra du téléphone sur le code. Amenbo Viewer est aussi à %s",
		phImageNotOpened:          "l'image n'a pas pu être ouverte (%v) — elle est dessinée ici à la place",
		phCodeLeftWithKey:         "le code est à %s et il porte la clé — supprimez-le dès que le téléphone l'a lu (%v).",
		phCodeLeftBehind:          "le code est à %s, et rien n'a été lancé pour le retirer (%v).",
		phCodeIsOnScreen:          "le code est à l'écran, et l'image disparaît dans %d minutes — lisez-la avec le téléphone avant.",
		phNoScreenForTheTokenPage: "il n'y a pas d'écran ici pour l'ouvrir. La page du jeton est à %s",
		phTokenPageNotOpened:      "la page du jeton n'a pas pu être ouverte (%w) — elle est à %s",
		phTokenPageIsOpen:         "la page du jeton est ouverte, avec les permissions nécessaires déjà cochées. Appuyez sur Continue to summary, puis Create Token, et collez ce qu'elle affiche dans le champ derrière le bouton setup.",
		phBuildingInAccount:       "construction dans le compte %s",
		phDatabaseCreated:         "base de données %s créée",
		phDatabaseAlreadyThere:    "la base de données %s était déjà là",
		phWorkerDeployed:          "Worker %s déployé",
		phNoWorkersDevName:        "le Worker est déployé, mais ce compte n'a pas encore de nom workers.dev pour répondre. Choisissez-en un sur %s et relancez setup",
		phTheRouteIsUp:            "la route Cloudflare est en place à %s",
		phTheKeyWasKept:           "la clé de chiffrement déjà présente dans les réglages a été conservée : les téléphones appairés avec elle lisent toujours.",
		phANewKeyWasGenerated:     "une nouvelle clé de chiffrement a été générée — appairez un téléphone avec `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "le Worker et la base de données sont à vous. Désinstaller ce plugin les laisse où ils sont ;\n  supprimez-les dans le tableau de bord Cloudflare quand vous voudrez.",
		phNoTokenWasPasted:        "aucun jeton n'a été collé",
		phTokenReachesNoAccount:   "ce jeton n'atteint aucun compte Cloudflare — il lui manque peut-être la permission Account Settings (read)",
		phWorkerHasNoWriteToken:   "le Worker répond mais n'a pas de jeton d'écriture : le déploiement n'est pas allé au bout — relancez setup",
		phEndpointNotAnsweringYet: "tout a été créé, mais l'endpoint ne répond pas encore comme il devrait : %w",
		phPhoneMayReadFromNowOn:   "%q peut lire à partir de maintenant. C'est sous ce nom qu'on le coupera plus tard.",
		phPhoneAlreadyPaired:      "un téléphone est déjà appairé sous le nom %q — coupez-le avec `%s revoke %s`, puis appairez-le à nouveau",
		phNoEncryptionKey:         "aucune clé de chiffrement n'est réglée — lancez setup",
		phNoCloudflareRouteYet:    "il n'y a pas encore de route Cloudflare — montez-en une avec `%s setup`",
		phThePhoneWasNotNamed:     "le téléphone n'a pas été nommé, et c'est le nom qui sert à le couper",
	},
	"hi": {
		phICloudFolder:            "iCloud फ़ोल्डर",
		phCloudflareWorker:        "Cloudflare Worker",
		phOpenTheAppOnce:          "फ़ोन पर Amenbo Viewer (%s)",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "वह खड़ा है, पर कोई एन्क्रिप्शन कुंजी सेट नहीं है — setup चलाएँ",
		phStandingBadKey:          "वह खड़ा है, पर सेटिंग्स की कुंजी काम की नहीं — setup दोबारा चलाएँ",
		phCarryingTo:              "पहुँच रहा है: %s।",
		phCarryingNowhere:         "कहीं नहीं।",
		phNothingIsTicked:         "कहीं नहीं पहुँच रहा: «कहाँ पहुँचाना है» में कोई जगह चुनी नहीं गई है।",
		phWaitingOn:               " बाकी: %s",
		phNoSuchPlaceHere:         " %s — यह Mac की जगह है, इस मशीन पर नहीं।",
		phNowhere:                 "कहीं नहीं",
		phAnd:                     " और ",
		phComma:                   ", ",
		phNothingToDrawOn:         "यहाँ कोड बनाने की कोई जगह नहीं है। Amenbo Viewer %s पर है",
		phCodeNotDrawn:            "कोड नहीं बनाया जा सका (%w) — Amenbo Viewer %s पर है",
		phPointTheCamera:          "फ़ोन का कैमरा कोड पर रखें। Amenbo Viewer %s पर भी है",
		phImageNotOpened:          "छवि नहीं खोली जा सकी (%v) — उसके बदले उसे यहीं बनाया जा रहा है",
		phCodeLeftWithKey:         "कोड %s पर है और उस पर कुंजी है — फ़ोन के पढ़ लेने पर उसे मिटा दें (%v)।",
		phCodeLeftBehind:          "कोड %s पर है, और उसे हटाने के लिए कुछ शुरू नहीं किया गया (%v)।",
		phCodeIsOnScreen:          "कोड स्क्रीन पर है, और छवि %d मिनट में चली जाएगी — उससे पहले फ़ोन से पढ़ लें।",
		phNoScreenForTheTokenPage: "इसे खोलने के लिए यहाँ कोई स्क्रीन नहीं है। टोकन पृष्ठ %s पर है",
		phTokenPageNotOpened:      "टोकन पृष्ठ नहीं खोला जा सका (%w) — वह %s पर है",
		phTokenPageIsOpen:         "टोकन पृष्ठ खुला है, ज़रूरी अनुमतियाँ पहले से चुनी हुई हैं। Continue to summary दबाएँ, फिर Create Token, और जो दिखे उसे setup बटन के पीछे वाले खाने में चिपकाएँ।",
		phBuildingInAccount:       "खाता %s में बनाया जा रहा है",
		phDatabaseCreated:         "डेटाबेस %s बनाया गया",
		phDatabaseAlreadyThere:    "डेटाबेस %s पहले से मौजूद था",
		phWorkerDeployed:          "Worker %s तैनात किया गया",
		phNoWorkersDevName:        "Worker तैनात हो गया, पर इस खाते के पास अभी कोई workers.dev नाम नहीं है जिस पर वह जवाब दे। %s पर एक चुनें और setup दोबारा चलाएँ",
		phTheRouteIsUp:            "Cloudflare रास्ता %s पर खड़ा है",
		phTheKeyWasKept:           "सेटिंग्स में पहले से मौजूद एन्क्रिप्शन कुंजी रखी गई, इसलिए उससे जुड़े फ़ोन पढ़ते रहेंगे।",
		phANewKeyWasGenerated:     "नई एन्क्रिप्शन कुंजी बनाई गई — `amenbo plugin run %s qr` से एक फ़ोन जोड़ें।",
		phTheWorkerIsYours:        "Worker और डेटाबेस आपके हैं। यह प्लगइन हटाने पर भी वे जहाँ हैं वहीं रहेंगे;\n  जब हटाना हो तो Cloudflare डैशबोर्ड से मिटाएँ।",
		phNoTokenWasPasted:        "कोई टोकन चिपकाया नहीं गया",
		phTokenReachesNoAccount:   "यह टोकन किसी Cloudflare खाते तक नहीं पहुँचता — शायद इसमें Account Settings (read) की अनुमति नहीं है",
		phWorkerHasNoWriteToken:   "Worker जवाब दे रहा है पर उसमें लिखने का टोकन सेट नहीं है, यानी तैनाती पूरी नहीं उतरी — setup दोबारा चलाएँ",
		phEndpointNotAnsweringYet: "सब कुछ बन गया, पर एंडपॉइंट अभी वैसा जवाब नहीं दे रहा जैसा देना चाहिए: %w",
		phPhoneMayReadFromNowOn:   "%q अब से पढ़ सकता है। बाद में इसी नाम से उसे काटा जाएगा।",
		phPhoneAlreadyPaired:      "%q नाम से एक फ़ोन पहले से जुड़ा है — `%s revoke %s` से उसे काटें, फिर दोबारा जोड़ें",
		phNoEncryptionKey:         "कोई एन्क्रिप्शन कुंजी सेट नहीं है — setup चलाएँ",
		phNoCloudflareRouteYet:    "अभी कोई Cloudflare रास्ता नहीं है — `%s setup` से एक खड़ा करें",
		phThePhoneWasNotNamed:     "फ़ोन को नाम नहीं दिया गया, और काटते समय उसी नाम से उसे बताया जाता है",
	},
	"id": {
		phICloudFolder:            "folder iCloud",
		phCloudflareWorker:        "Cloudflare Worker Anda",
		phOpenTheAppOnce:          "buka Amenbo Viewer (%s) di ponsel",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "sudah berdiri, tetapi belum ada kunci enkripsi — jalankan setup",
		phStandingBadKey:          "sudah berdiri, tetapi kunci di pengaturan tidak bisa dipakai — jalankan setup lagi",
		phCarryingTo:              "Mengantar ke %s.",
		phCarryingNowhere:         "Belum ke mana pun.",
		phNothingIsTicked:         "Tidak mengantar ke mana pun: tidak ada tempat yang dicentang di «Ke mana mengantar».",
		phWaitingOn:               " Menunggu: %s.",
		phNoSuchPlaceHere:         " Mesin ini tidak punya tempat seperti %s — itu milik Mac.",
		phNowhere:                 "ke mana pun",
		phAnd:                     " dan ",
		phComma:                   ", ",
		phNothingToDrawOn:         "tidak ada tempat di sini untuk menggambar kode. Amenbo Viewer ada di %s",
		phCodeNotDrawn:            "kode tidak bisa digambar (%w) — Amenbo Viewer ada di %s",
		phPointTheCamera:          "arahkan kamera ponsel ke kode. Amenbo Viewer juga ada di %s",
		phImageNotOpened:          "gambar tidak bisa dibuka (%v) — digambar di sini saja",
		phCodeLeftWithKey:         "kode ada di %s dan membawa kuncinya — hapus begitu ponsel selesai membacanya (%v).",
		phCodeLeftBehind:          "kode ada di %s, dan tidak ada yang dijalankan untuk menyingkirkannya lagi (%v).",
		phCodeIsOnScreen:          "kode sudah di layar, dan gambarnya hilang dalam %d menit — baca dengan ponsel sebelum itu.",
		phNoScreenForTheTokenPage: "tidak ada layar di sini untuk membukanya. Halaman token ada di %s",
		phTokenPageNotOpened:      "halaman token tidak bisa dibuka (%w) — halamannya di %s",
		phTokenPageIsOpen:         "halaman token sudah terbuka, dengan izin yang diperlukan sudah tercentang. Tekan Continue to summary, lalu Create Token, dan tempel yang ditampilkan ke kotak di balik tombol setup.",
		phBuildingInAccount:       "membangun di akun %s",
		phDatabaseCreated:         "basis data %s dibuat",
		phDatabaseAlreadyThere:    "basis data %s sudah ada",
		phWorkerDeployed:          "Worker %s ditempatkan",
		phNoWorkersDevName:        "Worker sudah ditempatkan, tetapi akun ini belum punya nama workers.dev untuk menjawab. Pilih satu di %s lalu jalankan setup lagi",
		phTheRouteIsUp:            "rute Cloudflare berdiri di %s",
		phTheKeyWasKept:           "kunci enkripsi yang sudah ada di pengaturan dipertahankan, jadi ponsel yang dipasangkan dengannya tetap bisa membaca.",
		phANewKeyWasGenerated:     "kunci enkripsi baru dibuat — pasangkan sebuah ponsel dengan `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "Worker dan basis data itu milik Anda. Mencopot plugin ini tidak menghapusnya;\n  hapus lewat dasbor Cloudflare kalau sudah tidak diperlukan.",
		phNoTokenWasPasted:        "tidak ada token yang ditempel",
		phTokenReachesNoAccount:   "token ini tidak mencapai akun Cloudflare mana pun — mungkin izin Account Settings (read) belum ada",
		phWorkerHasNoWriteToken:   "Worker menjawab tetapi tidak punya token tulis, artinya penempatan belum mendarat sepenuhnya — jalankan setup lagi",
		phEndpointNotAnsweringYet: "semuanya sudah dibuat, tetapi endpoint belum menjawab sebagaimana mestinya: %w",
		phPhoneMayReadFromNowOn:   "%q boleh membaca mulai sekarang. Nanti diputus dengan nama itu.",
		phPhoneAlreadyPaired:      "sebuah ponsel sudah dipasangkan sebagai %q — putus dengan `%s revoke %s`, lalu pasangkan lagi",
		phNoEncryptionKey:         "belum ada kunci enkripsi — jalankan setup",
		phNoCloudflareRouteYet:    "belum ada rute Cloudflare — dirikan satu dengan `%s setup`",
		phThePhoneWasNotNamed:     "ponsel belum diberi nama, dan nama itulah yang dipakai untuk memutusnya",
	},
	"it": {
		phICloudFolder:            "la cartella iCloud",
		phCloudflareWorker:        "il tuo Cloudflare Worker",
		phOpenTheAppOnce:          "apri Amenbo Viewer (%s) sul telefono",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "è in piedi, ma non c'è nessuna chiave di cifratura — esegui setup",
		phStandingBadKey:          "è in piedi, ma la chiave nelle impostazioni non è utilizzabile — esegui di nuovo setup",
		phCarryingTo:              "Sta arrivando a %s.",
		phCarryingNowhere:         "Non arriva da nessuna parte.",
		phNothingIsTicked:         "Non sta arrivando da nessuna parte: in «Dove portarlo» non è spuntato nessun posto.",
		phWaitingOn:               " Manca: %s.",
		phNoSuchPlaceHere:         " Questa macchina non ha un posto come %s — quello è di un Mac.",
		phNowhere:                 "da nessuna parte",
		phAnd:                     " e ",
		phComma:                   ", ",
		phNothingToDrawOn:         "qui non c'è niente su cui disegnare un codice. Amenbo Viewer è su %s",
		phCodeNotDrawn:            "il codice non è stato disegnato (%w) — Amenbo Viewer è su %s",
		phPointTheCamera:          "punta la fotocamera del telefono sul codice. Amenbo Viewer è anche su %s",
		phImageNotOpened:          "l'immagine non si è aperta (%v) — la disegno qui",
		phCodeLeftWithKey:         "il codice è in %s e porta la chiave — cancellalo appena il telefono l'ha letto (%v).",
		phCodeLeftBehind:          "il codice è in %s, e non è stato avviato nulla per toglierlo di mezzo (%v).",
		phCodeIsOnScreen:          "il codice è sullo schermo, e l'immagine sparisce fra %d minuti — leggila col telefono prima di allora.",
		phNoScreenForTheTokenPage: "qui non c'è uno schermo su cui aprirla. La pagina del token è su %s",
		phTokenPageNotOpened:      "la pagina del token non si è aperta (%w) — è su %s",
		phTokenPageIsOpen:         "la pagina del token è aperta, con i permessi necessari già spuntati. Premi Continue to summary, poi Create Token, e incolla quello che mostra nella casella dietro il pulsante setup.",
		phBuildingInAccount:       "costruisco nell'account %s",
		phDatabaseCreated:         "database %s creato",
		phDatabaseAlreadyThere:    "il database %s c'era già",
		phWorkerDeployed:          "Worker %s distribuito",
		phNoWorkersDevName:        "il Worker è distribuito, ma questo account non ha ancora un nome workers.dev su cui rispondere. Scegline uno su %s ed esegui di nuovo setup",
		phTheRouteIsUp:            "la rotta Cloudflare è in piedi su %s",
		phTheKeyWasKept:           "la chiave di cifratura già presente nelle impostazioni è stata mantenuta, quindi i telefoni accoppiati con quella continuano a leggere.",
		phANewKeyWasGenerated:     "è stata generata una nuova chiave di cifratura — accoppia un telefono con `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "il Worker e il database sono tuoi. Disinstallare questo plugin li lascia dove sono;\n  cancellali dal pannello Cloudflare quando vuoi liberartene.",
		phNoTokenWasPasted:        "non è stato incollato nessun token",
		phTokenReachesNoAccount:   "questo token non raggiunge nessun account Cloudflare — forse gli manca il permesso Account Settings (read)",
		phWorkerHasNoWriteToken:   "il Worker risponde ma non ha un token di scrittura: è una distribuzione arrivata a metà — esegui di nuovo setup",
		phEndpointNotAnsweringYet: "è stato creato tutto, ma l'endpoint non risponde ancora come dovrebbe: %w",
		phPhoneMayReadFromNowOn:   "%q può leggere da adesso. Più avanti lo si taglia fuori con quel nome.",
		phPhoneAlreadyPaired:      "un telefono è già accoppiato come %q — taglialo fuori con `%s revoke %s`, poi accoppialo di nuovo",
		phNoEncryptionKey:         "non c'è nessuna chiave di cifratura — esegui setup",
		phNoCloudflareRouteYet:    "non c'è ancora una rotta Cloudflare — tirane su una con `%s setup`",
		phThePhoneWasNotNamed:     "il telefono non è stato chiamato in nessun modo, ed è il nome che serve per tagliarlo fuori",
	},
	"ja": {
		phICloudFolder:            "iCloud フォルダ",
		phCloudflareWorker:        "Cloudflare Worker",
		phOpenTheAppOnce:          "端末で Amenbo Viewer を開く (%s)",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "立ってはいるが、暗号鍵が設定されていません — setup を実行してください",
		phStandingBadKey:          "立ってはいるが、設定の鍵が使えません — setup をやり直してください",
		phCarryingTo:              "届いている先: %s。",
		phCarryingNowhere:         "どこにも届いていません。",
		phNothingIsTicked:         "どこへも届いていません:「どこへ運ぶか」で置き場が1つも選ばれていません。",
		phWaitingOn:               "待ち: %s。",
		phNoSuchPlaceHere:         "この機械に %sはありません — あれは mac だけのものです。",
		phNowhere:                 "どこにも",
		phAnd:                     "と ",
		phComma:                   "、",
		phNothingToDrawOn:         "ここにはコードを描く先がありません。Amenbo Viewer は %s にあります",
		phCodeNotDrawn:            "コードを描けませんでした (%w) — Amenbo Viewer は %s にあります",
		phPointTheCamera:          "端末のカメラをコードに向けてください。Amenbo Viewer は %s にもあります",
		phImageNotOpened:          "画像を開けませんでした (%v) — 代わりにここに描きます",
		phCodeLeftWithKey:         "コードは %s にあり、鍵を載せています — 端末が読み取ったら消してください (%v)。",
		phCodeLeftBehind:          "コードは %s にあり、消す手はかかりませんでした (%v)。",
		phCodeIsOnScreen:          "コードを表示しました。画像は %d 分で消えるので、それまでに端末で読み取ってください。",
		phNoScreenForTheTokenPage: "ここには開く画面がありません。トークンのページは %s です",
		phTokenPageNotOpened:      "トークンのページを開けませんでした (%w) — ページは %s です",
		phTokenPageIsOpen:         "トークンのページを開きました。必要な権限は選択済みです。Continue to summary、Create Token の順に押し、表示された文字列を setup ボタンの入力欄に貼ってください。",
		phBuildingInAccount:       "アカウント %s に作ります",
		phDatabaseCreated:         "データベース %s を作成しました",
		phDatabaseAlreadyThere:    "データベース %s はすでにありました",
		phWorkerDeployed:          "Worker %s をデプロイしました",
		phNoWorkersDevName:        "Worker はデプロイできましたが、このアカウントにはまだ workers.dev の名前がありません。%s で決めてから setup をやり直してください",
		phTheRouteIsUp:            "Cloudflare 経路が %s で立ち上がりました",
		phTheKeyWasKept:           "設定にあった暗号鍵をそのまま使ったので、ペアリング済みの端末は引き続き読めます。",
		phANewKeyWasGenerated:     "暗号鍵を新しく作りました — `amenbo plugin run %s qr` で端末をペアリングしてください。",
		phTheWorkerIsYours:        "Worker とデータベースは利用者のものです。このプラグインを削除してもそのまま残ります。\n  不要になったら Cloudflare のダッシュボードで削除してください。",
		phNoTokenWasPasted:        "トークンが貼られませんでした",
		phTokenReachesNoAccount:   "このトークンはどの Cloudflare アカウントにも届きません — Account Settings (read) の権限が足りない可能性があります",
		phWorkerHasNoWriteToken:   "Worker は応答していますが書き込みトークンが設定されていません。デプロイが最後まで届いていないので、setup をやり直してください",
		phEndpointNotAnsweringYet: "作成は済みましたが、エンドポイントがまだ想定どおりに応答しません: %w",
		phPhoneMayReadFromNowOn:   "%q が読めるようになりました。あとで切るときはこの名前で指します。",
		phPhoneAlreadyPaired:      "%q という名前の端末はすでにペアリング済みです — `%s revoke %s` で切ってから、もう一度ペアリングしてください",
		phNoEncryptionKey:         "暗号鍵が設定されていません — setup を実行してください",
		phNoCloudflareRouteYet:    "Cloudflare 経路がまだありません — `%s setup` で立ち上げてください",
		phThePhoneWasNotNamed:     "端末に名前が付いていません。切るときに指すのはその名前です",
	},
	"ko": {
		phICloudFolder:            "iCloud 폴더",
		phCloudflareWorker:        "내 Cloudflare Worker",
		phOpenTheAppOnce:          "휴대폰에서 Amenbo Viewer (%s) 열기",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "자리는 있지만 암호화 키가 설정되어 있지 않습니다 — setup 실행",
		phStandingBadKey:          "자리는 있지만 설정의 키를 쓸 수 없습니다 — setup 다시 실행",
		phCarryingTo:              "전달 중: %s.",
		phCarryingNowhere:         "아직 어디로도 전달되지 않습니다.",
		phNothingIsTicked:         "어디로도 전달되지 않습니다: 「어디로 보낼지」에서 선택된 곳이 없습니다.",
		phWaitingOn:               " 대기: %s.",
		phNoSuchPlaceHere:         " 이 기기에는 %s 같은 곳이 없습니다 — 그것은 mac의 것입니다.",
		phNowhere:                 "어디로도",
		phAnd:                     " 및 ",
		phComma:                   ", ",
		phNothingToDrawOn:         "여기에는 코드를 그릴 곳이 없습니다. Amenbo Viewer는 %s에 있습니다",
		phCodeNotDrawn:            "코드를 그리지 못했습니다 (%w) — Amenbo Viewer는 %s에 있습니다",
		phPointTheCamera:          "휴대폰 카메라를 코드에 맞추세요. Amenbo Viewer는 %s에도 있습니다",
		phImageNotOpened:          "이미지를 열지 못했습니다 (%v) — 대신 여기에 그립니다",
		phCodeLeftWithKey:         "코드는 %s에 있고 키를 담고 있습니다 — 휴대폰이 읽고 나면 삭제하세요 (%v).",
		phCodeLeftBehind:          "코드는 %s에 있고, 치우는 작업은 시작되지 않았습니다 (%v).",
		phCodeIsOnScreen:          "코드를 화면에 띄웠습니다. 이미지는 %d분 뒤에 사라지니 그전에 휴대폰으로 읽으세요.",
		phNoScreenForTheTokenPage: "여기에는 열 화면이 없습니다. 토큰 페이지는 %s입니다",
		phTokenPageNotOpened:      "토큰 페이지를 열지 못했습니다 (%w) — 페이지는 %s입니다",
		phTokenPageIsOpen:         "토큰 페이지를 열었고 필요한 권한은 이미 선택되어 있습니다. Continue to summary, Create Token 순서로 누른 뒤 표시된 값을 setup 버튼 뒤의 입력란에 붙여 넣으세요.",
		phBuildingInAccount:       "계정 %s에 만드는 중",
		phDatabaseCreated:         "데이터베이스 %s 생성됨",
		phDatabaseAlreadyThere:    "데이터베이스 %s은(는) 이미 있었습니다",
		phWorkerDeployed:          "Worker %s 배포됨",
		phNoWorkersDevName:        "Worker는 배포되었지만 이 계정에는 아직 응답할 workers.dev 이름이 없습니다. %s에서 하나 정한 뒤 setup을 다시 실행하세요",
		phTheRouteIsUp:            "Cloudflare 경로가 %s에 섰습니다",
		phTheKeyWasKept:           "설정에 있던 암호화 키를 그대로 두었으므로, 그 키로 짝지은 휴대폰은 계속 읽을 수 있습니다.",
		phANewKeyWasGenerated:     "새 암호화 키를 만들었습니다 — `amenbo plugin run %s qr`로 휴대폰을 짝지으세요.",
		phTheWorkerIsYours:        "Worker와 데이터베이스는 사용자의 것입니다. 이 플러그인을 지워도 그대로 남습니다;\n  필요 없어지면 Cloudflare 대시보드에서 삭제하세요.",
		phNoTokenWasPasted:        "토큰이 붙여 넣어지지 않았습니다",
		phTokenReachesNoAccount:   "이 토큰은 어떤 Cloudflare 계정에도 닿지 않습니다 — Account Settings (read) 권한이 빠졌을 수 있습니다",
		phWorkerHasNoWriteToken:   "Worker는 응답하지만 쓰기 토큰이 설정되어 있지 않습니다. 배포가 끝까지 닿지 않았으니 setup을 다시 실행하세요",
		phEndpointNotAnsweringYet: "생성은 모두 끝났지만 엔드포인트가 아직 제대로 응답하지 않습니다: %w",
		phPhoneMayReadFromNowOn:   "%q이(가) 이제부터 읽을 수 있습니다. 나중에 끊을 때 그 이름으로 가리킵니다.",
		phPhoneAlreadyPaired:      "%q(이)라는 이름의 휴대폰이 이미 짝지어져 있습니다 — `%s revoke %s`로 끊은 뒤 다시 짝지으세요",
		phNoEncryptionKey:         "암호화 키가 설정되어 있지 않습니다 — setup을 실행하세요",
		phNoCloudflareRouteYet:    "아직 Cloudflare 경로가 없습니다 — `%s setup`으로 세우세요",
		phThePhoneWasNotNamed:     "휴대폰에 이름이 없습니다. 끊을 때 가리키는 것이 그 이름입니다",
	},
	"nl": {
		phICloudFolder:            "de iCloud-map",
		phCloudflareWorker:        "je eigen Cloudflare Worker",
		phOpenTheAppOnce:          "open Amenbo Viewer (%s) op de telefoon",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "hij staat er, maar er is geen sleutel ingesteld — voer setup uit",
		phStandingBadKey:          "hij staat er, maar de sleutel in de instellingen is onbruikbaar — voer setup opnieuw uit",
		phCarryingTo:              "Gaat naar %s.",
		phCarryingNowhere:         "Gaat nergens heen.",
		phNothingIsTicked:         "Gaat nergens heen: onder «Waar het heen gaat» is geen plek aangevinkt.",
		phWaitingOn:               " Wacht op: %s.",
		phNoSuchPlaceHere:         " Deze machine heeft geen plek als %s — die hoort bij een Mac.",
		phNowhere:                 "nergens",
		phAnd:                     " en ",
		phComma:                   ", ",
		phNothingToDrawOn:         "hier is niets om een code op te tekenen. Amenbo Viewer staat op %s",
		phCodeNotDrawn:            "de code kon niet getekend worden (%w) — Amenbo Viewer staat op %s",
		phPointTheCamera:          "richt de camera van de telefoon op de code. Amenbo Viewer staat ook op %s",
		phImageNotOpened:          "de afbeelding kon niet geopend worden (%v) — hij wordt hier getekend",
		phCodeLeftWithKey:         "de code staat op %s en draagt de sleutel — verwijder hem zodra de telefoon hem gelezen heeft (%v).",
		phCodeLeftBehind:          "de code staat op %s, en er is niets gestart om hem weer op te ruimen (%v).",
		phCodeIsOnScreen:          "de code staat op het scherm, en de afbeelding verdwijnt over %d minuten — lees hem daarvoor met de telefoon.",
		phNoScreenForTheTokenPage: "hier is geen scherm om hem op te openen. De tokenpagina staat op %s",
		phTokenPageNotOpened:      "de tokenpagina kon niet geopend worden (%w) — hij staat op %s",
		phTokenPageIsOpen:         "de tokenpagina is open, met de benodigde rechten al aangevinkt. Druk op Continue to summary, dan Create Token, en plak wat er verschijnt in het vak achter de setup-knop.",
		phBuildingInAccount:       "bouwen in account %s",
		phDatabaseCreated:         "database %s aangemaakt",
		phDatabaseAlreadyThere:    "database %s was er al",
		phWorkerDeployed:          "Worker %s uitgerold",
		phNoWorkersDevName:        "de Worker is uitgerold, maar dit account heeft nog geen workers.dev-naam om op te antwoorden. Kies er een op %s en voer setup opnieuw uit",
		phTheRouteIsUp:            "de Cloudflare-route staat op %s",
		phTheKeyWasKept:           "de sleutel die al in de instellingen stond is behouden, dus de telefoons die daarmee gekoppeld zijn blijven lezen.",
		phANewKeyWasGenerated:     "er is een nieuwe sleutel gemaakt — koppel een telefoon met `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "de Worker en de database zijn van jou. Dit plugin verwijderen laat ze staan waar ze staan;\n  verwijder ze in het Cloudflare-dashboard wanneer je ze kwijt wilt.",
		phNoTokenWasPasted:        "er is geen token geplakt",
		phTokenReachesNoAccount:   "dit token bereikt geen enkel Cloudflare-account — misschien mist het de rechten Account Settings (read)",
		phWorkerHasNoWriteToken:   "de Worker antwoordt maar heeft geen schrijftoken: een uitrol die niet helemaal geland is — voer setup opnieuw uit",
		phEndpointNotAnsweringYet: "alles is aangemaakt, maar het endpoint antwoordt nog niet zoals het hoort: %w",
		phPhoneMayReadFromNowOn:   "%q mag vanaf nu lezen. Onder die naam wordt hij later afgesneden.",
		phPhoneAlreadyPaired:      "er is al een telefoon gekoppeld als %q — snijd hem af met `%s revoke %s` en koppel hem opnieuw",
		phNoEncryptionKey:         "er is geen sleutel ingesteld — voer setup uit",
		phNoCloudflareRouteYet:    "er is nog geen Cloudflare-route — zet er een op met `%s setup`",
		phThePhoneWasNotNamed:     "de telefoon heeft geen naam gekregen, en de naam is waarmee je hem later afsnijdt",
	},
	"pl": {
		phICloudFolder:            "folder iCloud",
		phCloudflareWorker:        "twój własny Cloudflare Worker",
		phOpenTheAppOnce:          "otwórz Amenbo Viewer (%s) na telefonie",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "stoi, ale nie ustawiono klucza szyfrowania — uruchom setup",
		phStandingBadKey:          "stoi, ale klucza z ustawień nie da się użyć — uruchom setup ponownie",
		phCarryingTo:              "Trafia do %s.",
		phCarryingNowhere:         "Nie trafia nigdzie.",
		phNothingIsTicked:         "Nie trafia nigdzie: w «Dokąd wysyłać» nie zaznaczono żadnego miejsca.",
		phWaitingOn:               " Czeka: %s.",
		phNoSuchPlaceHere:         " Ta maszyna nie ma takiego miejsca jak %s — ono należy do maca.",
		phNowhere:                 "nigdzie",
		phAnd:                     " i ",
		phComma:                   ", ",
		phNothingToDrawOn:         "nie ma tu na czym narysować kodu. Amenbo Viewer jest pod %s",
		phCodeNotDrawn:            "nie udało się narysować kodu (%w) — Amenbo Viewer jest pod %s",
		phPointTheCamera:          "skieruj aparat telefonu na kod. Amenbo Viewer jest też pod %s",
		phImageNotOpened:          "nie udało się otworzyć obrazu (%v) — rysuję go tutaj",
		phCodeLeftWithKey:         "kod jest w %s i niesie klucz — usuń go, gdy telefon go odczyta (%v).",
		phCodeLeftBehind:          "kod jest w %s, a nic nie zostało uruchomione, żeby go potem sprzątnąć (%v).",
		phCodeIsOnScreen:          "kod jest na ekranie, a obraz zniknie za %d min — odczytaj go telefonem wcześniej.",
		phNoScreenForTheTokenPage: "nie ma tu ekranu, na którym można by ją otworzyć. Strona tokenu jest pod %s",
		phTokenPageNotOpened:      "nie udało się otworzyć strony tokenu (%w) — jest pod %s",
		phTokenPageIsOpen:         "strona tokenu jest otwarta, z już zaznaczonymi potrzebnymi uprawnieniami. Naciśnij Continue to summary, potem Create Token, i wklej to, co pokaże, w pole za przyciskiem setup.",
		phBuildingInAccount:       "buduję na koncie %s",
		phDatabaseCreated:         "baza danych %s utworzona",
		phDatabaseAlreadyThere:    "baza danych %s już była",
		phWorkerDeployed:          "Worker %s wdrożony",
		phNoWorkersDevName:        "Worker jest wdrożony, ale to konto nie ma jeszcze nazwy workers.dev, pod którą mógłby odpowiadać. Wybierz ją na %s i uruchom setup ponownie",
		phTheRouteIsUp:            "trasa Cloudflare stoi pod %s",
		phTheKeyWasKept:           "klucz szyfrowania, który był już w ustawieniach, został zachowany, więc sparowane nim telefony nadal czytają.",
		phANewKeyWasGenerated:     "wygenerowano nowy klucz szyfrowania — sparuj telefon poleceniem `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "Worker i baza danych są twoje. Odinstalowanie tej wtyczki zostawia je tam, gdzie są;\n  usuń je w panelu Cloudflare, kiedy będziesz chciał się ich pozbyć.",
		phNoTokenWasPasted:        "nie wklejono żadnego tokenu",
		phTokenReachesNoAccount:   "ten token nie sięga żadnego konta Cloudflare — może brakuje mu uprawnienia Account Settings (read)",
		phWorkerHasNoWriteToken:   "Worker odpowiada, ale nie ma ustawionego tokenu zapisu — wdrożenie nie doszło do końca. Uruchom setup ponownie",
		phEndpointNotAnsweringYet: "wszystko zostało utworzone, ale punkt końcowy jeszcze nie odpowiada tak, jak powinien: %w",
		phPhoneMayReadFromNowOn:   "%q może od teraz czytać. Później odcina się go po tej nazwie.",
		phPhoneAlreadyPaired:      "telefon o nazwie %q jest już sparowany — odetnij go poleceniem `%s revoke %s`, a potem sparuj ponownie",
		phNoEncryptionKey:         "nie ustawiono klucza szyfrowania — uruchom setup",
		phNoCloudflareRouteYet:    "nie ma jeszcze trasy Cloudflare — postaw ją poleceniem `%s setup`",
		phThePhoneWasNotNamed:     "telefon nie dostał nazwy, a to nazwą się go potem odcina",
	},
	"pt-BR": {
		phICloudFolder:            "a pasta do iCloud",
		phCloudflareWorker:        "o seu Cloudflare Worker",
		phOpenTheAppOnce:          "abra o Amenbo Viewer (%s) no celular",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "está de pé, mas não há chave de criptografia configurada — execute setup",
		phStandingBadKey:          "está de pé, mas a chave das configurações não serve — execute setup de novo",
		phCarryingTo:              "Chegando a %s.",
		phCarryingNowhere:         "Não chega a lugar nenhum.",
		phNothingIsTicked:         "Não chega a lugar nenhum: nenhum lugar está marcado em «Para onde levar».",
		phWaitingOn:               " Falta: %s.",
		phNoSuchPlaceHere:         " Esta máquina não tem um lugar como %s — esse é coisa de Mac.",
		phNowhere:                 "lugar nenhum",
		phAnd:                     " e ",
		phComma:                   ", ",
		phNothingToDrawOn:         "aqui não há onde desenhar um código. O Amenbo Viewer está em %s",
		phCodeNotDrawn:            "o código não pôde ser desenhado (%w) — o Amenbo Viewer está em %s",
		phPointTheCamera:          "aponte a câmera do celular para o código. O Amenbo Viewer também está em %s",
		phImageNotOpened:          "a imagem não pôde ser aberta (%v) — desenhando aqui mesmo",
		phCodeLeftWithKey:         "o código está em %s e leva a chave — apague-o assim que o celular o tiver lido (%v).",
		phCodeLeftBehind:          "o código está em %s, e nada foi iniciado para removê-lo depois (%v).",
		phCodeIsOnScreen:          "o código está na tela, e a imagem some em %d minutos — leia com o celular antes disso.",
		phNoScreenForTheTokenPage: "aqui não há tela para abri-la. A página do token está em %s",
		phTokenPageNotOpened:      "a página do token não pôde ser aberta (%w) — ela está em %s",
		phTokenPageIsOpen:         "a página do token está aberta, com as permissões necessárias já marcadas. Pressione Continue to summary, depois Create Token, e cole o que aparecer na caixa atrás do botão setup.",
		phBuildingInAccount:       "construindo na conta %s",
		phDatabaseCreated:         "banco de dados %s criado",
		phDatabaseAlreadyThere:    "o banco de dados %s já existia",
		phWorkerDeployed:          "Worker %s implantado",
		phNoWorkersDevName:        "o Worker foi implantado, mas esta conta ainda não tem um nome workers.dev para responder. Escolha um em %s e execute setup de novo",
		phTheRouteIsUp:            "a rota do Cloudflare está de pé em %s",
		phTheKeyWasKept:           "a chave de criptografia que já estava nas configurações foi mantida, então os celulares pareados com ela continuam lendo.",
		phANewKeyWasGenerated:     "uma nova chave de criptografia foi gerada — pareie um celular com `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "o Worker e o banco de dados são seus. Desinstalar este plugin os deixa onde estão;\n  apague-os no painel do Cloudflare quando quiser se livrar deles.",
		phNoTokenWasPasted:        "nenhum token foi colado",
		phTokenReachesNoAccount:   "este token não alcança nenhuma conta do Cloudflare — pode estar faltando a permissão Account Settings (read)",
		phWorkerHasNoWriteToken:   "o Worker responde mas não tem token de escrita, o que é uma implantação que não chegou até o fim — execute setup de novo",
		phEndpointNotAnsweringYet: "tudo foi criado, mas o endpoint ainda não responde como deveria: %w",
		phPhoneMayReadFromNowOn:   "%q pode ler daqui em diante. Depois é por esse nome que se corta.",
		phPhoneAlreadyPaired:      "já há um celular pareado como %q — corte-o com `%s revoke %s` e pareie de novo",
		phNoEncryptionKey:         "não há chave de criptografia configurada — execute setup",
		phNoCloudflareRouteYet:    "ainda não há rota do Cloudflare — levante uma com `%s setup`",
		phThePhoneWasNotNamed:     "o celular não recebeu nome, e é o nome que se usa para cortá-lo",
	},
	"ru": {
		phICloudFolder:            "папка iCloud",
		phCloudflareWorker:        "ваш Cloudflare Worker",
		phOpenTheAppOnce:          "Amenbo Viewer (%s) на телефоне",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "он стоит, но ключ шифрования не задан — выполните setup",
		phStandingBadKey:          "он стоит, но ключом из настроек нельзя пользоваться — выполните setup заново",
		phCarryingTo:              "Доставляется: %s.",
		phCarryingNowhere:         "Пока никуда.",
		phNothingIsTicked:         "Никуда не доставляется: в «Куда доставлять» не отмечено ни одного места.",
		phWaitingOn:               " Ждём: %s.",
		phNoSuchPlaceHere:         " %s — такого места на этой машине нет, оно есть только у мака.",
		phNowhere:                 "никуда",
		phAnd:                     " и ",
		phComma:                   ", ",
		phNothingToDrawOn:         "здесь не на чем нарисовать код. Amenbo Viewer находится по адресу %s",
		phCodeNotDrawn:            "код не удалось нарисовать (%w) — Amenbo Viewer находится по адресу %s",
		phPointTheCamera:          "наведите камеру телефона на код. Amenbo Viewer есть и по адресу %s",
		phImageNotOpened:          "картинку не удалось открыть (%v) — рисуем её здесь",
		phCodeLeftWithKey:         "код лежит в %s и несёт ключ — удалите его, как только телефон его прочитает (%v).",
		phCodeLeftBehind:          "код лежит в %s, и ничего не запущено, чтобы потом его убрать (%v).",
		phCodeIsOnScreen:          "код на экране, картинка исчезнет через %d мин — успейте прочитать её телефоном.",
		phNoScreenForTheTokenPage: "здесь нет экрана, чтобы её открыть. Страница токена — %s",
		phTokenPageNotOpened:      "страницу токена не удалось открыть (%w) — она находится по адресу %s",
		phTokenPageIsOpen:         "страница токена открыта, нужные разрешения уже отмечены. Нажмите Continue to summary, затем Create Token и вставьте показанное в поле за кнопкой setup.",
		phBuildingInAccount:       "строим в аккаунте %s",
		phDatabaseCreated:         "база данных %s создана",
		phDatabaseAlreadyThere:    "база данных %s уже была",
		phWorkerDeployed:          "Worker %s развёрнут",
		phNoWorkersDevName:        "Worker развёрнут, но у этого аккаунта пока нет имени workers.dev, на котором он мог бы отвечать. Выберите его на %s и выполните setup заново",
		phTheRouteIsUp:            "маршрут Cloudflare поднят на %s",
		phTheKeyWasKept:           "ключ шифрования, который уже был в настройках, сохранён, поэтому связанные с ним телефоны продолжают читать.",
		phANewKeyWasGenerated:     "создан новый ключ шифрования — свяжите телефон командой `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "Worker и база данных — ваши. Удаление этого плагина оставляет их на месте;\n  удалите их в панели Cloudflare, когда они станут не нужны.",
		phNoTokenWasPasted:        "токен не вставлен",
		phTokenReachesNoAccount:   "этот токен не достаёт ни до одного аккаунта Cloudflare — возможно, ему не хватает разрешения Account Settings (read)",
		phWorkerHasNoWriteToken:   "Worker отвечает, но у него не задан токен записи — развёртывание дошло не до конца. Выполните setup заново",
		phEndpointNotAnsweringYet: "всё создано, но конечная точка пока отвечает не так, как должна: %w",
		phPhoneMayReadFromNowOn:   "%q может читать с этого момента. Позже его отключают по этому имени.",
		phPhoneAlreadyPaired:      "телефон с именем %q уже связан — отключите его командой `%s revoke %s` и свяжите заново",
		phNoEncryptionKey:         "ключ шифрования не задан — выполните setup",
		phNoCloudflareRouteYet:    "маршрута Cloudflare пока нет — поднимите его командой `%s setup`",
		phThePhoneWasNotNamed:     "телефону не дали имени, а именно по имени его потом отключают",
	},
	"th": {
		phICloudFolder:            "โฟลเดอร์ iCloud",
		phCloudflareWorker:        "Cloudflare Worker",
		phOpenTheAppOnce:          "เปิด Amenbo Viewer (%s)",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "ตั้งอยู่แล้ว แต่ยังไม่ได้ตั้งกุญแจเข้ารหัส — รัน setup",
		phStandingBadKey:          "ตั้งอยู่แล้ว แต่กุญแจในการตั้งค่าใช้ไม่ได้ — รัน setup ใหม่",
		phCarryingTo:              "ส่งไปที่: %s",
		phCarryingNowhere:         "ยังไม่ส่งไปไหน",
		phNothingIsTicked:         "ยังไม่ได้ส่งไปที่ใดเลย: ไม่มีที่ใดถูกเลือกใน «จะส่งไปที่ไหน»",
		phWaitingOn:               " รอ: %s",
		phNoSuchPlaceHere:         " %s — ของ mac เครื่องนี้ไม่มี",
		phNowhere:                 "ไม่มีที่ใด",
		phAnd:                     " และ ",
		phComma:                   ", ",
		phNothingToDrawOn:         "ที่นี่ไม่มีที่ให้วาดรหัส Amenbo Viewer อยู่ที่ %s",
		phCodeNotDrawn:            "วาดรหัสไม่ได้ (%w) — Amenbo Viewer อยู่ที่ %s",
		phPointTheCamera:          "เล็งกล้องของโทรศัพท์ไปที่รหัส Amenbo Viewer อยู่ที่ %s ด้วย",
		phImageNotOpened:          "เปิดรูปไม่ได้ (%v) — จะวาดไว้ตรงนี้แทน",
		phCodeLeftWithKey:         "รหัสอยู่ที่ %s และมีกุญแจอยู่ในนั้น — ลบทิ้งเมื่อโทรศัพท์อ่านแล้ว (%v)",
		phCodeLeftBehind:          "รหัสอยู่ที่ %s และไม่ได้เริ่มอะไรไว้เพื่อเก็บกวาดทีหลัง (%v)",
		phCodeIsOnScreen:          "รหัสอยู่บนหน้าจอแล้ว และรูปจะหายไปใน %d นาที — อ่านด้วยโทรศัพท์ก่อนถึงเวลานั้น",
		phNoScreenForTheTokenPage: "ที่นี่ไม่มีหน้าจอให้เปิด หน้าโทเคนอยู่ที่ %s",
		phTokenPageNotOpened:      "เปิดหน้าโทเคนไม่ได้ (%w) — หน้านั้นอยู่ที่ %s",
		phTokenPageIsOpen:         "เปิดหน้าโทเคนแล้ว โดยเลือกสิทธิ์ที่ต้องใช้ไว้ให้เรียบร้อย กด Continue to summary แล้วกด Create Token จากนั้นวางสิ่งที่แสดงลงในช่องหลังปุ่ม setup",
		phBuildingInAccount:       "กำลังสร้างในบัญชี %s",
		phDatabaseCreated:         "สร้างฐานข้อมูล %s แล้ว",
		phDatabaseAlreadyThere:    "ฐานข้อมูล %s มีอยู่แล้ว",
		phWorkerDeployed:          "ปล่อย Worker %s แล้ว",
		phNoWorkersDevName:        "ปล่อย Worker แล้ว แต่บัญชีนี้ยังไม่มีชื่อ workers.dev ให้ตอบ เลือกสักชื่อที่ %s แล้วรัน setup ใหม่",
		phTheRouteIsUp:            "เส้นทาง Cloudflare ตั้งขึ้นแล้วที่ %s",
		phTheKeyWasKept:           "กุญแจเข้ารหัสที่มีอยู่ในการตั้งค่าถูกเก็บไว้ตามเดิม โทรศัพท์ที่จับคู่ด้วยกุญแจนั้นจึงอ่านได้ต่อไป",
		phANewKeyWasGenerated:     "สร้างกุญแจเข้ารหัสใหม่แล้ว — จับคู่โทรศัพท์ด้วย `amenbo plugin run %s qr`",
		phTheWorkerIsYours:        "Worker และฐานข้อมูลเป็นของคุณ ถอนปลั๊กอินนี้ออกก็ยังอยู่ที่เดิม\n  ลบได้ที่แดชบอร์ดของ Cloudflare เมื่อไม่ต้องการแล้ว",
		phNoTokenWasPasted:        "ไม่ได้วางโทเคน",
		phTokenReachesNoAccount:   "โทเคนนี้ไปไม่ถึงบัญชี Cloudflare ใดเลย — อาจขาดสิทธิ์ Account Settings (read)",
		phWorkerHasNoWriteToken:   "Worker ตอบอยู่ แต่ยังไม่ได้ตั้งโทเคนสำหรับเขียน แปลว่าการปล่อยยังลงไม่ครบ — รัน setup ใหม่",
		phEndpointNotAnsweringYet: "สร้างครบแล้ว แต่ปลายทางยังตอบไม่ถูกต้องอย่างที่ควรเป็น: %w",
		phPhoneMayReadFromNowOn:   "%q อ่านได้ตั้งแต่นี้ไป ภายหลังจะตัดออกด้วยชื่อนี้",
		phPhoneAlreadyPaired:      "มีโทรศัพท์จับคู่ในชื่อ %q อยู่แล้ว — ตัดออกด้วย `%s revoke %s` แล้วจับคู่ใหม่",
		phNoEncryptionKey:         "ยังไม่ได้ตั้งกุญแจเข้ารหัส — รัน setup",
		phNoCloudflareRouteYet:    "ยังไม่มีเส้นทาง Cloudflare — ตั้งขึ้นด้วย `%s setup`",
		phThePhoneWasNotNamed:     "ยังไม่ได้ตั้งชื่อให้โทรศัพท์ และชื่อนั้นคือสิ่งที่ใช้ตัดออกภายหลัง",
	},
	"tr": {
		phICloudFolder:            "iCloud klasörü",
		phCloudflareWorker:        "kendi Cloudflare Worker'ın",
		phOpenTheAppOnce:          "telefonda Amenbo Viewer (%s) aç",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "ayakta, ama şifreleme anahtarı ayarlanmamış — setup çalıştır",
		phStandingBadKey:          "ayakta, ama ayarlardaki anahtar kullanılamıyor — setup'ı yeniden çalıştır",
		phCarryingTo:              "%s adresine ulaşıyor.",
		phCarryingNowhere:         "Hiçbir yere ulaşmıyor.",
		phNothingIsTicked:         "Hiçbir yere ulaşmıyor: «Nereye taşınacak» altında hiçbir yer işaretli değil.",
		phWaitingOn:               " Bekleyen: %s.",
		phNoSuchPlaceHere:         " Bu makinede %s gibi bir yer yok — o bir mac'e ait.",
		phNowhere:                 "hiçbir yer",
		phAnd:                     " ve ",
		phComma:                   ", ",
		phNothingToDrawOn:         "burada kod çizilecek bir yer yok. Amenbo Viewer %s adresinde",
		phCodeNotDrawn:            "kod çizilemedi (%w) — Amenbo Viewer %s adresinde",
		phPointTheCamera:          "telefonun kamerasını koda tut. Amenbo Viewer ayrıca %s adresinde",
		phImageNotOpened:          "görsel açılamadı (%v) — onun yerine buraya çiziliyor",
		phCodeLeftWithKey:         "kod %s konumunda ve anahtarı taşıyor — telefon okur okumaz sil (%v).",
		phCodeLeftBehind:          "kod %s konumunda ve onu sonradan kaldıracak hiçbir şey başlatılmadı (%v).",
		phCodeIsOnScreen:          "kod ekranda ve görsel %d dakika içinde gidiyor — ondan önce telefonla oku.",
		phNoScreenForTheTokenPage: "burada açacak bir ekran yok. Belirteç sayfası %s adresinde",
		phTokenPageNotOpened:      "belirteç sayfası açılamadı (%w) — sayfa %s adresinde",
		phTokenPageIsOpen:         "belirteç sayfası açık, gereken izinler önceden işaretli. Continue to summary'ye, sonra Create Token'a bas ve gösterdiğini setup düğmesinin arkasındaki kutuya yapıştır.",
		phBuildingInAccount:       "%s hesabında kuruluyor",
		phDatabaseCreated:         "%s veritabanı oluşturuldu",
		phDatabaseAlreadyThere:    "%s veritabanı zaten vardı",
		phWorkerDeployed:          "Worker %s dağıtıldı",
		phNoWorkersDevName:        "Worker dağıtıldı, ama bu hesabın henüz yanıt vereceği bir workers.dev adı yok. %s adresinden bir tane seç ve setup'ı yeniden çalıştır",
		phTheRouteIsUp:            "Cloudflare yolu %s adresinde ayakta",
		phTheKeyWasKept:           "ayarlarda hâlihazırda duran şifreleme anahtarı korundu, onunla eşleştirilmiş telefonlar okumaya devam ediyor.",
		phANewKeyWasGenerated:     "yeni bir şifreleme anahtarı üretildi — `amenbo plugin run %s qr` ile bir telefon eşleştir.",
		phTheWorkerIsYours:        "Worker ve veritabanı senin. Bu eklentiyi kaldırmak onları yerinde bırakır;\n  istemediğinde Cloudflare panosundan sil.",
		phNoTokenWasPasted:        "hiçbir belirteç yapıştırılmadı",
		phTokenReachesNoAccount:   "bu belirteç hiçbir Cloudflare hesabına ulaşmıyor — Account Settings (read) izni eksik olabilir",
		phWorkerHasNoWriteToken:   "Worker yanıt veriyor ama yazma belirteci ayarlı değil; bu, sonuna kadar inmemiş bir dağıtımdır — setup'ı yeniden çalıştır",
		phEndpointNotAnsweringYet: "her şey oluşturuldu, ama uç nokta henüz olması gerektiği gibi yanıt vermiyor: %w",
		phPhoneMayReadFromNowOn:   "%q artık okuyabilir. Sonradan bu adla kesilir.",
		phPhoneAlreadyPaired:      "%q adıyla eşleştirilmiş bir telefon zaten var — `%s revoke %s` ile kes, sonra yeniden eşleştir",
		phNoEncryptionKey:         "şifreleme anahtarı ayarlanmamış — setup çalıştır",
		phNoCloudflareRouteYet:    "henüz bir Cloudflare yolu yok — `%s setup` ile bir tane kur",
		phThePhoneWasNotNamed:     "telefona ad verilmedi, oysa keserken gösterilecek olan o addır",
	},
	"uk": {
		phICloudFolder:            "тека iCloud",
		phCloudflareWorker:        "ваш Cloudflare Worker",
		phOpenTheAppOnce:          "Amenbo Viewer (%s) на телефоні",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "він стоїть, але ключ шифрування не задано — виконайте setup",
		phStandingBadKey:          "він стоїть, але ключем із налаштувань не можна скористатися — виконайте setup ще раз",
		phCarryingTo:              "Доставляється: %s.",
		phCarryingNowhere:         "Поки нікуди.",
		phNothingIsTicked:         "Нікуди не доставляється: у «Куди доставляти» не позначено жодного місця.",
		phWaitingOn:               " Чекаємо: %s.",
		phNoSuchPlaceHere:         " %s — такого місця на цій машині немає, воно є лише в мака.",
		phNowhere:                 "нікуди",
		phAnd:                     " і ",
		phComma:                   ", ",
		phNothingToDrawOn:         "тут немає на чому намалювати код. Amenbo Viewer — за адресою %s",
		phCodeNotDrawn:            "код не вдалося намалювати (%w) — Amenbo Viewer за адресою %s",
		phPointTheCamera:          "наведіть камеру телефона на код. Amenbo Viewer є й за адресою %s",
		phImageNotOpened:          "зображення не вдалося відкрити (%v) — малюємо його тут",
		phCodeLeftWithKey:         "код лежить у %s і несе ключ — видаліть його, щойно телефон його прочитає (%v).",
		phCodeLeftBehind:          "код лежить у %s, і нічого не запущено, щоб потім його прибрати (%v).",
		phCodeIsOnScreen:          "код на екрані, зображення зникне за %d хв — встигніть прочитати його телефоном.",
		phNoScreenForTheTokenPage: "тут немає екрана, щоб її відкрити. Сторінка токена — %s",
		phTokenPageNotOpened:      "сторінку токена не вдалося відкрити (%w) — вона за адресою %s",
		phTokenPageIsOpen:         "сторінку токена відкрито, потрібні дозволи вже позначено. Натисніть Continue to summary, потім Create Token і вставте показане в поле за кнопкою setup.",
		phBuildingInAccount:       "будуємо в обліковому записі %s",
		phDatabaseCreated:         "базу даних %s створено",
		phDatabaseAlreadyThere:    "база даних %s уже була",
		phWorkerDeployed:          "Worker %s розгорнуто",
		phNoWorkersDevName:        "Worker розгорнуто, але цей обліковий запис ще не має імені workers.dev, на якому він відповідав би. Оберіть його на %s і виконайте setup ще раз",
		phTheRouteIsUp:            "маршрут Cloudflare піднято на %s",
		phTheKeyWasKept:           "ключ шифрування, який уже був у налаштуваннях, збережено, тож пов'язані з ним телефони читають далі.",
		phANewKeyWasGenerated:     "створено новий ключ шифрування — пов'яжіть телефон командою `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "Worker і база даних — ваші. Видалення цього плагіна залишає їх на місці;\n  видаліть їх у панелі Cloudflare, коли вони стануть непотрібні.",
		phNoTokenWasPasted:        "токен не вставлено",
		phTokenReachesNoAccount:   "цей токен не дістає до жодного облікового запису Cloudflare — можливо, йому бракує дозволу Account Settings (read)",
		phWorkerHasNoWriteToken:   "Worker відповідає, але не має токена запису — розгортання дійшло не до кінця. Виконайте setup ще раз",
		phEndpointNotAnsweringYet: "усе створено, але кінцева точка ще відповідає не так, як мала б: %w",
		phPhoneMayReadFromNowOn:   "%q може читати відтепер. Згодом його відрізають за цим іменем.",
		phPhoneAlreadyPaired:      "телефон з іменем %q уже пов'язано — відріжте його командою `%s revoke %s`, а потім пов'яжіть знову",
		phNoEncryptionKey:         "ключ шифрування не задано — виконайте setup",
		phNoCloudflareRouteYet:    "маршруту Cloudflare ще немає — підніміть його командою `%s setup`",
		phThePhoneWasNotNamed:     "телефонові не дали імені, а саме за іменем його потім відрізають",
	},
	"vi": {
		phICloudFolder:            "thư mục iCloud",
		phCloudflareWorker:        "Cloudflare Worker của bạn",
		phOpenTheAppOnce:          "mở Amenbo Viewer (%s) trên điện thoại",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "nó đã dựng, nhưng chưa đặt khóa mã hóa — chạy setup",
		phStandingBadKey:          "nó đã dựng, nhưng khóa trong cài đặt không dùng được — chạy lại setup",
		phCarryingTo:              "Đang chuyển tới %s.",
		phCarryingNowhere:         "Chưa tới đâu cả.",
		phNothingIsTicked:         "Chưa chuyển tới đâu cả: không có nơi nào được chọn ở «Chuyển tới đâu».",
		phWaitingOn:               " Đang chờ: %s.",
		phNoSuchPlaceHere:         " Máy này không có nơi như %s — đó là của máy Mac.",
		phNowhere:                 "không đâu cả",
		phAnd:                     " và ",
		phComma:                   ", ",
		phNothingToDrawOn:         "ở đây không có chỗ nào để vẽ mã. Amenbo Viewer ở %s",
		phCodeNotDrawn:            "không vẽ được mã (%w) — Amenbo Viewer ở %s",
		phPointTheCamera:          "hướng camera điện thoại vào mã. Amenbo Viewer cũng ở %s",
		phImageNotOpened:          "không mở được ảnh (%v) — vẽ ngay tại đây thay vì vậy",
		phCodeLeftWithKey:         "mã nằm ở %s và mang theo khóa — hãy xóa ngay khi điện thoại đã đọc xong (%v).",
		phCodeLeftBehind:          "mã nằm ở %s, và không có gì được khởi động để dọn nó đi sau (%v).",
		phCodeIsOnScreen:          "mã đã hiện trên màn hình, và ảnh sẽ mất sau %d phút — hãy đọc bằng điện thoại trước lúc đó.",
		phNoScreenForTheTokenPage: "ở đây không có màn hình để mở nó. Trang token ở %s",
		phTokenPageNotOpened:      "không mở được trang token (%w) — trang đó ở %s",
		phTokenPageIsOpen:         "trang token đã mở, các quyền cần thiết đã được chọn sẵn. Bấm Continue to summary, rồi Create Token, và dán thứ hiện ra vào ô phía sau nút setup.",
		phBuildingInAccount:       "đang dựng trong tài khoản %s",
		phDatabaseCreated:         "đã tạo cơ sở dữ liệu %s",
		phDatabaseAlreadyThere:    "cơ sở dữ liệu %s đã có sẵn",
		phWorkerDeployed:          "đã triển khai Worker %s",
		phNoWorkersDevName:        "Worker đã triển khai, nhưng tài khoản này chưa có tên workers.dev để nó trả lời. Hãy chọn một tên ở %s rồi chạy lại setup",
		phTheRouteIsUp:            "tuyến Cloudflare đã dựng tại %s",
		phTheKeyWasKept:           "khóa mã hóa vốn đã có trong cài đặt được giữ nguyên, nên những điện thoại ghép bằng khóa đó vẫn đọc được.",
		phANewKeyWasGenerated:     "đã tạo khóa mã hóa mới — hãy ghép một điện thoại bằng `amenbo plugin run %s qr`.",
		phTheWorkerIsYours:        "Worker và cơ sở dữ liệu là của bạn. Gỡ plugin này vẫn để chúng nguyên chỗ cũ;\n  hãy xóa chúng trong bảng điều khiển Cloudflare khi không cần nữa.",
		phNoTokenWasPasted:        "chưa dán token nào",
		phTokenReachesNoAccount:   "token này không với tới tài khoản Cloudflare nào — có thể nó thiếu quyền Account Settings (read)",
		phWorkerHasNoWriteToken:   "Worker có trả lời nhưng chưa đặt token ghi, tức là một lần triển khai chưa hạ cánh trọn vẹn — hãy chạy lại setup",
		phEndpointNotAnsweringYet: "mọi thứ đã được tạo, nhưng endpoint vẫn chưa trả lời đúng như phải có: %w",
		phPhoneMayReadFromNowOn:   "%q được phép đọc từ bây giờ. Sau này cắt nó bằng chính cái tên đó.",
		phPhoneAlreadyPaired:      "đã có một điện thoại ghép với tên %q — hãy cắt nó bằng `%s revoke %s`, rồi ghép lại",
		phNoEncryptionKey:         "chưa đặt khóa mã hóa — hãy chạy setup",
		phNoCloudflareRouteYet:    "chưa có tuyến Cloudflare — hãy dựng một tuyến bằng `%s setup`",
		phThePhoneWasNotNamed:     "điện thoại chưa được đặt tên, mà tên chính là thứ dùng để cắt nó sau này",
	},
	"zh-Hans": {
		phICloudFolder:            "iCloud 文件夹",
		phCloudflareWorker:        "你自己的 Cloudflare Worker",
		phOpenTheAppOnce:          "在手机上打开 Amenbo Viewer (%s)",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "它已就位，但没有配置加密密钥 — 运行 setup",
		phStandingBadKey:          "它已就位，但设置里的密钥无法使用 — 重新运行 setup",
		phCarryingTo:              "正在送达: %s。",
		phCarryingNowhere:         "尚未送达任何地方。",
		phNothingIsTicked:         "尚未送达任何地方：「送到哪里」里没有勾选任何位置。",
		phWaitingOn:               "等待: %s。",
		phNoSuchPlaceHere:         "这台机器没有 %s这样的位置 — 那是 mac 才有的。",
		phNowhere:                 "任何地方",
		phAnd:                     "和",
		phComma:                   "、",
		phNothingToDrawOn:         "这里没有可以绘制二维码的地方。Amenbo Viewer 在 %s",
		phCodeNotDrawn:            "二维码无法绘制 (%w) — Amenbo Viewer 在 %s",
		phPointTheCamera:          "用手机摄像头对准二维码。Amenbo Viewer 也在 %s",
		phImageNotOpened:          "图片无法打开 (%v) — 改为在这里绘制",
		phCodeLeftWithKey:         "二维码在 %s，上面带着密钥 — 手机读取后请立即删除 (%v)。",
		phCodeLeftBehind:          "二维码在 %s，也没有启动任何东西稍后把它清掉 (%v)。",
		phCodeIsOnScreen:          "二维码已显示，图片将在 %d 分钟后消失 — 请在那之前用手机读取。",
		phNoScreenForTheTokenPage: "这里没有可以打开它的屏幕。令牌页面在 %s",
		phTokenPageNotOpened:      "令牌页面无法打开 (%w) — 它在 %s",
		phTokenPageIsOpen:         "令牌页面已打开，所需权限已经勾选。依次按 Continue to summary 和 Create Token，再把显示出来的内容粘贴到 setup 按钮后面的输入框里。",
		phBuildingInAccount:       "正在账户 %s 中搭建",
		phDatabaseCreated:         "数据库 %s 已创建",
		phDatabaseAlreadyThere:    "数据库 %s 本来就有",
		phWorkerDeployed:          "Worker %s 已部署",
		phNoWorkersDevName:        "Worker 已部署，但这个账户还没有可供它应答的 workers.dev 名称。请在 %s 选一个，然后重新运行 setup",
		phTheRouteIsUp:            "Cloudflare 路线已在 %s 就位",
		phTheKeyWasKept:           "设置里原有的加密密钥被保留，因此用它配对过的手机仍然可以读取。",
		phANewKeyWasGenerated:     "已生成新的加密密钥 — 用 `amenbo plugin run %s qr` 配对一台手机。",
		phTheWorkerIsYours:        "Worker 和数据库是你的。卸载本插件不会带走它们；\n  不需要时请在 Cloudflare 控制台删除。",
		phNoTokenWasPasted:        "没有粘贴任何令牌",
		phTokenReachesNoAccount:   "这个令牌够不到任何 Cloudflare 账户 — 可能缺少 Account Settings (read) 权限",
		phWorkerHasNoWriteToken:   "Worker 有应答，却没有设置写入令牌，这说明部署没有完全落地 — 请重新运行 setup",
		phEndpointNotAnsweringYet: "一切都已创建，但端点还没有按应有的方式应答：%w",
		phPhoneMayReadFromNowOn:   "%q 从现在起可以读取。以后要断开时，就用这个名字。",
		phPhoneAlreadyPaired:      "已经有一台手机以 %q 配对 — 用 `%s revoke %s` 断开后再重新配对",
		phNoEncryptionKey:         "没有配置加密密钥 — 请运行 setup",
		phNoCloudflareRouteYet:    "还没有 Cloudflare 路线 — 用 `%s setup` 立一条",
		phThePhoneWasNotNamed:     "这台手机没有名字，而断开时指的正是那个名字",
	},
	"zh-Hant": {
		phICloudFolder:            "iCloud 資料夾",
		phCloudflareWorker:        "你自己的 Cloudflare Worker",
		phOpenTheAppOnce:          "在手機上開啟 Amenbo Viewer (%s)",
		phStandTheWorkerUp:        "`%s setup`",
		phStandingWithNoKey:       "它已就位，但沒有設定加密金鑰 — 執行 setup",
		phStandingBadKey:          "它已就位，但設定裡的金鑰無法使用 — 重新執行 setup",
		phCarryingTo:              "正在送達: %s。",
		phCarryingNowhere:         "尚未送達任何地方。",
		phNothingIsTicked:         "尚未送達任何地方：「送到哪裡」裡沒有勾選任何位置。",
		phWaitingOn:               "等待: %s。",
		phNoSuchPlaceHere:         "這台機器沒有 %s這樣的位置 — 那是 mac 才有的。",
		phNowhere:                 "任何地方",
		phAnd:                     "和",
		phComma:                   "、",
		phNothingToDrawOn:         "這裡沒有可以繪製 QR 碼的地方。Amenbo Viewer 在 %s",
		phCodeNotDrawn:            "QR 碼無法繪製 (%w) — Amenbo Viewer 在 %s",
		phPointTheCamera:          "用手機相機對準 QR 碼。Amenbo Viewer 也在 %s",
		phImageNotOpened:          "圖片無法開啟 (%v) — 改為在這裡繪製",
		phCodeLeftWithKey:         "QR 碼在 %s，上面帶著金鑰 — 手機讀取後請立即刪除 (%v)。",
		phCodeLeftBehind:          "QR 碼在 %s，也沒有啟動任何東西稍後把它清掉 (%v)。",
		phCodeIsOnScreen:          "QR 碼已顯示，圖片將在 %d 分鐘後消失 — 請在那之前用手機讀取。",
		phNoScreenForTheTokenPage: "這裡沒有可以開啟它的螢幕。權杖頁面在 %s",
		phTokenPageNotOpened:      "權杖頁面無法開啟 (%w) — 它在 %s",
		phTokenPageIsOpen:         "權杖頁面已開啟，所需權限已經勾選。依序按 Continue to summary 和 Create Token，再把顯示出來的內容貼到 setup 按鈕後面的輸入欄裡。",
		phBuildingInAccount:       "正在帳戶 %s 中建置",
		phDatabaseCreated:         "資料庫 %s 已建立",
		phDatabaseAlreadyThere:    "資料庫 %s 本來就有",
		phWorkerDeployed:          "Worker %s 已部署",
		phNoWorkersDevName:        "Worker 已部署，但這個帳戶還沒有可供它回應的 workers.dev 名稱。請在 %s 選一個，然後重新執行 setup",
		phTheRouteIsUp:            "Cloudflare 路線已在 %s 就位",
		phTheKeyWasKept:           "設定裡原有的加密金鑰被保留，因此用它配對過的手機仍然可以讀取。",
		phANewKeyWasGenerated:     "已產生新的加密金鑰 — 用 `amenbo plugin run %s qr` 配對一台手機。",
		phTheWorkerIsYours:        "Worker 和資料庫是你的。解除安裝本外掛不會帶走它們；\n  不需要時請在 Cloudflare 主控台刪除。",
		phNoTokenWasPasted:        "沒有貼上任何權杖",
		phTokenReachesNoAccount:   "這個權杖搆不到任何 Cloudflare 帳戶 — 可能缺少 Account Settings (read) 權限",
		phWorkerHasNoWriteToken:   "Worker 有回應，卻沒有設定寫入權杖，這表示部署沒有完全落地 — 請重新執行 setup",
		phEndpointNotAnsweringYet: "一切都已建立，但端點還沒有按應有的方式回應：%w",
		phPhoneMayReadFromNowOn:   "%q 從現在起可以讀取。以後要切斷時，就用這個名字。",
		phPhoneAlreadyPaired:      "已經有一台手機以 %q 配對 — 用 `%s revoke %s` 切斷後再重新配對",
		phNoEncryptionKey:         "沒有設定加密金鑰 — 請執行 setup",
		phNoCloudflareRouteYet:    "還沒有 Cloudflare 路線 — 用 `%s setup` 立一條",
		phThePhoneWasNotNamed:     "這台手機沒有名字，而切斷時指的正是那個名字",
	},
}
