package main

// Every language this build can speak the settings face in, keyed by Amenbo's language code and
// ordered by it. All nineteen Amenbo offers are here, and the code has to be
// spelled the way the store spells it — `pt-BR` and not `pt-br` — or the row is one nothing ever
// reads.
//
// **English is the row that must be complete**, and it is the one the code was written against:
// every other row is read against it phrase by phrase, so a sentence nobody has translated yet
// arrives in English rather than blank.
//
// What is *not* translated travels through these sentences untouched: an account id, a database
// name, an endpoint, the name a person gave their phone, and the addresses — the App Store page,
// Cloudflare's dashboard. So do the commands, `viewer setup` and `viewer revoke <name>`, which
// are typed exactly as they are printed.
var wordings = map[string]wording{
	"de": {
		phCloudflareWorker:           "dein Server bei Cloudflare",
		phStandTheWorkerUp:           "drücke „%s“",
		phTheSetupButton:             "3. Server bei Cloudflare einrichten",
		phThePairButton:              "4. Telefon koppeln",
		phTheSeePhonesButton:         "5. Kopplung ansehen",
		phTheUnpairButton:            "6. Kopplung aufheben",
		phTheRepairButton:            "7. Telefonkopie reparieren",
		phRepairWillSend:             "Auf deinem Server fehlen %d Einträge, und %d liegen dort, die dieser PC nicht mehr hat. Drücke „%s“ erneut, um sie zu senden.",
		phRepairFoundNothing:         "Dein Server hat genau das, was dieser PC hat — es muss nichts erneut gesendet werden.",
		phRepairIsOnItsWay:           "%d Einträge sind auf dem Weg zu deinem Server.",
		phStandingWithNoKey:          "der Server ist da, aber es ist kein Schlüssel hinterlegt — drücke „%s“",
		phStandingBadKey:             "der Server ist da, aber der Schlüssel in den Einstellungen ist unbrauchbar — drücke „%s“ erneut",
		phCarryingTo:                 "Es wird zu %s getragen.",
		phCarryingNowhere:            "Trägt nirgendwohin.",
		phNothingIsTicked:            "Es wird nirgendwohin getragen: unter „Wohin getragen wird“ ist kein Ort angehakt.",
		phWaitingOn:                  " Fehlt: %s.",
		phNowhere:                    "nirgendwohin",
		phAnd:                        " und ",
		phComma:                      ", ",
		phCodeNotDrawn:               "der Code konnte nicht gezeichnet werden (%w) — Amenbo Viewer liegt unter %s",
		phPointTheCamera:             "richte die Kamera des Telefons auf den Code. Amenbo Viewer liegt auch unter %s",
		phReadThisWithTheCamera:      "Richte die Kamera des Telefons auf den Code.",
		phNoScreenForTheTokenPage:    "hier gibt es keinen Bildschirm, um sie zu öffnen. Die Seite für den Cloudflare-API-Token liegt unter %s",
		phTokenPageNotOpened:         "die Seite für den Cloudflare-API-Token ließ sich nicht öffnen (%w) — sie liegt unter %s",
		phTokenPageIsOpen:            "die Seite für den Cloudflare-API-Token ist offen, die nötigen Berechtigungen sind bereits angehakt. Drücke Continue to summary, dann Create Token, und füge das Angezeigte in das Feld hinter „%s“ ein.",
		phBuildingInAccount:          "wird im Konto %s aufgebaut",
		phDatabaseCreated:            "Datenbank %s angelegt",
		phDatabaseAlreadyThere:       "Datenbank %s war schon da",
		phWorkerDeployed:             "Server %s ausgeliefert",
		phNoWorkersDevName:           "der Server ist ausgeliefert, aber dieses Konto hat noch keinen workers.dev-Namen, unter dem er antworten kann. Wähle einen unter %s und drücke „%s“ erneut",
		phTheRouteIsUp:               "der Server bei Cloudflare steht unter %s",
		phTheKeyWasKept:              "der Schlüssel, der schon in den Einstellungen stand, wurde behalten — die damit gekoppelten Telefone lesen weiter.",
		phANewKeyWasGenerated:        "ein neuer Schlüssel wurde erzeugt — koppele ein Telefon mit „%s“.",
		phTheWorkerIsYours:           "der Server und die Datenbank gehören dir. Wird dieses Plugin deinstalliert, bleiben sie, wo sie sind;\n  lösche sie im Cloudflare-Dashboard, wenn du sie loswerden willst.",
		phNoTokenWasPasted:           "es wurde kein Cloudflare-API-Token eingefügt",
		phTokenReachesNoAccount:      "dieses Cloudflare-API-Token erreicht kein Konto — möglicherweise fehlt ihm die Berechtigung Account Settings (read)",
		phWorkerHasNoWriteToken:      "der Server antwortet, hat aber kein API-Token zum Schreiben gesetzt — die Auslieferung ist nicht vollständig angekommen. Drücke „%s“ erneut",
		phEndpointNotAnsweringYet:    "alles wurde angelegt, aber die URL des Servers antwortet noch nicht so, wie sie sollte: %w",
		phPairedOn:                   "Ein Telefon ist gekoppelt — seit %s.",
		phNoPhoneIsPairedYet:         "Es ist noch kein Telefon gekoppelt — drücke „%s“.",
		phNothingWasReadingAsThat:    "es hat nichts gelesen, also war auch nichts aufzuheben.",
		phPhoneReadsNothingFromNowOn: "Das Telefon liest von jetzt an nichts mehr.",
		phPhoneMayReadFromNowOn:      "Das Telefon darf von jetzt an lesen.",
		phNoEncryptionKey:            "es ist kein Schlüssel hinterlegt — drücke „%s“",
		phNoCloudflareRouteYet:       "es gibt noch keinen Server bei Cloudflare — drücke „%s“, um einen anzulegen",
	},
	"en": {
		phCloudflareWorker:   "your server on Cloudflare",
		phStandTheWorkerUp:   "press “%s”",
		phTheSetupButton:     "3. Set up the server on Cloudflare",
		phThePairButton:      "4. Pair a phone",
		phTheSeePhonesButton: "5. See whether a phone is paired",
		phTheUnpairButton:    "6. Undo the pairing",
		phTheRepairButton:    "7. Fix the phone's copy",
		phRepairWillSend:     "Your server is missing %d record(s), and holds %d that this PC no longer has. Press “%s” again to send them.",
		phRepairFoundNothing: "Your server holds exactly what this PC holds — there is nothing to send again.",
		phRepairIsOnItsWay:   "%d record(s) are on their way to your server.",
		phStandingWithNoKey:  "the server is there, but there is no encryption key — press “%s”",
		phStandingBadKey:     "the server is there, but the encryption key in the settings cannot be used — press “%s” again",
		phCarryingTo:         "Carrying to %s.",
		phCarryingNowhere:    "Carrying nowhere.",
		phNothingIsTicked:    `Carrying nowhere: no place is ticked under "Where to carry".`,
		phWaitingOn:          " Waiting on %s.",
		phNowhere:            "nowhere",
		phAnd:                " and ",
		phComma:              ", ",

		phCodeNotDrawn:          "the code could not be drawn (%w) — Amenbo Viewer is at %s",
		phPointTheCamera:        "point the phone's camera at the code. Amenbo Viewer is also at %s",
		phReadThisWithTheCamera: "Point the phone's camera at the code.",

		phNoScreenForTheTokenPage: "there is no screen here to open it on. The Cloudflare API token page is at %s",
		phTokenPageNotOpened:      "the Cloudflare API token page could not be opened (%w) — it is at %s",
		phTokenPageIsOpen:         "the Cloudflare API token page is open, with the permissions it needs already ticked. Press Continue to summary, then Create Token, and paste what it shows you into the box behind “%s”.",

		phBuildingInAccount:          "building in account %s",
		phDatabaseCreated:            "database %s created",
		phDatabaseAlreadyThere:       "database %s was already there",
		phWorkerDeployed:             "server %s deployed",
		phNoWorkersDevName:           "the server is deployed, but this account has no workers.dev name for it to answer on yet. Choose one at %s and press “%s” again",
		phTheRouteIsUp:               "the server on Cloudflare is up at %s",
		phTheKeyWasKept:              "the encryption key already in the settings was kept, so the phones paired with it still read.",
		phANewKeyWasGenerated:        "a new encryption key was generated — pair a phone with “%s”.",
		phTheWorkerIsYours:           "the server and the database are yours. Uninstalling this plugin leaves them where they are;\n  delete them in the Cloudflare dashboard when you want them gone.",
		phNoTokenWasPasted:           "no Cloudflare API token was pasted",
		phTokenReachesNoAccount:      "this Cloudflare API token reaches no account — it may be missing the Account Settings (read) permission",
		phWorkerHasNoWriteToken:      "the server is answering but has no API token for writing set, which is a deploy that did not fully land — press “%s” again",
		phEndpointNotAnsweringYet:    "everything was created, but the server's URL is not answering the way it should yet: %w",
		phPairedOn:                   "A phone is paired — since %s.",
		phNoPhoneIsPairedYet:         "No phone is paired yet — press “%s”.",
		phNothingWasReadingAsThat:    "nothing was reading, so there was nothing to undo.",
		phPhoneReadsNothingFromNowOn: "The phone reads nothing from now on.",

		phPhoneMayReadFromNowOn: "The phone may read from now on.",
		phNoEncryptionKey:       "there is no encryption key — press “%s”",
		phNoCloudflareRouteYet:  "there is no server on Cloudflare yet — press “%s” to make one",
	},
	"es": {
		phCloudflareWorker:           "tu servidor en Cloudflare",
		phStandTheWorkerUp:           "pulsa «%s»",
		phTheSetupButton:             "3. Crear el servidor en Cloudflare",
		phThePairButton:              "4. Vincular un teléfono",
		phTheSeePhonesButton:         "5. Ver si hay un teléfono",
		phTheUnpairButton:            "6. Deshacer la vinculación",
		phTheRepairButton:            "7. Reparar la copia del teléfono",
		phRepairWillSend:             "A tu servidor le faltan %d registros y tiene %d que este PC ya no tiene. Pulsa «%s» otra vez para enviarlos.",
		phRepairFoundNothing:         "Tu servidor tiene exactamente lo que tiene este PC: no hay nada que volver a enviar.",
		phRepairIsOnItsWay:           "%d registros van camino de tu servidor.",
		phStandingWithNoKey:          "el servidor está, pero no hay clave de cifrado — pulsa «%s»",
		phStandingBadKey:             "el servidor está, pero la clave de cifrado de los ajustes no sirve — vuelve a pulsar «%s»",
		phCarryingTo:                 "Llegando a %s.",
		phCarryingNowhere:            "No llega a ninguna parte.",
		phNothingIsTicked:            "No llega a ninguna parte: no hay ningún sitio marcado en «A dónde llevarlo».",
		phWaitingOn:                  " Falta: %s.",
		phNowhere:                    "ninguna parte",
		phAnd:                        " y ",
		phComma:                      ", ",
		phCodeNotDrawn:               "no se pudo dibujar el código (%w) — Amenbo Viewer está en %s",
		phPointTheCamera:             "apunta la cámara del teléfono al código. Amenbo Viewer también está en %s",
		phReadThisWithTheCamera:      "Apunta la cámara del teléfono al código.",
		phNoScreenForTheTokenPage:    "aquí no hay pantalla donde abrirla. La página del token de API de Cloudflare está en %s",
		phTokenPageNotOpened:         "no se pudo abrir la página del token de API de Cloudflare (%w) — está en %s",
		phTokenPageIsOpen:            "la página del token de API de Cloudflare está abierta, con los permisos que hacen falta ya marcados. Pulsa Continue to summary, luego Create Token, y pega lo que te muestre en la casilla que hay tras «%s».",
		phBuildingInAccount:          "construyendo en la cuenta %s",
		phDatabaseCreated:            "base de datos %s creada",
		phDatabaseAlreadyThere:       "la base de datos %s ya estaba",
		phWorkerDeployed:             "servidor %s desplegado",
		phNoWorkersDevName:           "el servidor está desplegado, pero esta cuenta aún no tiene un nombre workers.dev donde responder. Elige uno en %s y vuelve a pulsar «%s»",
		phTheRouteIsUp:               "el servidor en Cloudflare está en pie en %s",
		phTheKeyWasKept:              "se conservó la clave de cifrado que ya estaba en los ajustes, así que los teléfonos emparejados con ella siguen leyendo.",
		phANewKeyWasGenerated:        "se generó una clave de cifrado nueva — empareja un teléfono con «%s».",
		phTheWorkerIsYours:           "el servidor y la base de datos son tuyos. Desinstalar este plugin los deja donde están;\n  bórralos en el panel de Cloudflare cuando quieras deshacerte de ellos.",
		phNoTokenWasPasted:           "no se pegó ningún token de API de Cloudflare",
		phTokenReachesNoAccount:      "este token de API de Cloudflare no llega a ninguna cuenta — puede que le falte el permiso Account Settings (read)",
		phWorkerHasNoWriteToken:      "el servidor responde pero no tiene token de API para escribir, lo que es un despliegue que no llegó del todo — vuelve a pulsar «%s»",
		phEndpointNotAnsweringYet:    "se creó todo, pero la URL del servidor todavía no responde como debería: %w",
		phPairedOn:                   "Hay un teléfono vinculado — desde %s.",
		phNoPhoneIsPairedYet:         "Todavía no hay ningún teléfono vinculado — pulsa «%s».",
		phNothingWasReadingAsThat:    "nada estaba leyendo, así que no había nada que deshacer.",
		phPhoneReadsNothingFromNowOn: "El teléfono no lee nada a partir de ahora.",
		phPhoneMayReadFromNowOn:      "El teléfono puede leer desde ahora.",
		phNoEncryptionKey:            "no hay clave de cifrado — pulsa «%s»",
		phNoCloudflareRouteYet:       "todavía no hay servidor en Cloudflare — pulsa «%s» para crear uno",
	},
	"fr": {
		phCloudflareWorker:           "votre serveur sur Cloudflare",
		phStandTheWorkerUp:           "appuyez sur « %s »",
		phTheSetupButton:             "3. Créer le serveur sur Cloudflare",
		phThePairButton:              "4. Associer un téléphone",
		phTheSeePhonesButton:         "5. Voir si un téléphone est lié",
		phTheUnpairButton:            "6. Annuler l'association",
		phTheRepairButton:            "7. Réparer la copie du téléphone",
		phRepairWillSend:             "Il manque %d enregistrements sur ton serveur, et %d s'y trouvent que ce PC n'a plus. Appuie de nouveau sur « %s » pour les envoyer.",
		phRepairFoundNothing:         "Ton serveur contient exactement ce que contient ce PC — il n'y a rien à renvoyer.",
		phRepairIsOnItsWay:           "%d enregistrements sont en route vers ton serveur.",
		phStandingWithNoKey:          "le serveur est là, mais aucune clé de chiffrement n'est réglée — appuyez sur « %s »",
		phStandingBadKey:             "le serveur est là, mais la clé de chiffrement des réglages est inutilisable — appuyez de nouveau sur « %s »",
		phCarryingTo:                 "Achemine vers %s.",
		phCarryingNowhere:            "N'achemine nulle part.",
		phNothingIsTicked:            "N'achemine nulle part : aucun endroit n'est coché sous « Où acheminer ».",
		phWaitingOn:                  " Manque : %s.",
		phNowhere:                    "nulle part",
		phAnd:                        " et ",
		phComma:                      ", ",
		phCodeNotDrawn:               "le code n'a pas pu être dessiné (%w) — Amenbo Viewer est à %s",
		phPointTheCamera:             "pointez la caméra du téléphone sur le code. Amenbo Viewer est aussi à %s",
		phReadThisWithTheCamera:      "Pointez la caméra du téléphone sur le code.",
		phNoScreenForTheTokenPage:    "il n'y a pas d'écran ici pour l'ouvrir. La page du jeton d'API Cloudflare est à %s",
		phTokenPageNotOpened:         "la page du jeton d'API Cloudflare n'a pas pu être ouverte (%w) — elle est à %s",
		phTokenPageIsOpen:            "la page du jeton d'API Cloudflare est ouverte, avec les permissions nécessaires déjà cochées. Appuyez sur Continue to summary, puis Create Token, et collez ce qu'elle affiche dans le champ derrière « %s ».",
		phBuildingInAccount:          "construction dans le compte %s",
		phDatabaseCreated:            "base de données %s créée",
		phDatabaseAlreadyThere:       "la base de données %s était déjà là",
		phWorkerDeployed:             "serveur %s déployé",
		phNoWorkersDevName:           "le serveur est déployé, mais ce compte n'a pas encore de nom workers.dev pour répondre. Choisissez-en un sur %s et appuyez de nouveau sur « %s »",
		phTheRouteIsUp:               "le serveur sur Cloudflare est en place à %s",
		phTheKeyWasKept:              "la clé de chiffrement déjà présente dans les réglages a été conservée : les téléphones appairés avec elle lisent toujours.",
		phANewKeyWasGenerated:        "une nouvelle clé de chiffrement a été générée — appairez un téléphone avec « %s ».",
		phTheWorkerIsYours:           "le serveur et la base de données sont à vous. Désinstaller ce plugin les laisse où ils sont ;\n  supprimez-les dans le tableau de bord Cloudflare quand vous voudrez.",
		phNoTokenWasPasted:           "aucun jeton d'API Cloudflare n'a été collé",
		phTokenReachesNoAccount:      "ce jeton d'API Cloudflare n'atteint aucun compte — il lui manque peut-être la permission Account Settings (read)",
		phWorkerHasNoWriteToken:      "le serveur répond mais n'a pas de jeton d'API pour écrire : le déploiement n'est pas allé au bout — appuyez de nouveau sur « %s »",
		phEndpointNotAnsweringYet:    "tout a été créé, mais l'URL du serveur ne répond pas encore comme elle devrait : %w",
		phPairedOn:                   "Un téléphone est associé — depuis %s.",
		phNoPhoneIsPairedYet:         "Aucun téléphone n'est encore associé — appuyez sur « %s ».",
		phNothingWasReadingAsThat:    "rien ne lisait, il n'y avait donc rien à annuler.",
		phPhoneReadsNothingFromNowOn: "Le téléphone ne lit plus rien à partir de maintenant.",
		phPhoneMayReadFromNowOn:      "Le téléphone peut lire à partir de maintenant.",
		phNoEncryptionKey:            "aucune clé de chiffrement n'est réglée — appuyez sur « %s »",
		phNoCloudflareRouteYet:       "il n'y a pas encore de serveur sur Cloudflare — appuyez sur « %s » pour en créer un",
	},
	"hi": {
		phCloudflareWorker:           "Cloudflare पर आपका सर्वर",
		phStandTheWorkerUp:           "“%s” दबाएँ",
		phTheSetupButton:             "3. सर्वर बनाएँ",
		phThePairButton:              "4. फ़ोन जोड़ें",
		phTheSeePhonesButton:         "5. जोड़ देखें",
		phTheUnpairButton:            "6. जोड़ हटाएँ",
		phTheRepairButton:            "7. कॉपी सुधारें",
		phRepairWillSend:             "आपके सर्वर पर %d रिकॉर्ड नहीं हैं, और %d ऐसे हैं जो अब इस PC पर नहीं हैं। इन्हें भेजने के लिए “%s” फिर से दबाएँ।",
		phRepairFoundNothing:         "आपके सर्वर पर वही है जो इस PC पर है — दोबारा भेजने के लिए कुछ नहीं है।",
		phRepairIsOnItsWay:           "%d रिकॉर्ड आपके सर्वर की ओर जा रहे हैं।",
		phStandingWithNoKey:          "सर्वर बन चुका है, पर कोई एन्क्रिप्शन कुंजी नहीं है — “%s” दबाएँ",
		phStandingBadKey:             "सर्वर बन चुका है, पर सेटिंग्स की एन्क्रिप्शन कुंजी काम की नहीं — “%s” दोबारा दबाएँ",
		phCarryingTo:                 "पहुँच रहा है: %s।",
		phCarryingNowhere:            "कहीं नहीं।",
		phNothingIsTicked:            "कहीं नहीं पहुँच रहा: «कहाँ पहुँचाना है» में कोई जगह चुनी नहीं गई है।",
		phWaitingOn:                  " बाकी: %s",
		phNowhere:                    "कहीं नहीं",
		phAnd:                        " और ",
		phComma:                      ", ",
		phCodeNotDrawn:               "कोड नहीं बनाया जा सका (%w) — Amenbo Viewer %s पर है",
		phPointTheCamera:             "फ़ोन का कैमरा कोड पर रखें। Amenbo Viewer %s पर भी है",
		phReadThisWithTheCamera:      "फ़ोन का कैमरा कोड पर रखें।",
		phNoScreenForTheTokenPage:    "इसे खोलने के लिए यहाँ कोई स्क्रीन नहीं है। Cloudflare API टोकन का पृष्ठ %s पर है",
		phTokenPageNotOpened:         "Cloudflare API टोकन का पृष्ठ नहीं खोला जा सका (%w) — वह %s पर है",
		phTokenPageIsOpen:            "Cloudflare API टोकन का पृष्ठ खुला है, ज़रूरी अनुमतियाँ पहले से चुनी हुई हैं। Continue to summary दबाएँ, फिर Create Token, और जो दिखे उसे “%s” के पीछे वाले खाने में चिपकाएँ।",
		phBuildingInAccount:          "खाता %s में बनाया जा रहा है",
		phDatabaseCreated:            "डेटाबेस %s बनाया गया",
		phDatabaseAlreadyThere:       "डेटाबेस %s पहले से मौजूद था",
		phWorkerDeployed:             "सर्वर %s तैनात किया गया",
		phNoWorkersDevName:           "सर्वर तैनात हो गया, पर इस खाते के पास अभी कोई workers.dev नाम नहीं है जिस पर वह जवाब दे। %s पर एक चुनें और “%s” दोबारा दबाएँ",
		phTheRouteIsUp:               "Cloudflare पर सर्वर %s पर खड़ा है",
		phTheKeyWasKept:              "सेटिंग्स में पहले से मौजूद एन्क्रिप्शन कुंजी रखी गई, इसलिए उससे जुड़े फ़ोन पढ़ते रहेंगे।",
		phANewKeyWasGenerated:        "नई एन्क्रिप्शन कुंजी बनाई गई — “%s” से एक फ़ोन जोड़ें।",
		phTheWorkerIsYours:           "सर्वर और डेटाबेस आपके हैं। यह प्लगइन हटाने पर भी वे जहाँ हैं वहीं रहेंगे;\n  जब हटाना हो तो Cloudflare डैशबोर्ड से मिटाएँ।",
		phNoTokenWasPasted:           "कोई Cloudflare API टोकन चिपकाया नहीं गया",
		phTokenReachesNoAccount:      "यह Cloudflare API टोकन किसी खाते तक नहीं पहुँचता — शायद इसमें Account Settings (read) की अनुमति नहीं है",
		phWorkerHasNoWriteToken:      "सर्वर जवाब दे रहा है पर उसमें लिखने का API टोकन सेट नहीं है, यानी तैनाती पूरी नहीं उतरी — “%s” दोबारा दबाएँ",
		phEndpointNotAnsweringYet:    "सब कुछ बन गया, पर सर्वर का URL अभी वैसा जवाब नहीं दे रहा जैसा देना चाहिए: %w",
		phPairedOn:                   "एक फ़ोन जुड़ा है — %s से।",
		phNoPhoneIsPairedYet:         "अभी कोई फ़ोन नहीं जुड़ा है — “%s” दबाएँ।",
		phNothingWasReadingAsThat:    "कुछ भी नहीं पढ़ रहा था, इसलिए हटाने को कुछ था ही नहीं।",
		phPhoneReadsNothingFromNowOn: "फ़ोन अब से कुछ नहीं पढ़ेगा।",
		phPhoneMayReadFromNowOn:      "फ़ोन अब से पढ़ सकता है।",
		phNoEncryptionKey:            "कोई एन्क्रिप्शन कुंजी नहीं है — “%s” दबाएँ",
		phNoCloudflareRouteYet:       "अभी Cloudflare पर कोई सर्वर नहीं है — एक बनाने के लिए “%s” दबाएँ",
	},
	"id": {
		phCloudflareWorker:           "server Anda di Cloudflare",
		phStandTheWorkerUp:           "tekan “%s”",
		phTheSetupButton:             "3. Buat server di Cloudflare",
		phThePairButton:              "4. Pasangkan ponsel",
		phTheSeePhonesButton:         "5. Lihat apakah ada ponsel",
		phTheUnpairButton:            "6. Batalkan pemasangan",
		phTheRepairButton:            "7. Perbaiki salinan di ponsel",
		phRepairWillSend:             "Server Anda kekurangan %d catatan, dan menyimpan %d yang tidak lagi ada di PC ini. Tekan “%s” lagi untuk mengirimnya.",
		phRepairFoundNothing:         "Server Anda berisi persis apa yang ada di PC ini — tidak ada yang perlu dikirim ulang.",
		phRepairIsOnItsWay:           "%d catatan sedang dikirim ke server Anda.",
		phStandingWithNoKey:          "server sudah ada, tetapi belum ada kunci enkripsi — tekan “%s”",
		phStandingBadKey:             "server sudah ada, tetapi kunci enkripsi di pengaturan tidak bisa dipakai — tekan “%s” lagi",
		phCarryingTo:                 "Mengantar ke %s.",
		phCarryingNowhere:            "Belum ke mana pun.",
		phNothingIsTicked:            "Tidak mengantar ke mana pun: tidak ada tempat yang dicentang di «Ke mana mengantar».",
		phWaitingOn:                  " Menunggu: %s.",
		phNowhere:                    "ke mana pun",
		phAnd:                        " dan ",
		phComma:                      ", ",
		phCodeNotDrawn:               "kode tidak bisa digambar (%w) — Amenbo Viewer ada di %s",
		phPointTheCamera:             "arahkan kamera ponsel ke kode. Amenbo Viewer juga ada di %s",
		phReadThisWithTheCamera:      "Arahkan kamera ponsel ke kode.",
		phNoScreenForTheTokenPage:    "tidak ada layar di sini untuk membukanya. Halaman token API Cloudflare ada di %s",
		phTokenPageNotOpened:         "halaman token API Cloudflare tidak bisa dibuka (%w) — halamannya di %s",
		phTokenPageIsOpen:            "halaman token API Cloudflare sudah terbuka, dengan izin yang diperlukan sudah tercentang. Tekan Continue to summary, lalu Create Token, dan tempel yang ditampilkan ke kotak di balik “%s”.",
		phBuildingInAccount:          "membangun di akun %s",
		phDatabaseCreated:            "basis data %s dibuat",
		phDatabaseAlreadyThere:       "basis data %s sudah ada",
		phWorkerDeployed:             "server %s ditempatkan",
		phNoWorkersDevName:           "server sudah ditempatkan, tetapi akun ini belum punya nama workers.dev untuk menjawab. Pilih satu di %s lalu tekan “%s” lagi",
		phTheRouteIsUp:               "server di Cloudflare berdiri di %s",
		phTheKeyWasKept:              "kunci enkripsi yang sudah ada di pengaturan dipertahankan, jadi ponsel yang dipasangkan dengannya tetap bisa membaca.",
		phANewKeyWasGenerated:        "kunci enkripsi baru dibuat — pasangkan sebuah ponsel dengan “%s”.",
		phTheWorkerIsYours:           "server dan basis data itu milik Anda. Mencopot plugin ini tidak menghapusnya;\n  hapus lewat dasbor Cloudflare kalau sudah tidak diperlukan.",
		phNoTokenWasPasted:           "tidak ada token API Cloudflare yang ditempel",
		phTokenReachesNoAccount:      "token API Cloudflare ini tidak mencapai akun mana pun — mungkin izin Account Settings (read) belum ada",
		phWorkerHasNoWriteToken:      "server menjawab tetapi tidak punya token API untuk menulis, artinya penempatan belum mendarat sepenuhnya — tekan “%s” lagi",
		phEndpointNotAnsweringYet:    "semuanya sudah dibuat, tetapi URL server belum menjawab sebagaimana mestinya: %w",
		phPairedOn:                   "Ada ponsel yang dipasangkan — sejak %s.",
		phNoPhoneIsPairedYet:         "Belum ada ponsel yang dipasangkan — tekan “%s”.",
		phNothingWasReadingAsThat:    "tidak ada yang membaca, jadi tidak ada yang perlu dibatalkan.",
		phPhoneReadsNothingFromNowOn: "Ponsel tidak membaca apa pun mulai sekarang.",
		phPhoneMayReadFromNowOn:      "Ponsel boleh membaca mulai sekarang.",
		phNoEncryptionKey:            "belum ada kunci enkripsi — tekan “%s”",
		phNoCloudflareRouteYet:       "belum ada server di Cloudflare — tekan “%s” untuk membuatnya",
	},
	"it": {
		phCloudflareWorker:           "il tuo server su Cloudflare",
		phStandTheWorkerUp:           "premi «%s»",
		phTheSetupButton:             "3. Crea il server su Cloudflare",
		phThePairButton:              "4. Abbina un telefono",
		phTheSeePhonesButton:         "5. Vedi se c'è un telefono",
		phTheUnpairButton:            "6. Annulla l'abbinamento",
		phTheRepairButton:            "7. Riparare la copia del telefono",
		phRepairWillSend:             "Al tuo server mancano %d record e ne ha %d che questo PC non ha più. Premi di nuovo «%s» per inviarli.",
		phRepairFoundNothing:         "Il tuo server contiene esattamente ciò che contiene questo PC: non c'è nulla da inviare di nuovo.",
		phRepairIsOnItsWay:           "%d record sono in viaggio verso il tuo server.",
		phStandingWithNoKey:          "il server c'è, ma non c'è nessuna chiave di cifratura — premi «%s»",
		phStandingBadKey:             "il server c'è, ma la chiave di cifratura nelle impostazioni non è utilizzabile — premi di nuovo «%s»",
		phCarryingTo:                 "Sta arrivando a %s.",
		phCarryingNowhere:            "Non arriva da nessuna parte.",
		phNothingIsTicked:            "Non sta arrivando da nessuna parte: in «Dove portarlo» non è spuntato nessun posto.",
		phWaitingOn:                  " Manca: %s.",
		phNowhere:                    "da nessuna parte",
		phAnd:                        " e ",
		phComma:                      ", ",
		phCodeNotDrawn:               "il codice non è stato disegnato (%w) — Amenbo Viewer è su %s",
		phPointTheCamera:             "punta la fotocamera del telefono sul codice. Amenbo Viewer è anche su %s",
		phReadThisWithTheCamera:      "Punta la fotocamera del telefono sul codice.",
		phNoScreenForTheTokenPage:    "qui non c'è uno schermo su cui aprirla. La pagina del token API di Cloudflare è su %s",
		phTokenPageNotOpened:         "la pagina del token API di Cloudflare non si è aperta (%w) — è su %s",
		phTokenPageIsOpen:            "la pagina del token API di Cloudflare è aperta, con i permessi necessari già spuntati. Premi Continue to summary, poi Create Token, e incolla quello che mostra nella casella dietro «%s».",
		phBuildingInAccount:          "costruisco nell'account %s",
		phDatabaseCreated:            "database %s creato",
		phDatabaseAlreadyThere:       "il database %s c'era già",
		phWorkerDeployed:             "server %s distribuito",
		phNoWorkersDevName:           "il server è distribuito, ma questo account non ha ancora un nome workers.dev su cui rispondere. Scegline uno su %s e premi di nuovo «%s»",
		phTheRouteIsUp:               "il server su Cloudflare è in piedi su %s",
		phTheKeyWasKept:              "la chiave di cifratura già presente nelle impostazioni è stata mantenuta, quindi i telefoni accoppiati con quella continuano a leggere.",
		phANewKeyWasGenerated:        "è stata generata una nuova chiave di cifratura — accoppia un telefono con «%s».",
		phTheWorkerIsYours:           "il server e il database sono tuoi. Disinstallare questo plugin li lascia dove sono;\n  cancellali dal pannello Cloudflare quando vuoi liberartene.",
		phNoTokenWasPasted:           "non è stato incollato nessun token API di Cloudflare",
		phTokenReachesNoAccount:      "questo token API di Cloudflare non raggiunge nessun account — forse gli manca il permesso Account Settings (read)",
		phWorkerHasNoWriteToken:      "il server risponde ma non ha un token API per scrivere: è una distribuzione arrivata a metà — premi di nuovo «%s»",
		phEndpointNotAnsweringYet:    "è stato creato tutto, ma l'URL del server non risponde ancora come dovrebbe: %w",
		phPairedOn:                   "C'è un telefono abbinato — da %s.",
		phNoPhoneIsPairedYet:         "Non c'è ancora nessun telefono abbinato — premi «%s».",
		phNothingWasReadingAsThat:    "non stava leggendo nulla, quindi non c'era niente da annullare.",
		phPhoneReadsNothingFromNowOn: "Il telefono da adesso non legge più nulla.",
		phPhoneMayReadFromNowOn:      "Il telefono può leggere da adesso.",
		phNoEncryptionKey:            "non c'è nessuna chiave di cifratura — premi «%s»",
		phNoCloudflareRouteYet:       "non c'è ancora un server su Cloudflare — premi «%s» per crearne uno",
	},
	"ja": {
		phCloudflareWorker:           "Cloudflare のサーバー",
		phStandTheWorkerUp:           "「%s」を押してください",
		phTheSetupButton:             "3. Cloudflare にサーバーを作る",
		phThePairButton:              "4. 端末をペアリング",
		phTheSeePhonesButton:         "5. ペアリングを確かめる",
		phTheUnpairButton:            "6. ペアリングを解除する",
		phTheRepairButton:            "7. 端末とのずれを直す",
		phRepairWillSend:             "サーバーに %d 件が足りません。この PC にはもう無い %d 件が、サーバーに残っています。送るにはもう一度「%s」を押してください。",
		phRepairFoundNothing:         "サーバーの中身はこの PC と同じです。送り直すものはありません。",
		phRepairIsOnItsWay:           "%d 件をサーバーへ送っています。",
		phStandingWithNoKey:          "サーバーはできていますが、暗号鍵がありません —「%s」を押してください",
		phStandingBadKey:             "サーバーはできていますが、設定の暗号鍵が使えません —「%s」をもう一度押してください",
		phCarryingTo:                 "届いている先: %s。",
		phCarryingNowhere:            "どこにも届いていません。",
		phNothingIsTicked:            "どこへも送っていません:「どこへ送るか」で送り先が1つも選ばれていません。",
		phWaitingOn:                  "待ち: %s。",
		phNowhere:                    "どこにも",
		phAnd:                        "と ",
		phComma:                      "、",
		phCodeNotDrawn:               "QR コードを表示できませんでした (%w) — Amenbo Viewer は %s にあります",
		phPointTheCamera:             "端末のカメラをコードに向けてください。Amenbo Viewer は %s にもあります",
		phReadThisWithTheCamera:      "端末のカメラをコードに向けてください。",
		phNoScreenForTheTokenPage:    "ここには開く画面がありません。Cloudflare の API トークンのページは %s です",
		phTokenPageNotOpened:         "Cloudflare の API トークンのページを開けませんでした (%w) — ページは %s です",
		phTokenPageIsOpen:            "Cloudflare の API トークンのページを開きました。必要な権限は選択済みです。Continue to summary、Create Token の順に押し、表示された文字列を「%s」の入力欄に貼ってください。",
		phBuildingInAccount:          "アカウント %s に作ります",
		phDatabaseCreated:            "データベース %s を作成しました",
		phDatabaseAlreadyThere:       "データベース %s はすでにありました",
		phWorkerDeployed:             "サーバー %s をデプロイしました",
		phNoWorkersDevName:           "サーバーはデプロイできましたが、このアカウントにはまだ workers.dev の名前がありません。%s で決めてから「%s」をもう一度押してください",
		phTheRouteIsUp:               "Cloudflare のサーバーが %s で立ち上がりました",
		phTheKeyWasKept:              "設定にあった暗号鍵をそのまま使ったので、ペアリング済みの端末は引き続き読めます。",
		phANewKeyWasGenerated:        "暗号鍵を新しく作りました —「%s」で端末をペアリングしてください。",
		phTheWorkerIsYours:           "サーバーとデータベースは利用者のものです。このプラグインを削除してもそのまま残ります。\n  不要になったら Cloudflare のダッシュボードで削除してください。",
		phNoTokenWasPasted:           "Cloudflare の API トークンが貼られませんでした",
		phTokenReachesNoAccount:      "この Cloudflare の API トークンでは、どのアカウントにも接続できません — Account Settings (read) の権限が足りない可能性があります",
		phWorkerHasNoWriteToken:      "サーバーは応答していますが、書き込み用の API トークンが設定されていません。デプロイが最後まで終わっていないので、「%s」をもう一度押してください",
		phEndpointNotAnsweringYet:    "作成は済みましたが、サーバーがまだ想定どおりに応答しません: %w",
		phPairedOn:                   "端末がペアリングされています — %s から。",
		phNoPhoneIsPairedYet:         "まだ端末が1台もペアリングされていません —「%s」を押してください。",
		phNothingWasReadingAsThat:    "読んでいる端末はありませんでした。解除するものがありません。",
		phPhoneReadsNothingFromNowOn: "端末はこれから何も読めません。",
		phPhoneMayReadFromNowOn:      "端末が読めるようになりました。",
		phNoEncryptionKey:            "暗号鍵がありません —「%s」を押してください",
		phNoCloudflareRouteYet:       "Cloudflare のサーバーがまだありません —「%s」を押してください",
	},
	"ko": {
		phCloudflareWorker:           "내 Cloudflare 서버",
		phStandTheWorkerUp:           "“%s”을 누르세요",
		phTheSetupButton:             "3. Cloudflare에 서버 만들기",
		phThePairButton:              "4. 휴대폰 연결",
		phTheSeePhonesButton:         "5. 연결 상태 보기",
		phTheUnpairButton:            "6. 연결 해제",
		phTheRepairButton:            "7. 휴대폰 사본 고치기",
		phRepairWillSend:             "서버에 %d개가 없고, 이 PC에는 더 이상 없는 %d개가 남아 있습니다. 보내려면 “%s”를 다시 누르세요.",
		phRepairFoundNothing:         "서버에 있는 것이 이 PC에 있는 것과 같습니다 — 다시 보낼 것이 없습니다.",
		phRepairIsOnItsWay:           "%d개를 서버로 보내고 있습니다.",
		phStandingWithNoKey:          "서버는 있지만 암호화 키가 없습니다 — “%s”을 누르세요",
		phStandingBadKey:             "서버는 있지만 설정의 암호화 키를 쓸 수 없습니다 — “%s”을 다시 누르세요",
		phCarryingTo:                 "전달 중: %s.",
		phCarryingNowhere:            "아직 어디로도 전달되지 않습니다.",
		phNothingIsTicked:            "어디로도 전달되지 않습니다: 「어디로 보낼지」에서 선택된 곳이 없습니다.",
		phWaitingOn:                  " 대기: %s.",
		phNowhere:                    "어디로도",
		phAnd:                        " 및 ",
		phComma:                      ", ",
		phCodeNotDrawn:               "코드를 그리지 못했습니다 (%w) — Amenbo Viewer는 %s에 있습니다",
		phPointTheCamera:             "휴대폰 카메라를 코드에 맞추세요. Amenbo Viewer는 %s에도 있습니다",
		phReadThisWithTheCamera:      "휴대폰 카메라를 코드에 맞추세요.",
		phNoScreenForTheTokenPage:    "여기에는 열 화면이 없습니다. Cloudflare API 토큰 페이지는 %s입니다",
		phTokenPageNotOpened:         "Cloudflare API 토큰 페이지를 열지 못했습니다 (%w) — 페이지는 %s입니다",
		phTokenPageIsOpen:            "Cloudflare API 토큰 페이지를 열었고 필요한 권한은 이미 선택되어 있습니다. Continue to summary, Create Token 순서로 누른 뒤 표시된 값을 “%s” 뒤의 입력란에 붙여 넣으세요.",
		phBuildingInAccount:          "계정 %s에 만드는 중",
		phDatabaseCreated:            "데이터베이스 %s 생성됨",
		phDatabaseAlreadyThere:       "데이터베이스 %s은(는) 이미 있었습니다",
		phWorkerDeployed:             "서버 %s 배포됨",
		phNoWorkersDevName:           "서버는 배포되었지만 이 계정에는 아직 응답할 workers.dev 이름이 없습니다. %s에서 하나 정한 뒤 “%s”을 다시 누르세요",
		phTheRouteIsUp:               "Cloudflare 서버가 %s에 섰습니다",
		phTheKeyWasKept:              "설정에 있던 암호화 키를 그대로 두었으므로, 그 키로 짝지은 휴대폰은 계속 읽을 수 있습니다.",
		phANewKeyWasGenerated:        "새 암호화 키를 만들었습니다 — “%s”으로 휴대폰을 짝지으세요.",
		phTheWorkerIsYours:           "서버와 데이터베이스는 사용자의 것입니다. 이 플러그인을 지워도 그대로 남습니다;\n  필요 없어지면 Cloudflare 대시보드에서 삭제하세요.",
		phNoTokenWasPasted:           "Cloudflare API 토큰이 붙여 넣어지지 않았습니다",
		phTokenReachesNoAccount:      "이 Cloudflare API 토큰은 어떤 계정에도 닿지 않습니다 — Account Settings (read) 권한이 빠졌을 수 있습니다",
		phWorkerHasNoWriteToken:      "서버는 응답하지만 쓰기용 API 토큰이 설정되어 있지 않습니다. 배포가 끝까지 닿지 않았으니 “%s”을 다시 누르세요",
		phEndpointNotAnsweringYet:    "생성은 모두 끝났지만 서버의 URL이 아직 제대로 응답하지 않습니다: %w",
		phPairedOn:                   "휴대폰이 연결되어 있습니다 — %s부터.",
		phNoPhoneIsPairedYet:         "아직 연결된 휴대폰이 없습니다 — “%s”을 누르세요.",
		phNothingWasReadingAsThat:    "읽고 있는 것이 없어서 해제할 것도 없었습니다.",
		phPhoneReadsNothingFromNowOn: "휴대폰은 이제부터 아무것도 읽지 않습니다.",
		phPhoneMayReadFromNowOn:      "휴대폰이 이제부터 읽을 수 있습니다.",
		phNoEncryptionKey:            "암호화 키가 없습니다 — “%s”을 누르세요",
		phNoCloudflareRouteYet:       "아직 Cloudflare 서버가 없습니다 — “%s”을 눌러 만드세요",
	},
	"nl": {
		phCloudflareWorker:           "je eigen server op Cloudflare",
		phStandTheWorkerUp:           "druk op “%s”",
		phTheSetupButton:             "3. Server op Cloudflare aanmaken",
		phThePairButton:              "4. Telefoon koppelen",
		phTheSeePhonesButton:         "5. Kijken of er een telefoon is",
		phTheUnpairButton:            "6. Koppeling ongedaan maken",
		phTheRepairButton:            "7. Kopie op de telefoon herstellen",
		phRepairWillSend:             "Op je server ontbreken %d records, en er staan er %d die deze pc niet meer heeft. Druk opnieuw op “%s” om ze te versturen.",
		phRepairFoundNothing:         "Je server bevat precies wat deze pc bevat — er hoeft niets opnieuw verstuurd te worden.",
		phRepairIsOnItsWay:           "%d records zijn onderweg naar je server.",
		phStandingWithNoKey:          "de server staat er, maar er is geen sleutel ingesteld — druk op “%s”",
		phStandingBadKey:             "de server staat er, maar de sleutel in de instellingen is onbruikbaar — druk opnieuw op “%s”",
		phCarryingTo:                 "Gaat naar %s.",
		phCarryingNowhere:            "Gaat nergens heen.",
		phNothingIsTicked:            "Gaat nergens heen: onder «Waar het heen gaat» is geen plek aangevinkt.",
		phWaitingOn:                  " Wacht op: %s.",
		phNowhere:                    "nergens",
		phAnd:                        " en ",
		phComma:                      ", ",
		phCodeNotDrawn:               "de code kon niet getekend worden (%w) — Amenbo Viewer staat op %s",
		phPointTheCamera:             "richt de camera van de telefoon op de code. Amenbo Viewer staat ook op %s",
		phReadThisWithTheCamera:      "Richt de camera van de telefoon op de code.",
		phNoScreenForTheTokenPage:    "hier is geen scherm om hem op te openen. De pagina voor het Cloudflare-API-token staat op %s",
		phTokenPageNotOpened:         "de pagina voor het Cloudflare-API-token kon niet geopend worden (%w) — hij staat op %s",
		phTokenPageIsOpen:            "de pagina voor het Cloudflare-API-token is open, met de benodigde rechten al aangevinkt. Druk op Continue to summary, dan Create Token, en plak wat er verschijnt in het vak achter “%s”.",
		phBuildingInAccount:          "bouwen in account %s",
		phDatabaseCreated:            "database %s aangemaakt",
		phDatabaseAlreadyThere:       "database %s was er al",
		phWorkerDeployed:             "server %s uitgerold",
		phNoWorkersDevName:           "de server is uitgerold, maar dit account heeft nog geen workers.dev-naam om op te antwoorden. Kies er een op %s en druk opnieuw op “%s”",
		phTheRouteIsUp:               "de server op Cloudflare staat op %s",
		phTheKeyWasKept:              "de sleutel die al in de instellingen stond is behouden, dus de telefoons die daarmee gekoppeld zijn blijven lezen.",
		phANewKeyWasGenerated:        "er is een nieuwe sleutel gemaakt — koppel een telefoon met “%s”.",
		phTheWorkerIsYours:           "de server en de database zijn van jou. Dit plugin verwijderen laat ze staan waar ze staan;\n  verwijder ze in het Cloudflare-dashboard wanneer je ze kwijt wilt.",
		phNoTokenWasPasted:           "er is geen Cloudflare-API-token geplakt",
		phTokenReachesNoAccount:      "dit Cloudflare-API-token bereikt geen enkel account — misschien mist het de rechten Account Settings (read)",
		phWorkerHasNoWriteToken:      "de server antwoordt maar heeft geen API-token om te schrijven: een uitrol die niet helemaal geland is — druk opnieuw op “%s”",
		phEndpointNotAnsweringYet:    "alles is aangemaakt, maar de URL van de server antwoordt nog niet zoals het hoort: %w",
		phPairedOn:                   "Er is een telefoon gekoppeld — sinds %s.",
		phNoPhoneIsPairedYet:         "Er is nog geen telefoon gekoppeld — druk op “%s”.",
		phNothingWasReadingAsThat:    "er las niets, dus er was niets ongedaan te maken.",
		phPhoneReadsNothingFromNowOn: "De telefoon leest vanaf nu niets meer.",
		phPhoneMayReadFromNowOn:      "De telefoon mag vanaf nu lezen.",
		phNoEncryptionKey:            "er is geen sleutel ingesteld — druk op “%s”",
		phNoCloudflareRouteYet:       "er is nog geen server op Cloudflare — druk op “%s” om er een te maken",
	},
	"pl": {
		phCloudflareWorker:           "twój własny serwer w Cloudflare",
		phStandTheWorkerUp:           "naciśnij „%s”",
		phTheSetupButton:             "3. Utwórz serwer w Cloudflare",
		phThePairButton:              "4. Sparuj telefon",
		phTheSeePhonesButton:         "5. Sprawdź parowanie",
		phTheUnpairButton:            "6. Cofnij parowanie",
		phTheRepairButton:            "7. Napraw kopię w telefonie",
		phRepairWillSend:             "Na twoim serwerze brakuje %d rekordów, a %d leży tam mimo że ten komputer ich nie ma. Naciśnij „%s” ponownie, aby je wysłać.",
		phRepairFoundNothing:         "Twój serwer ma dokładnie to, co ten komputer — nie ma czego wysyłać ponownie.",
		phRepairIsOnItsWay:           "%d rekordów jest w drodze na twój serwer.",
		phStandingWithNoKey:          "serwer jest, ale nie ustawiono klucza szyfrowania — naciśnij „%s”",
		phStandingBadKey:             "serwer jest, ale klucza szyfrowania z ustawień nie da się użyć — naciśnij „%s” ponownie",
		phCarryingTo:                 "Trafia do %s.",
		phCarryingNowhere:            "Nie trafia nigdzie.",
		phNothingIsTicked:            "Nie trafia nigdzie: w «Dokąd wysyłać» nie zaznaczono żadnego miejsca.",
		phWaitingOn:                  " Czeka: %s.",
		phNowhere:                    "nigdzie",
		phAnd:                        " i ",
		phComma:                      ", ",
		phCodeNotDrawn:               "nie udało się narysować kodu (%w) — Amenbo Viewer jest pod %s",
		phPointTheCamera:             "skieruj aparat telefonu na kod. Amenbo Viewer jest też pod %s",
		phReadThisWithTheCamera:      "Skieruj aparat telefonu na kod.",
		phNoScreenForTheTokenPage:    "nie ma tu ekranu, na którym można by ją otworzyć. Strona tokenu API Cloudflare jest pod %s",
		phTokenPageNotOpened:         "nie udało się otworzyć strony tokenu API Cloudflare (%w) — jest pod %s",
		phTokenPageIsOpen:            "strona tokenu API Cloudflare jest otwarta, z już zaznaczonymi potrzebnymi uprawnieniami. Naciśnij Continue to summary, potem Create Token, i wklej to, co pokaże, w pole za „%s”.",
		phBuildingInAccount:          "buduję na koncie %s",
		phDatabaseCreated:            "baza danych %s utworzona",
		phDatabaseAlreadyThere:       "baza danych %s już była",
		phWorkerDeployed:             "serwer %s wdrożony",
		phNoWorkersDevName:           "serwer jest wdrożony, ale to konto nie ma jeszcze nazwy workers.dev, pod którą mógłby odpowiadać. Wybierz ją na %s i naciśnij „%s” ponownie",
		phTheRouteIsUp:               "serwer w Cloudflare stoi pod %s",
		phTheKeyWasKept:              "klucz szyfrowania, który był już w ustawieniach, został zachowany, więc sparowane nim telefony nadal czytają.",
		phANewKeyWasGenerated:        "wygenerowano nowy klucz szyfrowania — sparuj telefon przyciskiem „%s”.",
		phTheWorkerIsYours:           "serwer i baza danych są twoje. Odinstalowanie tej wtyczki zostawia je tam, gdzie są;\n  usuń je w panelu Cloudflare, kiedy będziesz chciał się ich pozbyć.",
		phNoTokenWasPasted:           "nie wklejono żadnego tokenu API Cloudflare",
		phTokenReachesNoAccount:      "ten token API Cloudflare nie sięga żadnego konta — może brakuje mu uprawnienia Account Settings (read)",
		phWorkerHasNoWriteToken:      "serwer odpowiada, ale nie ma ustawionego tokenu API do zapisu — wdrożenie nie doszło do końca. Naciśnij „%s” ponownie",
		phEndpointNotAnsweringYet:    "wszystko zostało utworzone, ale adres URL serwera jeszcze nie odpowiada tak, jak powinien: %w",
		phPairedOn:                   "Telefon jest sparowany — od %s.",
		phNoPhoneIsPairedYet:         "Żaden telefon nie jest jeszcze sparowany — naciśnij „%s”.",
		phNothingWasReadingAsThat:    "nic nie czytało, więc nie było czego cofać.",
		phPhoneReadsNothingFromNowOn: "Telefon od teraz nic nie czyta.",
		phPhoneMayReadFromNowOn:      "Telefon może od teraz czytać.",
		phNoEncryptionKey:            "nie ustawiono klucza szyfrowania — naciśnij „%s”",
		phNoCloudflareRouteYet:       "nie ma jeszcze serwera w Cloudflare — naciśnij „%s”, aby go utworzyć",
	},
	"pt-BR": {
		phCloudflareWorker:           "o seu servidor no Cloudflare",
		phStandTheWorkerUp:           "pressione “%s”",
		phTheSetupButton:             "3. Criar o servidor no Cloudflare",
		phThePairButton:              "4. Parear um telefone",
		phTheSeePhonesButton:         "5. Ver se há um celular pareado",
		phTheUnpairButton:            "6. Desfazer o pareamento",
		phTheRepairButton:            "7. Reparar a cópia do telefone",
		phRepairWillSend:             "Faltam %d registros no seu servidor, e há %d lá que este PC não tem mais. Pressione “%s” de novo para enviá-los.",
		phRepairFoundNothing:         "Seu servidor tem exatamente o que este PC tem — não há nada para enviar de novo.",
		phRepairIsOnItsWay:           "%d registros estão a caminho do seu servidor.",
		phStandingWithNoKey:          "o servidor está lá, mas não há chave de criptografia — pressione “%s”",
		phStandingBadKey:             "o servidor está lá, mas a chave de criptografia das configurações não serve — pressione “%s” de novo",
		phCarryingTo:                 "Chegando a %s.",
		phCarryingNowhere:            "Não chega a lugar nenhum.",
		phNothingIsTicked:            "Não chega a lugar nenhum: nenhum lugar está marcado em «Para onde levar».",
		phWaitingOn:                  " Falta: %s.",
		phNowhere:                    "lugar nenhum",
		phAnd:                        " e ",
		phComma:                      ", ",
		phCodeNotDrawn:               "o código não pôde ser desenhado (%w) — o Amenbo Viewer está em %s",
		phPointTheCamera:             "aponte a câmera do celular para o código. O Amenbo Viewer também está em %s",
		phReadThisWithTheCamera:      "Aponte a câmera do celular para o código.",
		phNoScreenForTheTokenPage:    "aqui não há tela para abri-la. A página do token de API do Cloudflare está em %s",
		phTokenPageNotOpened:         "a página do token de API do Cloudflare não pôde ser aberta (%w) — ela está em %s",
		phTokenPageIsOpen:            "a página do token de API do Cloudflare está aberta, com as permissões necessárias já marcadas. Pressione Continue to summary, depois Create Token, e cole o que aparecer na caixa atrás de “%s”.",
		phBuildingInAccount:          "construindo na conta %s",
		phDatabaseCreated:            "banco de dados %s criado",
		phDatabaseAlreadyThere:       "o banco de dados %s já existia",
		phWorkerDeployed:             "servidor %s implantado",
		phNoWorkersDevName:           "o servidor foi implantado, mas esta conta ainda não tem um nome workers.dev para responder. Escolha um em %s e pressione “%s” de novo",
		phTheRouteIsUp:               "o servidor no Cloudflare está de pé em %s",
		phTheKeyWasKept:              "a chave de criptografia que já estava nas configurações foi mantida, então os celulares pareados com ela continuam lendo.",
		phANewKeyWasGenerated:        "uma nova chave de criptografia foi gerada — pareie um celular com “%s”.",
		phTheWorkerIsYours:           "o servidor e o banco de dados são seus. Desinstalar este plugin os deixa onde estão;\n  apague-os no painel do Cloudflare quando quiser se livrar deles.",
		phNoTokenWasPasted:           "nenhum token de API do Cloudflare foi colado",
		phTokenReachesNoAccount:      "este token de API do Cloudflare não alcança nenhuma conta — pode estar faltando a permissão Account Settings (read)",
		phWorkerHasNoWriteToken:      "o servidor responde mas não tem token de API para escrever, o que é uma implantação que não chegou até o fim — pressione “%s” de novo",
		phEndpointNotAnsweringYet:    "tudo foi criado, mas a URL do servidor ainda não responde como deveria: %w",
		phPairedOn:                   "Há um celular pareado — desde %s.",
		phNoPhoneIsPairedYet:         "Nenhum celular foi pareado ainda — pressione “%s”.",
		phNothingWasReadingAsThat:    "nada estava lendo, então não havia o que desfazer.",
		phPhoneReadsNothingFromNowOn: "O celular não lê mais nada a partir de agora.",
		phPhoneMayReadFromNowOn:      "O celular pode ler daqui em diante.",
		phNoEncryptionKey:            "não há chave de criptografia — pressione “%s”",
		phNoCloudflareRouteYet:       "ainda não há servidor no Cloudflare — pressione “%s” para criar um",
	},
	"ru": {
		phCloudflareWorker:           "ваш сервер в Cloudflare",
		phStandTheWorkerUp:           "нажмите «%s»",
		phTheSetupButton:             "3. Создать сервер",
		phThePairButton:              "4. Подключить телефон",
		phTheSeePhonesButton:         "5. Есть ли подключение",
		phTheUnpairButton:            "6. Отключить телефон",
		phTheRepairButton:            "7. Починить копию",
		phRepairWillSend:             "На вашем сервере не хватает %d записей, и там есть %d, которых на этом ПК уже нет. Нажмите «%s» ещё раз, чтобы отправить их.",
		phRepairFoundNothing:         "На сервере ровно то же, что и на этом ПК — отправлять заново нечего.",
		phRepairIsOnItsWay:           "%d записей отправляются на ваш сервер.",
		phStandingWithNoKey:          "сервер есть, но ключ шифрования не задан — нажмите «%s»",
		phStandingBadKey:             "сервер есть, но ключом шифрования из настроек нельзя пользоваться — нажмите «%s» ещё раз",
		phCarryingTo:                 "Доставляется: %s.",
		phCarryingNowhere:            "Пока никуда.",
		phNothingIsTicked:            "Никуда не доставляется: в «Куда доставлять» не отмечено ни одного места.",
		phWaitingOn:                  " Ждём: %s.",
		phNowhere:                    "никуда",
		phAnd:                        " и ",
		phComma:                      ", ",
		phCodeNotDrawn:               "код не удалось нарисовать (%w) — Amenbo Viewer находится по адресу %s",
		phPointTheCamera:             "наведите камеру телефона на код. Amenbo Viewer есть и по адресу %s",
		phReadThisWithTheCamera:      "Наведите камеру телефона на код.",
		phNoScreenForTheTokenPage:    "здесь нет экрана, чтобы её открыть. Страница API-токена Cloudflare — %s",
		phTokenPageNotOpened:         "страницу API-токена Cloudflare не удалось открыть (%w) — она находится по адресу %s",
		phTokenPageIsOpen:            "страница API-токена Cloudflare открыта, нужные разрешения уже отмечены. Нажмите Continue to summary, затем Create Token и вставьте показанное в поле за «%s».",
		phBuildingInAccount:          "строим в аккаунте %s",
		phDatabaseCreated:            "база данных %s создана",
		phDatabaseAlreadyThere:       "база данных %s уже была",
		phWorkerDeployed:             "сервер %s развёрнут",
		phNoWorkersDevName:           "сервер развёрнут, но у этого аккаунта пока нет имени workers.dev, на котором он мог бы отвечать. Выберите его на %s и нажмите «%s» ещё раз",
		phTheRouteIsUp:               "сервер в Cloudflare поднят на %s",
		phTheKeyWasKept:              "ключ шифрования, который уже был в настройках, сохранён, поэтому связанные с ним телефоны продолжают читать.",
		phANewKeyWasGenerated:        "создан новый ключ шифрования — свяжите телефон кнопкой «%s».",
		phTheWorkerIsYours:           "сервер и база данных — ваши. Удаление этого плагина оставляет их на месте;\n  удалите их в панели Cloudflare, когда они станут не нужны.",
		phNoTokenWasPasted:           "API-токен Cloudflare не вставлен",
		phTokenReachesNoAccount:      "этот API-токен Cloudflare не достаёт ни до одного аккаунта — возможно, ему не хватает разрешения Account Settings (read)",
		phWorkerHasNoWriteToken:      "сервер отвечает, но у него не задан API-токен для записи — развёртывание дошло не до конца. Нажмите «%s» ещё раз",
		phEndpointNotAnsweringYet:    "всё создано, но URL сервера пока отвечает не так, как должен: %w",
		phPairedOn:                   "Телефон подключён — с %s.",
		phNoPhoneIsPairedYet:         "Ни один телефон ещё не подключён — нажмите «%s».",
		phNothingWasReadingAsThat:    "ничего не читало, поэтому и отменять было нечего.",
		phPhoneReadsNothingFromNowOn: "Телефон с этого момента ничего не читает.",
		phPhoneMayReadFromNowOn:      "Телефон может читать с этого момента.",
		phNoEncryptionKey:            "ключ шифрования не задан — нажмите «%s»",
		phNoCloudflareRouteYet:       "сервера в Cloudflare пока нет — нажмите «%s», чтобы создать его",
	},
	"th": {
		phCloudflareWorker:           "เซิร์ฟเวอร์บน Cloudflare",
		phStandTheWorkerUp:           "กด “%s”",
		phTheSetupButton:             "3. เซิร์ฟเวอร์",
		phThePairButton:              "4. จับคู่มือถือ",
		phTheSeePhonesButton:         "5. ดูการจับคู่",
		phTheUnpairButton:            "6. เลิกจับคู่",
		phTheRepairButton:            "7. ซ่อมข้อมูล",
		phRepairWillSend:             "เซิร์ฟเวอร์ของคุณขาดอยู่ %d รายการ และมี %d รายการที่พีซีเครื่องนี้ไม่มีแล้ว กด “%s” อีกครั้งเพื่อส่ง",
		phRepairFoundNothing:         "เซิร์ฟเวอร์ของคุณมีเหมือนกับพีซีเครื่องนี้ทุกอย่าง ไม่มีอะไรต้องส่งใหม่",
		phRepairIsOnItsWay:           "กำลังส่ง %d รายการไปยังเซิร์ฟเวอร์ของคุณ",
		phStandingWithNoKey:          "เซิร์ฟเวอร์มีแล้ว แต่ยังไม่มีกุญแจเข้ารหัส — กด “%s”",
		phStandingBadKey:             "เซิร์ฟเวอร์มีแล้ว แต่กุญแจเข้ารหัสในการตั้งค่าใช้ไม่ได้ — กด “%s” อีกครั้ง",
		phCarryingTo:                 "ส่งไปที่: %s",
		phCarryingNowhere:            "ยังไม่ส่งไปไหน",
		phNothingIsTicked:            "ยังไม่ได้ส่งไปที่ใดเลย: ไม่มีที่ใดถูกเลือกใน «จะส่งไปที่ไหน»",
		phWaitingOn:                  " รอ: %s",
		phNowhere:                    "ไม่มีที่ใด",
		phAnd:                        " และ ",
		phComma:                      ", ",
		phCodeNotDrawn:               "วาดรหัสไม่ได้ (%w) — Amenbo Viewer อยู่ที่ %s",
		phPointTheCamera:             "เล็งกล้องของโทรศัพท์ไปที่รหัส Amenbo Viewer อยู่ที่ %s ด้วย",
		phReadThisWithTheCamera:      "เล็งกล้องของโทรศัพท์ไปที่รหัส",
		phNoScreenForTheTokenPage:    "ที่นี่ไม่มีหน้าจอให้เปิด หน้า API โทเคนของ Cloudflare อยู่ที่ %s",
		phTokenPageNotOpened:         "เปิดหน้า API โทเคนของ Cloudflare ไม่ได้ (%w) — หน้านั้นอยู่ที่ %s",
		phTokenPageIsOpen:            "เปิดหน้า API โทเคนของ Cloudflare แล้ว โดยเลือกสิทธิ์ที่ต้องใช้ไว้ให้เรียบร้อย กด Continue to summary แล้วกด Create Token จากนั้นวางสิ่งที่แสดงลงในช่องหลัง “%s”",
		phBuildingInAccount:          "กำลังสร้างในบัญชี %s",
		phDatabaseCreated:            "สร้างฐานข้อมูล %s แล้ว",
		phDatabaseAlreadyThere:       "ฐานข้อมูล %s มีอยู่แล้ว",
		phWorkerDeployed:             "ปล่อยเซิร์ฟเวอร์ %s แล้ว",
		phNoWorkersDevName:           "ปล่อยเซิร์ฟเวอร์แล้ว แต่บัญชีนี้ยังไม่มีชื่อ workers.dev ให้ตอบ เลือกสักชื่อที่ %s แล้วกด “%s” อีกครั้ง",
		phTheRouteIsUp:               "เซิร์ฟเวอร์บน Cloudflare ตั้งขึ้นแล้วที่ %s",
		phTheKeyWasKept:              "กุญแจเข้ารหัสที่มีอยู่ในการตั้งค่าถูกเก็บไว้ตามเดิม โทรศัพท์ที่จับคู่ด้วยกุญแจนั้นจึงอ่านได้ต่อไป",
		phANewKeyWasGenerated:        "สร้างกุญแจเข้ารหัสใหม่แล้ว — จับคู่โทรศัพท์ด้วย “%s”",
		phTheWorkerIsYours:           "เซิร์ฟเวอร์และฐานข้อมูลเป็นของคุณ ถอนปลั๊กอินนี้ออกก็ยังอยู่ที่เดิม\n  ลบได้ที่แดชบอร์ดของ Cloudflare เมื่อไม่ต้องการแล้ว",
		phNoTokenWasPasted:           "ไม่ได้วาง API โทเคนของ Cloudflare",
		phTokenReachesNoAccount:      "API โทเคนของ Cloudflare นี้ไปไม่ถึงบัญชีใดเลย — อาจขาดสิทธิ์ Account Settings (read)",
		phWorkerHasNoWriteToken:      "เซิร์ฟเวอร์ตอบอยู่ แต่ยังไม่ได้ตั้ง API โทเคนสำหรับเขียน แปลว่าการปล่อยยังลงไม่ครบ — กด “%s” อีกครั้ง",
		phEndpointNotAnsweringYet:    "สร้างครบแล้ว แต่ URL ของเซิร์ฟเวอร์ยังตอบไม่ถูกต้องอย่างที่ควรเป็น: %w",
		phPairedOn:                   "มีมือถือจับคู่อยู่ — ตั้งแต่ %s",
		phNoPhoneIsPairedYet:         "ยังไม่มีมือถือที่จับคู่ไว้ — กด “%s”",
		phNothingWasReadingAsThat:    "ไม่มีอะไรกำลังอ่านอยู่ จึงไม่มีอะไรให้ยกเลิก",
		phPhoneReadsNothingFromNowOn: "มือถือจะไม่อ่านอะไรอีกต่อไป",
		phPhoneMayReadFromNowOn:      "มือถืออ่านได้ตั้งแต่นี้ไป",
		phNoEncryptionKey:            "ยังไม่มีกุญแจเข้ารหัส — กด “%s”",
		phNoCloudflareRouteYet:       "ยังไม่มีเซิร์ฟเวอร์บน Cloudflare — กด “%s” เพื่อสร้าง",
	},
	"tr": {
		phCloudflareWorker:           "Cloudflare'deki kendi sunucun",
		phStandTheWorkerUp:           "“%s” düğmesine bas",
		phTheSetupButton:             "3. Cloudflare'de sunucu oluştur",
		phThePairButton:              "4. Telefon eşle",
		phTheSeePhonesButton:         "5. Eşleşme var mı gör",
		phTheUnpairButton:            "6. Eşleşmeyi geri al",
		phTheRepairButton:            "7. Telefondaki kopyayı onar",
		phRepairWillSend:             "Sunucunda %d kayıt eksik ve bu bilgisayarda artık olmayan %d kayıt orada duruyor. Göndermek için “%s” düğmesine yeniden bas.",
		phRepairFoundNothing:         "Sunucunda tam olarak bu bilgisayardakiler var — yeniden gönderilecek bir şey yok.",
		phRepairIsOnItsWay:           "%d kayıt sunucuna gidiyor.",
		phStandingWithNoKey:          "sunucu var, ama şifreleme anahtarı yok — “%s” düğmesine bas",
		phStandingBadKey:             "sunucu var, ama ayarlardaki şifreleme anahtarı kullanılamıyor — “%s” düğmesine yeniden bas",
		phCarryingTo:                 "%s adresine ulaşıyor.",
		phCarryingNowhere:            "Hiçbir yere ulaşmıyor.",
		phNothingIsTicked:            "Hiçbir yere ulaşmıyor: «Nereye taşınacak» altında hiçbir yer işaretli değil.",
		phWaitingOn:                  " Bekleyen: %s.",
		phNowhere:                    "hiçbir yer",
		phAnd:                        " ve ",
		phComma:                      ", ",
		phCodeNotDrawn:               "kod çizilemedi (%w) — Amenbo Viewer %s adresinde",
		phPointTheCamera:             "telefonun kamerasını koda tut. Amenbo Viewer ayrıca %s adresinde",
		phReadThisWithTheCamera:      "Telefonun kamerasını koda tut.",
		phNoScreenForTheTokenPage:    "burada açacak bir ekran yok. Cloudflare API belirteci sayfası %s adresinde",
		phTokenPageNotOpened:         "Cloudflare API belirteci sayfası açılamadı (%w) — sayfa %s adresinde",
		phTokenPageIsOpen:            "Cloudflare API belirteci sayfası açık, gereken izinler önceden işaretli. Continue to summary'ye, sonra Create Token'a bas ve gösterdiğini “%s” düğmesinin arkasındaki kutuya yapıştır.",
		phBuildingInAccount:          "%s hesabında kuruluyor",
		phDatabaseCreated:            "%s veritabanı oluşturuldu",
		phDatabaseAlreadyThere:       "%s veritabanı zaten vardı",
		phWorkerDeployed:             "sunucu %s dağıtıldı",
		phNoWorkersDevName:           "sunucu dağıtıldı, ama bu hesabın henüz yanıt vereceği bir workers.dev adı yok. %s adresinden bir tane seç ve “%s” düğmesine yeniden bas",
		phTheRouteIsUp:               "Cloudflare'deki sunucu %s adresinde ayakta",
		phTheKeyWasKept:              "ayarlarda hâlihazırda duran şifreleme anahtarı korundu, onunla eşleştirilmiş telefonlar okumaya devam ediyor.",
		phANewKeyWasGenerated:        "yeni bir şifreleme anahtarı üretildi — “%s” ile bir telefon eşleştir.",
		phTheWorkerIsYours:           "sunucu ve veritabanı senin. Bu eklentiyi kaldırmak onları yerinde bırakır;\n  istemediğinde Cloudflare panosundan sil.",
		phNoTokenWasPasted:           "hiçbir Cloudflare API belirteci yapıştırılmadı",
		phTokenReachesNoAccount:      "bu Cloudflare API belirteci hiçbir hesaba ulaşmıyor — Account Settings (read) izni eksik olabilir",
		phWorkerHasNoWriteToken:      "sunucu yanıt veriyor ama yazma için API belirteci ayarlı değil; bu, sonuna kadar inmemiş bir dağıtımdır — “%s” düğmesine yeniden bas",
		phEndpointNotAnsweringYet:    "her şey oluşturuldu, ama sunucunun URL'si henüz olması gerektiği gibi yanıt vermiyor: %w",
		phPairedOn:                   "Eşleşmiş bir telefon var — %s tarihinden beri.",
		phNoPhoneIsPairedYet:         "Henüz eşleşmiş bir telefon yok — “%s” düğmesine bas.",
		phNothingWasReadingAsThat:    "hiçbir şey okumuyordu, geri alınacak bir şey de yoktu.",
		phPhoneReadsNothingFromNowOn: "Telefon bundan sonra hiçbir şey okumaz.",
		phPhoneMayReadFromNowOn:      "Telefon artık okuyabilir.",
		phNoEncryptionKey:            "şifreleme anahtarı yok — “%s” düğmesine bas",
		phNoCloudflareRouteYet:       "henüz Cloudflare'de bir sunucu yok — bir tane oluşturmak için “%s” düğmesine bas",
	},
	"uk": {
		phCloudflareWorker:           "ваш сервер у Cloudflare",
		phStandTheWorkerUp:           "натисніть «%s»",
		phTheSetupButton:             "3. Створити сервер",
		phThePairButton:              "4. Підключити телефон",
		phTheSeePhonesButton:         "5. Чи є підключення",
		phTheUnpairButton:            "6. Відключити телефон",
		phTheRepairButton:            "7. Полагодити копію",
		phRepairWillSend:             "На вашому сервері бракує %d записів, і там є %d, яких на цьому ПК уже немає. Натисніть «%s» ще раз, щоб надіслати їх.",
		phRepairFoundNothing:         "На сервері рівно те саме, що й на цьому ПК — надсилати заново нічого.",
		phRepairIsOnItsWay:           "%d записів прямують на ваш сервер.",
		phStandingWithNoKey:          "сервер є, але ключ шифрування не задано — натисніть «%s»",
		phStandingBadKey:             "сервер є, але ключем шифрування з налаштувань не можна скористатися — натисніть «%s» ще раз",
		phCarryingTo:                 "Доставляється: %s.",
		phCarryingNowhere:            "Поки нікуди.",
		phNothingIsTicked:            "Нікуди не доставляється: у «Куди доставляти» не позначено жодного місця.",
		phWaitingOn:                  " Чекаємо: %s.",
		phNowhere:                    "нікуди",
		phAnd:                        " і ",
		phComma:                      ", ",
		phCodeNotDrawn:               "код не вдалося намалювати (%w) — Amenbo Viewer за адресою %s",
		phPointTheCamera:             "наведіть камеру телефона на код. Amenbo Viewer є й за адресою %s",
		phReadThisWithTheCamera:      "Наведіть камеру телефона на код.",
		phNoScreenForTheTokenPage:    "тут немає екрана, щоб її відкрити. Сторінка API-токена Cloudflare — %s",
		phTokenPageNotOpened:         "сторінку API-токена Cloudflare не вдалося відкрити (%w) — вона за адресою %s",
		phTokenPageIsOpen:            "сторінку API-токена Cloudflare відкрито, потрібні дозволи вже позначено. Натисніть Continue to summary, потім Create Token і вставте показане в поле за «%s».",
		phBuildingInAccount:          "будуємо в обліковому записі %s",
		phDatabaseCreated:            "базу даних %s створено",
		phDatabaseAlreadyThere:       "база даних %s уже була",
		phWorkerDeployed:             "сервер %s розгорнуто",
		phNoWorkersDevName:           "сервер розгорнуто, але цей обліковий запис ще не має імені workers.dev, на якому він відповідав би. Оберіть його на %s і натисніть «%s» ще раз",
		phTheRouteIsUp:               "сервер у Cloudflare піднято на %s",
		phTheKeyWasKept:              "ключ шифрування, який уже був у налаштуваннях, збережено, тож пов'язані з ним телефони читають далі.",
		phANewKeyWasGenerated:        "створено новий ключ шифрування — пов'яжіть телефон кнопкою «%s».",
		phTheWorkerIsYours:           "сервер і база даних — ваші. Видалення цього плагіна залишає їх на місці;\n  видаліть їх у панелі Cloudflare, коли вони стануть непотрібні.",
		phNoTokenWasPasted:           "API-токен Cloudflare не вставлено",
		phTokenReachesNoAccount:      "цей API-токен Cloudflare не дістає до жодного облікового запису — можливо, йому бракує дозволу Account Settings (read)",
		phWorkerHasNoWriteToken:      "сервер відповідає, але не має API-токена для запису — розгортання дійшло не до кінця. Натисніть «%s» ще раз",
		phEndpointNotAnsweringYet:    "усе створено, але URL сервера ще відповідає не так, як мав би: %w",
		phPairedOn:                   "Телефон підключено — з %s.",
		phNoPhoneIsPairedYet:         "Жоден телефон ще не підключено — натисніть «%s».",
		phNothingWasReadingAsThat:    "нічого не читало, тому й скасовувати не було чого.",
		phPhoneReadsNothingFromNowOn: "Телефон відтепер нічого не читає.",
		phPhoneMayReadFromNowOn:      "Телефон може читати відтепер.",
		phNoEncryptionKey:            "ключ шифрування не задано — натисніть «%s»",
		phNoCloudflareRouteYet:       "сервера в Cloudflare ще немає — натисніть «%s», щоб створити його",
	},
	"vi": {
		phCloudflareWorker:           "máy chủ của bạn trên Cloudflare",
		phStandTheWorkerUp:           "bấm “%s”",
		phTheSetupButton:             "3. Tạo máy chủ trên Cloudflare",
		phThePairButton:              "4. Ghép nối điện thoại",
		phTheSeePhonesButton:         "5. Xem đã ghép nối chưa",
		phTheUnpairButton:            "6. Hủy ghép nối",
		phTheRepairButton:            "7. Sửa bản sao",
		phRepairWillSend:             "Máy chủ của bạn thiếu %d bản ghi, và có %d bản ghi mà PC này không còn. Nhấn “%s” lần nữa để gửi chúng.",
		phRepairFoundNothing:         "Máy chủ của bạn có đúng những gì PC này có — không có gì cần gửi lại.",
		phRepairIsOnItsWay:           "%d bản ghi đang trên đường tới máy chủ của bạn.",
		phStandingWithNoKey:          "máy chủ đã có, nhưng chưa có khóa mã hóa — bấm “%s”",
		phStandingBadKey:             "máy chủ đã có, nhưng khóa mã hóa trong cài đặt không dùng được — bấm lại “%s”",
		phCarryingTo:                 "Đang chuyển tới %s.",
		phCarryingNowhere:            "Chưa tới đâu cả.",
		phNothingIsTicked:            "Chưa chuyển tới đâu cả: không có nơi nào được chọn ở «Chuyển tới đâu».",
		phWaitingOn:                  " Đang chờ: %s.",
		phNowhere:                    "không đâu cả",
		phAnd:                        " và ",
		phComma:                      ", ",
		phCodeNotDrawn:               "không vẽ được mã (%w) — Amenbo Viewer ở %s",
		phPointTheCamera:             "hướng camera điện thoại vào mã. Amenbo Viewer cũng ở %s",
		phReadThisWithTheCamera:      "Hướng camera điện thoại vào mã.",
		phNoScreenForTheTokenPage:    "ở đây không có màn hình để mở nó. Trang API token của Cloudflare ở %s",
		phTokenPageNotOpened:         "không mở được trang API token của Cloudflare (%w) — trang đó ở %s",
		phTokenPageIsOpen:            "trang API token của Cloudflare đã mở, các quyền cần thiết đã được chọn sẵn. Bấm Continue to summary, rồi Create Token, và dán thứ hiện ra vào ô phía sau “%s”.",
		phBuildingInAccount:          "đang dựng trong tài khoản %s",
		phDatabaseCreated:            "đã tạo cơ sở dữ liệu %s",
		phDatabaseAlreadyThere:       "cơ sở dữ liệu %s đã có sẵn",
		phWorkerDeployed:             "đã triển khai máy chủ %s",
		phNoWorkersDevName:           "máy chủ đã triển khai, nhưng tài khoản này chưa có tên workers.dev để nó trả lời. Hãy chọn một tên ở %s rồi bấm lại “%s”",
		phTheRouteIsUp:               "máy chủ trên Cloudflare đã dựng tại %s",
		phTheKeyWasKept:              "khóa mã hóa vốn đã có trong cài đặt được giữ nguyên, nên những điện thoại ghép bằng khóa đó vẫn đọc được.",
		phANewKeyWasGenerated:        "đã tạo khóa mã hóa mới — hãy ghép một điện thoại bằng “%s”.",
		phTheWorkerIsYours:           "máy chủ và cơ sở dữ liệu là của bạn. Gỡ plugin này vẫn để chúng nguyên chỗ cũ;\n  hãy xóa chúng trong bảng điều khiển Cloudflare khi không cần nữa.",
		phNoTokenWasPasted:           "chưa dán API token nào của Cloudflare",
		phTokenReachesNoAccount:      "API token này của Cloudflare không với tới tài khoản nào — có thể nó thiếu quyền Account Settings (read)",
		phWorkerHasNoWriteToken:      "máy chủ có trả lời nhưng chưa đặt API token để ghi, tức là một lần triển khai chưa hạ cánh trọn vẹn — hãy bấm lại “%s”",
		phEndpointNotAnsweringYet:    "mọi thứ đã được tạo, nhưng URL của máy chủ vẫn chưa trả lời đúng như phải có: %w",
		phPairedOn:                   "Có một điện thoại đã ghép nối — từ %s.",
		phNoPhoneIsPairedYet:         "Chưa có điện thoại nào được ghép nối — bấm “%s”.",
		phNothingWasReadingAsThat:    "không có gì đang đọc, nên cũng không có gì để hủy.",
		phPhoneReadsNothingFromNowOn: "Điện thoại từ giờ không đọc gì nữa.",
		phPhoneMayReadFromNowOn:      "Điện thoại được phép đọc từ bây giờ.",
		phNoEncryptionKey:            "chưa có khóa mã hóa — bấm “%s”",
		phNoCloudflareRouteYet:       "chưa có máy chủ trên Cloudflare — hãy bấm “%s” để tạo một máy chủ",
	},
	"zh-Hans": {
		phCloudflareWorker:           "你自己在 Cloudflare 上的服务器",
		phStandTheWorkerUp:           "按“%s”",
		phTheSetupButton:             "3. 在 Cloudflare 上创建服务器",
		phThePairButton:              "4. 配对手机",
		phTheSeePhonesButton:         "5. 查看配对状态",
		phTheUnpairButton:            "6. 解除配对",
		phTheRepairButton:            "7. 修复手机上的副本",
		phRepairWillSend:             "你的服务器缺少 %d 条记录，还有 %d 条是这台电脑已经没有的。再按一次“%s”即可发送。",
		phRepairFoundNothing:         "你的服务器与这台电脑完全一致，没有需要重新发送的内容。",
		phRepairIsOnItsWay:           "%d 条记录正在发往你的服务器。",
		phStandingWithNoKey:          "服务器已经有了，但没有加密密钥 — 按“%s”",
		phStandingBadKey:             "服务器已经有了，但设置里的加密密钥无法使用 — 重新按“%s”",
		phCarryingTo:                 "正在送达: %s。",
		phCarryingNowhere:            "尚未送达任何地方。",
		phNothingIsTicked:            "尚未送达任何地方：「送到哪里」里没有勾选任何位置。",
		phWaitingOn:                  "等待: %s。",
		phNowhere:                    "任何地方",
		phAnd:                        "和",
		phComma:                      "、",
		phCodeNotDrawn:               "二维码无法绘制 (%w) — Amenbo Viewer 在 %s",
		phPointTheCamera:             "用手机摄像头对准二维码。Amenbo Viewer 也在 %s",
		phReadThisWithTheCamera:      "用手机摄像头对准二维码。",
		phNoScreenForTheTokenPage:    "这里没有可以打开它的屏幕。Cloudflare API 令牌页面在 %s",
		phTokenPageNotOpened:         "Cloudflare API 令牌页面无法打开 (%w) — 它在 %s",
		phTokenPageIsOpen:            "Cloudflare API 令牌页面已打开，所需权限已经勾选。依次按 Continue to summary 和 Create Token，再把显示出来的内容粘贴到“%s”后面的输入框里。",
		phBuildingInAccount:          "正在账户 %s 中搭建",
		phDatabaseCreated:            "数据库 %s 已创建",
		phDatabaseAlreadyThere:       "数据库 %s 本来就有",
		phWorkerDeployed:             "服务器 %s 已部署",
		phNoWorkersDevName:           "服务器已部署，但这个账户还没有可供它应答的 workers.dev 名称。请在 %s 选一个，然后重新按“%s”",
		phTheRouteIsUp:               "Cloudflare 上的服务器已在 %s 就位",
		phTheKeyWasKept:              "设置里原有的加密密钥被保留，因此用它配对过的手机仍然可以读取。",
		phANewKeyWasGenerated:        "已生成新的加密密钥 — 用“%s”配对一台手机。",
		phTheWorkerIsYours:           "服务器和数据库是你的。卸载本插件不会带走它们；\n  不需要时请在 Cloudflare 控制台删除。",
		phNoTokenWasPasted:           "没有粘贴任何 Cloudflare API 令牌",
		phTokenReachesNoAccount:      "这个 Cloudflare API 令牌够不到任何账户 — 可能缺少 Account Settings (read) 权限",
		phWorkerHasNoWriteToken:      "服务器有应答，却没有设置写入用的 API 令牌，这说明部署没有完全落地 — 请重新按“%s”",
		phEndpointNotAnsweringYet:    "一切都已创建，但服务器的 URL 还没有按应有的方式应答：%w",
		phPairedOn:                   "已配对一台手机 — 自 %s 起。",
		phNoPhoneIsPairedYet:         "还没有配对任何手机 — 按“%s”。",
		phNothingWasReadingAsThat:    "没有任何东西在读取，所以也没有什么可解除的。",
		phPhoneReadsNothingFromNowOn: "手机从现在起什么都读不到了。",
		phPhoneMayReadFromNowOn:      "手机从现在起可以读取。",
		phNoEncryptionKey:            "没有加密密钥 — 按“%s”",
		phNoCloudflareRouteYet:       "还没有 Cloudflare 上的服务器 — 按“%s”创建一个",
	},
	"zh-Hant": {
		phCloudflareWorker:           "你自己在 Cloudflare 上的伺服器",
		phStandTheWorkerUp:           "按「%s」",
		phTheSetupButton:             "3. 在 Cloudflare 上建立伺服器",
		phThePairButton:              "4. 配對手機",
		phTheSeePhonesButton:         "5. 檢視配對狀態",
		phTheUnpairButton:            "6. 解除配對",
		phTheRepairButton:            "7. 修復手機上的副本",
		phRepairWillSend:             "你的伺服器缺少 %d 筆記錄，還有 %d 筆是這台電腦已經沒有的。再按一次「%s」即可傳送。",
		phRepairFoundNothing:         "你的伺服器與這台電腦完全一致，沒有需要重新傳送的內容。",
		phRepairIsOnItsWay:           "%d 筆記錄正在傳往你的伺服器。",
		phStandingWithNoKey:          "伺服器已經有了，但沒有加密金鑰 — 按「%s」",
		phStandingBadKey:             "伺服器已經有了，但設定裡的加密金鑰無法使用 — 重新按「%s」",
		phCarryingTo:                 "正在送達: %s。",
		phCarryingNowhere:            "尚未送達任何地方。",
		phNothingIsTicked:            "尚未送達任何地方：「送到哪裡」裡沒有勾選任何位置。",
		phWaitingOn:                  "等待: %s。",
		phNowhere:                    "任何地方",
		phAnd:                        "和",
		phComma:                      "、",
		phCodeNotDrawn:               "QR 碼無法繪製 (%w) — Amenbo Viewer 在 %s",
		phPointTheCamera:             "用手機相機對準 QR 碼。Amenbo Viewer 也在 %s",
		phReadThisWithTheCamera:      "用手機相機對準 QR 碼。",
		phNoScreenForTheTokenPage:    "這裡沒有可以開啟它的螢幕。Cloudflare API 權杖頁面在 %s",
		phTokenPageNotOpened:         "Cloudflare API 權杖頁面無法開啟 (%w) — 它在 %s",
		phTokenPageIsOpen:            "Cloudflare API 權杖頁面已開啟，所需權限已經勾選。依序按 Continue to summary 和 Create Token，再把顯示出來的內容貼到「%s」後面的輸入欄裡。",
		phBuildingInAccount:          "正在帳戶 %s 中建置",
		phDatabaseCreated:            "資料庫 %s 已建立",
		phDatabaseAlreadyThere:       "資料庫 %s 本來就有",
		phWorkerDeployed:             "伺服器 %s 已部署",
		phNoWorkersDevName:           "伺服器已部署，但這個帳戶還沒有可供它回應的 workers.dev 名稱。請在 %s 選一個，然後重新按「%s」",
		phTheRouteIsUp:               "Cloudflare 上的伺服器已在 %s 就位",
		phTheKeyWasKept:              "設定裡原有的加密金鑰被保留，因此用它配對過的手機仍然可以讀取。",
		phANewKeyWasGenerated:        "已產生新的加密金鑰 — 用「%s」配對一台手機。",
		phTheWorkerIsYours:           "伺服器和資料庫是你的。解除安裝本外掛不會帶走它們；\n  不需要時請在 Cloudflare 主控台刪除。",
		phNoTokenWasPasted:           "沒有貼上任何 Cloudflare API 權杖",
		phTokenReachesNoAccount:      "這個 Cloudflare API 權杖搆不到任何帳戶 — 可能缺少 Account Settings (read) 權限",
		phWorkerHasNoWriteToken:      "伺服器有回應，卻沒有設定寫入用的 API 權杖，這表示部署沒有完全落地 — 請重新按「%s」",
		phEndpointNotAnsweringYet:    "一切都已建立，但伺服器的 URL 還沒有按應有的方式回應：%w",
		phPairedOn:                   "已配對一台手機 — 自 %s 起。",
		phNoPhoneIsPairedYet:         "還沒有配對任何手機 — 按「%s」。",
		phNothingWasReadingAsThat:    "沒有任何東西在讀取，所以也沒有什麼可解除的。",
		phPhoneReadsNothingFromNowOn: "手機從現在起什麼都讀不到了。",
		phPhoneMayReadFromNowOn:      "手機從現在起可以讀取。",
		phNoEncryptionKey:            "沒有加密金鑰 — 按「%s」",
		phNoCloudflareRouteYet:       "還沒有 Cloudflare 上的伺服器 — 按「%s」建立一個",
	},
}
