// Generated by `make -C worker baked` from worker/src. Edit the TypeScript, not this.
var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// src/index.ts
var NOT_BUILT_YET = "not built yet \u2014 this endpoint has no handler behind it";
var index_default = {
  async fetch(request, env) {
    if (!env.WRITE_TOKEN) {
      return problem(503, "this Worker has no WRITE_TOKEN set \u2014 run `wrangler secret put WRITE_TOKEN`");
    }
    const carrying = await kindOffered(request, env);
    if (!carrying) {
      return problem(401, "a bearer token is required", { "WWW-Authenticate": "Bearer" });
    }
    const { pathname } = new URL(request.url);
    const labelled = pathname.match(LABELLED_TOKEN);
    const allowed = labelled ? TOKEN_METHODS : ROUTES[pathname];
    if (!allowed) {
      return problem(404, "no such endpoint");
    }
    const wanted = allowed[request.method];
    if (!wanted) {
      return problem(405, `${request.method} is not allowed here`, { Allow: Object.keys(allowed).join(", ") });
    }
    if (wanted !== carrying) {
      return problem(403, `this endpoint takes the ${wanted} token, and a ${carrying} token was offered`);
    }
    if (labelled) {
      return revoke(env, decodeURIComponent(labelled[1]));
    }
    if (pathname === "/tokens") {
      return issue(env, request);
    }
    return problem(501, NOT_BUILT_YET);
  }
};
var ROUTES = {
  "/snapshot": { PUT: "write", GET: "read", HEAD: "read" },
  "/meta": { GET: "read", HEAD: "read" },
  "/tokens": { PUT: "write" }
};
var LABELLED_TOKEN = /^\/tokens\/(.+)$/;
var TOKEN_METHODS = { DELETE: "write" };
async function kindOffered(request, env) {
  const offered = bearer(request);
  if (offered === null) {
    return null;
  }
  if (sameSecret(offered, env.WRITE_TOKEN)) {
    return "write";
  }
  const known = await env.RECORDS.prepare("SELECT 1 FROM tokens WHERE hash = ?").bind(await sha256(offered)).first();
  return known ? "read" : null;
}
__name(kindOffered, "kindOffered");
function bearer(request) {
  const header = request.headers.get("Authorization") ?? "";
  const [scheme, ...rest] = header.split(" ");
  if (scheme.toLowerCase() !== "bearer") {
    return null;
  }
  const offered = rest.join(" ");
  return offered === "" ? null : offered;
}
__name(bearer, "bearer");
function sameSecret(offered, expected) {
  const a = new TextEncoder().encode(offered);
  const b = new TextEncoder().encode(expected);
  if (a.byteLength !== b.byteLength) {
    return false;
  }
  return crypto.subtle.timingSafeEqual(a, b);
}
__name(sameSecret, "sameSecret");
async function sha256(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
__name(sha256, "sha256");
var HASH = /^[0-9a-f]{64}$/i;
async function issue(env, request) {
  let asked;
  try {
    asked = await request.json();
  } catch {
    return problem(400, "the body has to be a JSON object");
  }
  const { label, hash } = asked ?? {};
  if (typeof label !== "string" || label.trim() === "") {
    return problem(400, "a token needs a label \u2014 it is what revoking one names");
  }
  if (typeof hash !== "string" || !HASH.test(hash)) {
    return problem(400, "the hash has to be a SHA-256 as 64 hex characters");
  }
  const issued_at = (/* @__PURE__ */ new Date()).toISOString();
  await env.RECORDS.prepare(
    "INSERT INTO tokens (label, hash, issued_at) VALUES (?, ?, ?) ON CONFLICT (label) DO UPDATE SET hash = excluded.hash, issued_at = excluded.issued_at"
  ).bind(label.trim(), hash.toLowerCase(), issued_at).run();
  return Response.json({ label: label.trim(), issued_at });
}
__name(issue, "issue");
async function revoke(env, label) {
  const gone = await env.RECORDS.prepare("DELETE FROM tokens WHERE label = ?").bind(label).run();
  if (!gone.meta.changes) {
    return problem(404, `no token is labelled ${JSON.stringify(label)}`);
  }
  return Response.json({ label });
}
__name(revoke, "revoke");
function problem(status, detail, headers = {}) {
  return Response.json({ error: detail }, { status, headers });
}
__name(problem, "problem");
export {
  index_default as default
};
