// Generated by `make -C worker baked` from worker/src. Edit the TypeScript, not this.
var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// src/index.ts
var SPEC_V = 1;
var PER_PAGE = 200;
var PER_WRITE = 500;
var index_default = {
  async fetch(request, env) {
    if (!env.WRITE_TOKEN) {
      return problem(503, "this Worker has no WRITE_TOKEN set \u2014 run `wrangler secret put WRITE_TOKEN`");
    }
    const carrying = await kindOffered(request, env);
    if (!carrying) {
      return problem(401, "a bearer token is required", { "WWW-Authenticate": "Bearer" });
    }
    const url = new URL(request.url);
    const { pathname } = url;
    const labelled = pathname.match(LABELLED_TOKEN);
    const allowed = labelled ? TOKEN_METHODS : ROUTES[pathname];
    if (!allowed) {
      return problem(404, "no such endpoint");
    }
    const wanted = allowed[request.method];
    if (!wanted) {
      return problem(405, `${request.method} is not allowed here`, { Allow: Object.keys(allowed).join(", ") });
    }
    if (wanted !== carrying) {
      return problem(403, `this endpoint takes the ${wanted} token, and a ${carrying} token was offered`);
    }
    if (labelled) {
      return revoke(env, decodeURIComponent(labelled[1]));
    }
    switch (pathname) {
      case "/records":
        return request.method === "PUT" ? place(env, request, "add") : read(env, url);
      case "/reset":
        return place(env, request, "replace");
      case "/meta":
        return meta(env);
      default:
        return issue(env, request);
    }
  }
};
var ROUTES = {
  "/records": { PUT: "write", GET: "read", HEAD: "read" },
  "/reset": { PUT: "write" },
  "/meta": { GET: "read", HEAD: "read" },
  "/tokens": { PUT: "write" }
};
var LABELLED_TOKEN = /^\/tokens\/(.+)$/;
var TOKEN_METHODS = { DELETE: "write" };
async function kindOffered(request, env) {
  const offered = bearer(request);
  if (offered === null) {
    return null;
  }
  if (sameSecret(offered, env.WRITE_TOKEN)) {
    return "write";
  }
  const known = await env.RECORDS.prepare("SELECT 1 FROM tokens WHERE hash = ?").bind(await sha256(offered)).first();
  return known ? "read" : null;
}
__name(kindOffered, "kindOffered");
function bearer(request) {
  const header = request.headers.get("Authorization") ?? "";
  const [scheme, ...rest] = header.split(" ");
  if (scheme.toLowerCase() !== "bearer") {
    return null;
  }
  const offered = rest.join(" ");
  return offered === "" ? null : offered;
}
__name(bearer, "bearer");
function sameSecret(offered, expected) {
  const a = new TextEncoder().encode(offered);
  const b = new TextEncoder().encode(expected);
  if (a.byteLength !== b.byteLength) {
    return false;
  }
  return crypto.subtle.timingSafeEqual(a, b);
}
__name(sameSecret, "sameSecret");
async function sha256(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
__name(sha256, "sha256");
async function standing(env) {
  const row = await env.RECORDS.prepare(
    "SELECT version, seq, updated_at, replacing, placed_from FROM store WHERE id = 1"
  ).first();
  return row;
}
__name(standing, "standing");
function halfReplaced() {
  return problem(
    503,
    "the whole of this store is being placed again, and what is here is part of it \u2014 this door answers once the last part has landed",
    { "Retry-After": "5" }
  );
}
__name(halfReplaced, "halfReplaced");
async function meta(env) {
  const now = await standing(env);
  if (now.replacing) {
    return halfReplaced();
  }
  return Response.json({
    spec_v: SPEC_V,
    version: now.version,
    seq: now.seq,
    updated_at: now.updated_at,
    placed_from: now.placed_from
  });
}
__name(meta, "meta");
async function read(env, url) {
  const asked = url.searchParams.get("since") ?? "0";
  if (!/^\d+$/.test(asked)) {
    return problem(400, "since has to be a whole number \u2014 the point in the order to read on from");
  }
  const since = Number(asked);
  const now = await standing(env);
  if (now.replacing) {
    return halfReplaced();
  }
  if (since > now.seq) {
    return problem(
      409,
      `the order here has reached ${now.seq}, and you asked to read on from ${since} \u2014 this store is not the one that cursor came from, so read again from the beginning`
    );
  }
  if (since > 0 && since <= now.placed_from) {
    return problem(
      409,
      `the whole of this store was placed again above ${now.placed_from}, and you asked to read on from ${since} \u2014 everything you have from before that has been made again, so throw it away and read from the beginning`
    );
  }
  const { results } = await env.RECORDS.prepare(
    "SELECT seq, k, op, nonce, ciphertext FROM records WHERE seq > ? ORDER BY seq LIMIT ?"
  ).bind(since, PER_PAGE + 1).all();
  const more = results.length > PER_PAGE;
  const page = more ? results.slice(0, PER_PAGE) : results;
  return Response.json({
    spec_v: SPEC_V,
    version: now.version,
    seq: page.length ? page[page.length - 1].seq : since,
    more,
    records: page.map(travelling)
  });
}
__name(read, "read");
function travelling(row) {
  if (row.op === "del") {
    return { k: row.k, op: row.op };
  }
  return { k: row.k, op: row.op, n: row.nonce ?? "", c: row.ciphertext ?? "" };
}
__name(travelling, "travelling");
async function place(env, request, placing) {
  let asked;
  try {
    asked = await request.json();
  } catch {
    return problem(400, "the body has to be a JSON object");
  }
  const { spec_v, version, part, parts, records } = asked ?? {};
  if (spec_v !== SPEC_V) {
    return problem(400, `this Worker reads spec_v ${SPEC_V}, and was sent ${JSON.stringify(spec_v) ?? "nothing"}`);
  }
  if (typeof version !== "number" || !Number.isSafeInteger(version)) {
    return problem(400, "version has to be a whole number \u2014 the backlog's own version, so a repeat can be recognised");
  }
  const of = parts === void 0 ? 1 : parts;
  const at = part === void 0 ? 1 : part;
  if (typeof of !== "number" || !Number.isSafeInteger(of) || of < 1) {
    return problem(400, "parts has to be a whole number of 1 or more \u2014 how many requests this turn is being sent in");
  }
  if (typeof at !== "number" || !Number.isSafeInteger(at) || at < 1 || at > of) {
    return problem(400, `part has to be a whole number from 1 to ${of} \u2014 which of this turn's requests this is`);
  }
  if (!Array.isArray(records)) {
    return problem(400, "records has to be a list, empty or otherwise");
  }
  if (records.length > PER_WRITE) {
    return problem(
      413,
      `one write takes ${PER_WRITE} records at most, and this one carried ${records.length} \u2014 send it in parts`
    );
  }
  const carrying = [];
  for (const record of records) {
    const checked = checkedRecord(record ?? {});
    if (typeof checked === "string") {
      return problem(400, checked);
    }
    carrying.push(checked);
  }
  const now = await standing(env);
  if (placing === "add" && now.version === version) {
    return Response.json({ seq: now.seq });
  }
  const first = at === 1;
  const last = at === of;
  const upsert = env.RECORDS.prepare(
    "INSERT INTO records (k, seq, op, nonce, ciphertext) VALUES (?, (SELECT seq FROM store WHERE id = 1) + ?, ?, ?, ?) ON CONFLICT (k) DO UPDATE SET seq = excluded.seq, op = excluded.op, nonce = excluded.nonce, ciphertext = excluded.ciphertext"
  );
  const statements = [
    // Only the first part empties: the ones after it are the rest of the same store, and
    // emptying again would leave the store holding whichever part arrived last.
    ...placing === "replace" && first ? [
      env.RECORDS.prepare("DELETE FROM records"),
      // Where this placement begins, taken before the rows it places move the order
      // on. It is written with the emptying rather than after it, so there is no
      // moment where the records are gone and nothing says they were.
      env.RECORDS.prepare("UPDATE store SET placed_from = seq WHERE id = 1")
    ] : [],
    ...placing === "replace" && first && !last ? [env.RECORDS.prepare("UPDATE store SET replacing = 1 WHERE id = 1")] : [],
    ...carrying.map((record, offset) => upsert.bind(record.k, offset + 1, record.op, record.nonce, record.ciphertext)),
    env.RECORDS.prepare("UPDATE store SET seq = seq + ? WHERE id = 1").bind(carrying.length),
    ...last ? [
      env.RECORDS.prepare(
        placing === "replace" ? "UPDATE store SET version = ?, updated_at = ?, replacing = 0 WHERE id = 1" : "UPDATE store SET version = ?, updated_at = ? WHERE id = 1"
      ).bind(version, (/* @__PURE__ */ new Date()).toISOString())
    ] : [],
    env.RECORDS.prepare("SELECT seq FROM store WHERE id = 1")
  ];
  let done;
  try {
    done = await env.RECORDS.batch(statements);
  } catch (thrown) {
    if (!outOfRoom(thrown)) {
      throw thrown;
    }
    return full();
  }
  return Response.json({ seq: done[done.length - 1].results[0].seq });
}
__name(place, "place");
var OUT_OF_ROOM = "Exceeded maximum DB size";
function outOfRoom(thrown) {
  return thrown instanceof Error && thrown.message.includes(OUT_OF_ROOM);
}
__name(outOfRoom, "outOfRoom");
function full() {
  return problem(
    507,
    "there is no room left in this store \u2014 a D1 database holds 500 MB on Cloudflare's free plan and 10 GB on the paid one, so raising the account it lives in is what makes room"
  );
}
__name(full, "full");
function checkedRecord(record) {
  const { k, op, n, c } = record;
  if (typeof k !== "string" || k === "") {
    return "every record needs a key \u2014 the string it is filed under";
  }
  if (op !== "put" && op !== "del") {
    return `a record is either a put or a del, and ${JSON.stringify(k)} said ${JSON.stringify(op) ?? "nothing"}`;
  }
  if (op === "del") {
    return { k, op, nonce: null, ciphertext: null };
  }
  if (typeof n !== "string" || n === "" || typeof c !== "string" || c === "") {
    return `a put carries a nonce and a ciphertext, and ${JSON.stringify(k)} carried neither or half`;
  }
  return { k, op, nonce: n, ciphertext: c };
}
__name(checkedRecord, "checkedRecord");
var HASH = /^[0-9a-f]{64}$/i;
async function issue(env, request) {
  let asked;
  try {
    asked = await request.json();
  } catch {
    return problem(400, "the body has to be a JSON object");
  }
  const { label, hash } = asked ?? {};
  if (typeof label !== "string" || label.trim() === "") {
    return problem(400, "a token needs a label \u2014 it is what revoking one names");
  }
  if (typeof hash !== "string" || !HASH.test(hash)) {
    return problem(400, "the hash has to be a SHA-256 as 64 hex characters");
  }
  const named = label.trim();
  const issued_at = (/* @__PURE__ */ new Date()).toISOString();
  try {
    const landed = await env.RECORDS.prepare(
      "INSERT INTO tokens (label, hash, issued_at) VALUES (?, ?, ?) ON CONFLICT (label) DO NOTHING"
    ).bind(named, hash.toLowerCase(), issued_at).run();
    if (!landed.meta.changes) {
      return problem(
        409,
        `a phone is already paired as ${JSON.stringify(named)} \u2014 cut that one off first, and pair again under the name once it is free`
      );
    }
  } catch (thrown) {
    if (!outOfRoom(thrown)) {
      throw thrown;
    }
    return full();
  }
  return Response.json({ label: named, issued_at });
}
__name(issue, "issue");
async function revoke(env, label) {
  const gone = await env.RECORDS.prepare("DELETE FROM tokens WHERE label = ?").bind(label).run();
  if (!gone.meta.changes) {
    return problem(404, `no token is labelled ${JSON.stringify(label)}`);
  }
  return Response.json({ label });
}
__name(revoke, "revoke");
function problem(status, detail, headers = {}) {
  return Response.json({ error: detail }, { status, headers });
}
__name(problem, "problem");
export {
  index_default as default
};
