// The launcher decides what shape to mask an adaptive icon into, and a circle is the one every
// launcher's shape fits inside. So the allowance is a circle of two thirds of the square — not,
// as it is easy to read it, the square of that size. This mark runs its arms out diagonally,
// which is exactly where the difference lands: fitted by its box it lost a quarter of its ink to
// the mask, and the arms read as running off the edge of the icon.
//
// Nothing else would notice. The asset is a committed PNG, generated by a script nobody runs on
// the way to a build, and the first place the clipping shows is a phone's home screen.

import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';

/// The densest of the five, which is the one with the pixels to say where an edge really falls.
const _foreground =
    'android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png';

/// The launch sheet is the same drawing at the size the foreground gave up, kept here so the two
/// cannot quietly become the same file again.
const _launchMark = 'android/app/src/main/res/mipmap-xxxhdpi/launch_mark.png';

/// Android's own allowance, as a fraction of the square's side.
const _safeDiameter = 72 / 108;

/// How far the ink reaches from the centre of [path], as a fraction of the square's side.
Future<double> _inkRadius(String path) async {
  final codec = await ui.instantiateImageCodec(File(path).readAsBytesSync());
  final image = (await codec.getNextFrame()).image;
  final pixels = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
  final size = image.width;
  final centre = size / 2;
  var reach = 0.0;

  for (var y = 0; y < size; y++) {
    for (var x = 0; x < size; x++) {
      // Alpha, the fourth of the four bytes. A pixel the smoothing left almost clear is not ink.
      if (pixels!.getUint8((y * size + x) * 4 + 3) > 8) {
        final d = math.sqrt(
          (x + 0.5 - centre) * (x + 0.5 - centre) +
              (y + 0.5 - centre) * (y + 0.5 - centre),
        );
        if (d > reach) reach = d;
      }
    }
  }
  image.dispose();
  return reach / size;
}

void main() {
  test('the launcher icon fits the circle a launcher masks it into', () async {
    final reach = await _inkRadius(_foreground);

    // A hair over is the smoothing on the outermost edge, not the drawing.
    expect(
      reach,
      lessThan(_safeDiameter / 2 + 0.002),
      reason: 'the mark reaches past the safe circle and will be clipped',
    );

    // And it is not shrunk further than it has to be: an icon smaller than its neighbours on the
    // home screen is a cost of its own, so this holds both ends.
    expect(
      reach,
      greaterThan(_safeDiameter / 2 - 0.02),
      reason: 'the mark is smaller than the room it is allowed',
    );
  });

  test('the launch sheet keeps the room the icon gives up', () async {
    // Nothing masks the launch screen — Android 12 and later draw the named icon as it is, and
    // the layer list older versions use places it in a box. Shrinking it to a circle would make
    // the mark smaller for no reason, so the two assets are drawn to different allowances and
    // this is what says so.
    expect(await _inkRadius(_launchMark), greaterThan(_safeDiameter / 2));
  });
}
